rancher/fleet

- docs/install.md
updating install.md with some fixes for minor errors and typos
> fix typo and minor errors

- scripts/build
> Adding -s and -w to all builds to reduce binary size.

- README.md
- mkdocs.yml
> Update docs to v0.3.0-alpha7

- charts/fleet-crd/templates/crds.yaml
- cmd/fleetcontroller/main.go
- go.mod
- go.sum
- pkg/agent/manifest.go
- pkg/fleetcontroller/app.go
https://github.com/rancher/fleet/issues/94
> Fix Fleet system sa and network policy for CIS

- modules/cli/agentmanifest/agent.go
- pkg/controllers/cluster/import.go
Remove Nocheck option and its legacy code.
> Remove NoCheck options

- docs/cluster-overview.md
- docs/cluster-tokens.md
Fix typo, adjust `base64` flag
> doc tweaks

- scripts/build
- scripts/package
Relevant issue: https://github.com/rancher/rancher/issues/30516
> Fix dapper build distribution

- .drone.yml
Relevant issue: https://github.com/rancher/rancher/issues/30516
> Fix Windows Dockefile agent name for drone

- modules/cli/agentmanifest/agent.go
- pkg/agent/manifest.go
- pkg/controllers/cluster/import.go
- pkg/controllers/manageagent/manageagent.go
This reverts commit 981611efbf1b0c485a99d3429374537ca4c01cac.
https://github.com/rancher/rancher/issues/29993
> Revert "add env vars to agent manifest"

- charts/fleet-agent/values.yaml
- pkg/basic/objects.go
https://github.com/rancher/rancher/issues/30471
> Add cloudprovider tolerations to fleet-agent

- pkg/basic/objects.go
Proof of concept: https://play.golang.org/p/N1gBTjjf3b6
Relevant issue: https://github.com/rancher/fleet/issues/324
> Add Linux toleration for all deployments

- charts/fleet-crd/templates/crds.yaml
- modules/cli/agentmanifest/agent.go
- modules/cli/cmds/test.go
- modules/cli/match/match.go
- pkg/agent/manifest.go
- pkg/apis/fleet.cattle.io/v1alpha1/bundle.go
- pkg/apis/fleet.cattle.io/v1alpha1/git.go
- pkg/bundle/match.go
- pkg/controllers/cluster/import.go
- pkg/controllers/git/git.go
- pkg/controllers/manageagent/manageagent.go
- pkg/match/cluster.go
- pkg/target/partition.go
- pkg/target/target.go
https://github.com/rancher/rancher/issues/29993
> add env vars to agent manifest

- pkg/helmdeployer/deployer.go
https://github.com/rancher/fleet/issues/225
> Limit name to 53 characters

- pkg/bundle/resources.go
- pkg/controllers/controllers.go
- pkg/controllers/git/git.go
https://github.com/rancher/fleet/issues/340
https://github.com/rancher/fleet/issues/341
> Handle the error for private helm repo

- charts/fleet-agent/values.yaml
- https://github.com/rancher/fleet/issues/345
- https://github.com/rancher/rancher/issues/32290
This is ready for review, but https://github.com/rancher/rancher/pull/32291 must be merged first.
> Enable fleet-agent image to be detected for images list generation

- charts/fleet/templates/deployment.yaml
- charts/fleet/values.yaml
https://github.com/rancher/fleet/issues/348
> Add proxy setting for fleet-controller

- .drone.yml
- manifest-agent.tmpl
- https://github.com/rancher/fleet/issues/345
- https://github.com/rancher/rancher/issues/32016
- https://github.com/rancher/rancher/issues/32290
Relevant PRs:
- https://github.com/rancher/rancher/pull/32246
Tasks issue to ensure we can add ARCH in the future: https://github.com/rancher/tasks/issues/190
> Drop ARCH from Windows agent images

- docs/gitrepo-structure.md
Update for git repo structure to show how to use 
* valuesFiles
* cluster labels as variable values
> Docs: git-repo structure update to add valuesFiles and label reference

- README.md
> updating path to fleet-examples simple

- docs/gitrepo-structure.md
> Add valuesFrom disclaimer to docs

- docs/gitrepo-structure.md
- go.mod
- pkg/helmdeployer/deployer.go
- pkg/helmdeployer/deployer_test.go
- https://github.com/rancher/fleet/issues/384
- https://github.com/rancher/fleet/issues/436
For readability: I've also moved type definitions to the top of the deploy file, and non-method functions to the bottom of the deploy file.
> Drop nil cache check for valuesFrom, add unit test and docs examples for it

- go.mod
- go.sum
- pkg/controllers/cluster/import.go
Relevant issue: https://github.com/rancher/rancher/issues/33203
Tested locally with this workflow: https://github.com/rancher/rancher/issues/33203#issuecomment-881653533
`fleet-system` no longer gets deleted.
> Ensure fleet-system does not get deleted upon upgrade

- modules/cli/apply/apply.go
- pkg/controllers/image/image.go
https://github.com/rancher/fleet/issues/437
https://github.com/rancher/fleet/issues/378
> Fix resource empty issue and give better status on imageScan

- DEVELOPING.md
- pkg/config/config.go
- pkg/controllers/cluster/import.go
Relevant issue: https://github.com/rancher/rancher/issues/33677
> Delete old agent resources upon upgrade

- pkg/controllers/bootstrap/bootstrap.go
- pkg/controllers/cluster/import.go
- pkg/controllers/data.go
- pkg/namespace/util.go
- https://github.com/rancher/rancher/issues/33203
- https://github.com/rancher/rancher/issues/33819
> Ensure namespace is not deleted (again) and delete old agent after new one is created

- pkg/controllers/cluster/import.go
- pkg/controllers/controllers.go
- pkg/namespace/util.go
Relevant issue: https://github.com/rancher/rancher/issues/33203
> Delete leftover clusters namespace if changed from default

- pkg/controllers/cluster/controller.go
- pkg/controllers/controllers.go
Relevant issue: https://github.com/rancher/fleet/issues/478
> Delete clusterRegs and their child objects upon cluster deletion

- DEVELOPING.md
> Split standalone and rancher dev docs

- DEVELOPING.md
- modules/cli/agentmanifest/agent.go
- scripts/agent-dev
Relevant issue: https://github.com/rancher/fleet/issues/490
> Fix race condition with Fleet agent secret

- .drone.yml
Relevant issue: https://github.com/rancher/fleet/issues/492
> Fix windows 20H2 drone build

- docs/gitrepo-structure.md
See https://github.com/rancher/fleet/issues/392
> Documentation for bundle dependencies

- docs/gitrepo-structure.md
Reverts https://github.com/rancher/fleet/commit/d45ae281f1bce8331f128fb5c68138ec8cbba3fd
> Docs readd valuesFrom

- DEVELOPING.md
- https://github.com/rancher/fleet/issues/531
- https://github.com/rancher/rancher/issues/34716
> Add docs for double agent scenario

- charts/fleet/templates/configmap.yaml
- charts/fleet/values.yaml
- pkg/config/config.go
- pkg/controllers/bootstrap/bootstrap.go
https://github.com/rancher/rancher/issues/34866
> Add ability to assign agentNamespace for local cluster from helm install

- package/Dockerfile
- package/Dockerfile.agent
> Update alpine base image versions to `3.14.2`

- DEVELOPING.md
- README.md
- RELEASE.md
https://github.com/rancher/fleet/issues/549
> Add Fleet release doc

- charts/fleet-agent/values.yaml
https://github.com/rancher/fleet/issues/551
> Bump kubectl to match other k8s dependencies (v1.21.3)

- modules/cli/apply/apply.go
https://github.com/rancher/fleet/issues/432
> Limit bundle name to 63 characters

- go.sum
- modules/cli/apply/apply.go
- pkg/bundle/read.go
- pkg/bundleyaml/bundleyaml.go
- pkg/bundleyaml/bundleyaml_test.go
- pkg/helm/helm.go
Primary issue (contains child issues): https://github.com/rancher/fleet/issues/593
> Allow for fleet.yml

- DEVELOPING.md
https://github.com/rancher/fleet/issues/609
https://github.com/rancher/fleet/issues/611
> Add Windows dev, charts forking, and split standalone in dev docs

- .drone.yml
- manifest-agent.tmpl
Linked Issues: 
* https://github.com/rancher/fleet/issues/603
* https://github.com/rancher/windows/issues/104
Signed-off-by: Jamie Phillips <jamie.phillips@suse.com>
> Adding Windows Server 2022 agent image builds.

- charts/fleet-agent/templates/deployment.yaml
- charts/fleet-agent/values.yaml
- charts/fleet/charts/gitjob/Chart.yaml
- charts/fleet/charts/gitjob/templates/deployment.yaml
- charts/fleet/charts/gitjob/values.yaml
- charts/fleet/templates/deployment.yaml
- charts/fleet/values.yaml
- cmd/fleetagent/main.go
- cmd/fleetcontroller/main.go
- pkg/agent/manifest.go
https://github.com/rancher/fleet/issues/242
~Need to merge https://github.com/rancher/gitjob/pull/45 first.~ Gitjob chart is updated to v0.1.23.
> Add debug log for fleet

- docs/multi-cluster-install.md
> Added note about multi-cluster installation per feedback

- docs/advanced-users.md
- mkdocs.yml
Closes #646 
- New Advanced Users section added; will continue to update this as Fleet standalone issues arise that need support.
> Added new advanced users section, updated mkdocs.yml

- .github/workflows/label-all-opened-issues.yml
Created based on https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues
Tested already in https://github.com/rancher/cis-operator/pull/109
> Create label-all-opened-issues.yml to add team labels to any issue that is opened or reopened

- docs/multi-cluster-install.md
If you have a lot of clusters, it's easiest to grab them by `CLUSTERNAME`
> fix: Update command to get cluster cert

- docs/advanced-users.md
> Added note for advanced users about nested GitRepos

- pkg/bundle/resources.go
Resolves issue https://github.com/rancher/fleet/issues/428.
> Fix go-getter parameter handling with helm chart url

- docs/gitrepo-structure.md
Closes #543 
Reference: https://fleet.rancher.io/gitrepo-structure/#reference
> Added values.yaml order of acceptance to docs

- docs/troubleshooting.md
> Added more troubleshooting tips for Bundle, GitRepo error states

- docs/concepts.md
- docs/troubleshooting.md
Closes #624 
References:
https://fleet.rancher.io/concepts/ - added link to new section in troubleshooting
https://fleet.rancher.io/troubleshooting/#naming-conventions-for-crds - new section
> Added new section for CRD naming conventions

- docs/gitrepo-add.md
> Added notes on fleet-local, fleet-default special purposes

- docs/troubleshooting.md
Closes #142
See https://github.com/rancher/docs/pull/3718
Added note of explanation in Fleet and pointer back to Rancher docs.
> Added note and pointer back to Rancher docs for WaitCheckIn state

- .drone.yml
- manifest-agent.tmpl
- manifest.tmpl
- scripts/build
Add s390x support to rancher/rancher
Part of https://github.com/rancher/rancher/issues/35501
> Add s390x arch support

- docs/troubleshooting.md
> Added new debug logging feature to Fleet docs

- go.mod
- go.sum
> Update go-getter to v1.5.11

- package/Dockerfile
- package/Dockerfile.agent
Bump to Alpine version to fix some CVEs in the base image.
Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>
> Bump to Alpine version

- charts/fleet-agent/Chart.yaml
- charts/fleet-crd/Chart.yaml
- charts/fleet-simulator/Chart.yaml
- charts/fleet-simulator/templates/deployment.yaml
- charts/fleet-simulator/values.yaml
- charts/fleet/Chart.yaml
Adding the permits-os annotation.
* https://github.com/rancher/rancher/issues/36401
> Adding permits-os annotation to the fleet charts.

- mkdocs.yml
Fixes https://github.com/rancher/fleet/issues/746
> Bump version of fleet

- README.md
👋 fleet maintainers!
This is my first contribution, please bear with me - although it feels pretty straightforward I might still have some aspect missed.
This will correct the syntax in the README example according to documentation, as it is it will fail.
HTH!
> README: fixes

- docs/agent-initiated.md
- docs/cluster-tokens.md
While developing [code to set up fleet automatically](https://github.com/moio/fleetaform) I found out a couple of steps missing from the documentation when deploying Fleet standalone.
I hope this helps 😃
> Docs: cluster registration fixes

- docs/troubleshooting.md
Troubleshooting when
GitRepo complains with `gzip: invalid header`
> feat: add section "gzip: invalid header"

- .github/workflows/e2e-ci.yml
- .github/workflows/e2e-multicluster-ci.yml
- README.md
Also fix typo in cron line, run daily not once a month.
> Add status badges for nightly CI runs

- README.md
> Add unit test badge

- .github/dependabot.yaml
There was a YAML indentation issue
> Fixing the dependabot config

- .github/workflows/e2e-multicluster-ci.yml
* wait for the right secret
* switch schedule to a less busy time
* trigger on charts folder changes
> Fix e2e mc workflow to wait for token

- .github/scripts/README.md
- .github/scripts/label-downstream-cluster.sh
- .github/scripts/register-downstream-clusters.sh
- .github/scripts/setup-latest-rancher.sh
- .github/scripts/upgrade-rancher-fleet-to-dev-fleet.sh
- .github/scripts/wait-for-loadbalancer.sh
- .github/workflows/rancher-integration.yml
This tests if the latest released rancher can be upgraded to dev fleet.
It runs the fleet multicluster examples to make sure the upgrade worked.
Not triggered for PRs, but:
* manually (for a branch/tag)
* daily (on master)
fixes #808
> Add rancher integration workflow

- docs/namespaces.md
> Added note on ns creation behavior in Fleet bundles

- package/Dockerfile
- package/Dockerfile.agent
This should fix https://github.com/rancher/rancher/issues/38248 by
reverting commit 7a894f65a37c384c48d159ee56a76c7adb49b607.
> Revert "Process in image uses a valid UID"

- charts/fleet/charts/gitjob/Chart.yaml
- charts/fleet/charts/gitjob/values.yaml
Bumping Gitjob to v0.1.29-rc1
https://github.com/rancher/rancher/issues/38248
> Bump GitJob to v0.1.29-rc1

- .github/workflows/e2e-ci.yml
> Enable k3s 1.24 CI Tests

- charts/fleet/charts/gitjob/Chart.yaml
- charts/fleet/charts/gitjob/values.yaml
- go.mod
- go.sum
> cherry-pick: Increment gitjob to latest release

- docs/gitrepo-structure.md
> Document defaultNamespace for targetCustomizations

- .github/workflows/label-all-opened-issues.yml
> Updating the labels automatically added to issues

- e2e/gitrepo/gitrepo_test.go
- modules/cli/agentmanifest/agent.go
- modules/cli/cmds/apply.go
- modules/cli/match/match.go
- modules/cli/pkg/progress/progress_tracking.go
- modules/cli/pkg/writer/writer.go
- pkg/bundle/read.go
- pkg/bundle/resources.go
- pkg/content/helpers.go
- pkg/controllers/bootstrap/bootstrap.go
- pkg/controllers/image/image.go
- pkg/helmdeployer/template.go
- pkg/update/filereader.go
staticcheck was complaining: https://github.com/rancher/fleet/actions/runs/2924256060
> Remove deprecated ioutil module

- modules/cli/apply/apply.go
Before https://github.com/rancher/fleet/pull/764 `fleet apply -o` would
result in a dry run, that did not reach out to a cluster.
The prune PR added pruned objects to the output, but needs to list the
bundles to do so.
The tests in fleet-examples use the output mode and run without any
cluster. They [fail for fleet 0.3.10](https://github.com/rancher/fleet-examples/runs/7975883869?check_suite_focus=true).
My feeling is we don't want to require a cluster and printing to-be-pruned bundles in dry run was not the main intent of the previous PR.
After this PR, if fleet apply is in output (= dry run) mode, it won't
contact a cluster. However it can no longer output which bundles it
would prune.
I'd prefer it, if in the future dry run was more explicitly chosen, instead of relying on the output …
> Skip pruneBundlesNotFoundInRepo in output mode

- pkg/bundle/resources.go
Shared global variable `getter.Getters` is updated in concurrently running goroutines. This causes corruption of authorization configuration for http getter when charts form various sources are used in the same git repository.
> BUG: race condition in readContent at pkg/bundle/resources.go

- e2e/assets/single-cluster/multiple-paths.yaml
- e2e/single-cluster/single_cluster_test.go
- modules/cli/apply/apply.go
This fixes https://github.com/rancher/rancher/issues/38672 on the release branch
> [0.3] Fix pruning issue

- .github/workflows/aks.yml
I propose to switch the Azure login credentials to this format, so it's easier in the future what to do to rotate credentials
> Update Azure login credentials

- .github/workflows/gke.yml
Deploy the GKE test cluster in fleet-ci network
@manno If you prefer I can create a variable for this setting
> Deploy the GKE test cluster in fleet-ci network

- .github/workflows/gke.yml
I am opening this pullrequest for visibility but I am gonna merge it right away
> fix: specify network in cluster creation command

- docs/gitrepo-structure.md
Add missing doc for targetCustomizations.clusterName selector
See https://github.com/rancher/fleet/blob/master/pkg/apis/fleet.cattle.io/v1alpha1/bundle.go#L98
> Add missing doc for targetCustomizations.clusterName selector

- e2e/assets/bundle-diffs/gitrepo.yaml
- e2e/gitrepo/gitrepo_test.go
- e2e/multi-cluster/multi_cluster_test.go
- e2e/single-cluster/bundle_diffs_test.go
- e2e/single-cluster/single_cluster_test.go
- e2e/testenv/githelper/gitrepo.go
- e2e/testenv/kubectl/kubectl.go
- modules/agent/pkg/controllers/cluster/cluster.go
- modules/agent/pkg/deployer/manager.go
- modules/agent/pkg/deployer/monitor.go
- pkg/bundle/bundle.go
This adds a test for the [bundle-diff](https://fleet.rancher.io/bundle-diffs/) feature.
Refers to https://github.com/rancher/fleet/issues/927
> Add bundle diff test

- pkg/options/calculate.go
Fix #928
When #928 was implemented the handling in the merge function was missed.
> Adding Helm Atomic to merge handling

- modules/agent/pkg/controllers/bundledeployment/controller.go
The fields are ignored in the JSON struct, however it would still trigger a status update, which would trigger another MonitorBundle call. The reason behind that is, that the structs are different, even though the marshalled JSON is not.
Refers to https://github.com/rancher/fleet/issues/760
> Remove ignored fields from status struct, to avoid loop

- e2e/assets/single-cluster/helm-oci.yaml
- e2e/single-cluster/single_cluster_test.go
Remove obsolete branch reference and move OCI test to the gitrepo resource area.
> Clean up Helm OCI test

- .github/workflows/aks.yml
- .github/workflows/e2e-ci.yml
- .github/workflows/eks.yml
- .github/workflows/gke.yml
- e2e/assets/single-cluster/helm-oci-with-auth.yaml
- e2e/single-cluster/single_cluster_test.go
- pkg/bundle/resources.go
- pkg/controllers/clusterregistrationtoken/handler.go
- pkg/controllers/git/git.go
This is the same PR as #997 but pushed to a repo where the rests can run.
> [v0.5] Cherry Pick Token and oci fixes

- .github/workflows/aks.yml
- .github/workflows/e2e-ci.yml
- .github/workflows/eks.yml
- .github/workflows/gke.yml
- e2e/assets/single-cluster/helm-oci-with-auth.yaml
- e2e/require-secrets/gitrepo_test.go
- e2e/require-secrets/oci_auth_test.go
- e2e/require-secrets/suite_test.go
- e2e/single-cluster/single_cluster_test.go
to prevent issues with pull requests from forked repos.
> Split test

- .github/pull_request_template.md
As requested by QA team, to increase visibility on pullrequest that need to be tested.
I propose to add "QA validation request" to the default pullrequest template
> Add QA validation request to pullrequest template

- modules/agent/pkg/controllers/bundledeployment/controller.go
- pkg/apis/fleet.cattle.io/v1alpha1/bundle.go
- pkg/helmdeployer/deployer.go
- pkg/summary/summary.go
This is a cherry pick of #1042 to the release 0.5 branch.
> [v0.5] Stop requeuing on failed deployments

- .github/workflows/aks.yml
- .github/workflows/e2e-ci.yml
- .github/workflows/e2e-multicluster-ci.yml
- .github/workflows/eks.yml
- .github/workflows/gke.yml
- .github/workflows/rancher-integration.yml
- e2e/assets/gitrepo/gitrepo.yaml
- e2e/assets/single-cluster/helm-oci-with-auth.yaml
- e2e/require-secrets/gitrepo_test.go
- e2e/require-secrets/oci_auth_test.go
- e2e/require-secrets/suite_test.go
- e2e/single-cluster/bundle_diffs_test.go
- e2e/single-cluster/single_cluster_test.go
- e2e/testenv/template.go
CI setup wasn't updated in release branch. Skipping tests that require secrets was missing. This should allow to merge code from forks into the release branch.
> Update test env from master branch

- charts/fleet/templates/configmap.yaml
- pkg/agent/agent.go
- pkg/agent/manifest.go
- pkg/agent/manifest_test.go
- pkg/config/config.go
- pkg/controllers/manageagent/manageagent.go
Cherry Pick #1053 for 0.5 release
> [v0.5] Cluster specific registry replaces global registry

- pkg/controllers/bundle/controller.go
- pkg/controllers/display/displaycontrollers.go
- pkg/controllers/git/git.go
- pkg/target/target.go
refers to #1079 - investigating the target selection
> More comments

- pkg/controllers/bundle/controller.go
- pkg/options/calculate.go
- pkg/summary/summary.go
- pkg/target/partition.go
- pkg/target/target.go
Preparation work for #1085.
Should be all harmless refactorings and comment improvements.
> Refactorings and comments

- pkg/config/config.go
- pkg/controllers/bootstrap/bootstrap.go
- pkg/controllers/cluster/import.go
- pkg/controllers/clusterregistration/controller.go
- pkg/controllers/clusterregistrationtoken/handler.go
- pkg/controllers/manageagent/manageagent.go
Comments from investigating the cluster registration flow
refers to #1079
> Cluster registration debug messages and comments

- pkg/controllers/git/git.go
> [v0.4] Parameter Generation Fix

- .github/workflows/ci.yml
- .github/workflows/e2e-ci.yml
- .github/workflows/e2e-multicluster-ci.yml
- DEVELOPING.md
This would not interfere with the PR.
> Trigger workflows for push to a release branch

- cmd/fleetagent/main.go
When a SIGTERM was sent it caused the context to complete. The context completing due to canceling is recorded as an error. Returning the context Error returned an error which triggered a non-zero exit code. This is not the intent. Returning nil instead. Nil is what is returned by other wrangler users for this situation and reason.
This context is only canceled on a signal. So, it should be safe to ignore the error on this context.
Relates to #1096
This is difficult to test as wrangler has a related issue causing a non-zero exit code elsewhere.
```shell
cd cmd
go run ./fleetagent --namespace cattle-fleet-system
kill [process id]
```
Note, this will have a leader election error as well.
More detail on this is in the linked …
> Returning nil on signal exit

- .github/scripts/deploy-fleet.sh
- dev/setup-fleet
- e2e/assets/helm-verify.yaml
- e2e/single-cluster/helm_verify_test.go
- pkg/controllers/bundle/controller.go
> Running helm template to set up status ignores errors

- .github/scripts/upgrade-rancher-fleet-to-dev-fleet.sh
* avoid downgrade of CRD chart
* fix waiting for bundle setup code
> Avoid downgrade in CI

- pkg/controllers/controllers.go
- pkg/controllers/display/displaycontrollers.go
Refactoring: remove unused parameter
> Refactoring: remove unused parameter

- DEVELOPING.md
- docs/README.md
- docs/design.md
- docs/performance.md
- docs/release.md
- docs/windows.md
Split DEVELOPING.md into separate files in docs/
> Split DEVELOPING.md into separate files in docs/

- .github/scripts/upgrade-rancher-fleet-to-dev-fleet.sh
- .github/workflows/e2e-multicluster-ci.yml
- dev/setup-fleet-downstream
- e2e/assets/multi-cluster/bundle-namespace-mapping.yaml
- e2e/multi-cluster/bundle_namespace_mapping_test.go
> Fix Fleet in Rancher  CI

- charts/fleet/charts/gitjob/templates/deployment.yaml
Equivalent of #1137 for gitjob.
> gitjob: allow to run longer before killing leader during debugging

- .github/workflows/e2e-multicluster-ci.yml
- e2e/assets/multi-cluster/helm-target-customizations.yaml
- e2e/multi-cluster/multi_cluster_test.go
- modules/agent/pkg/controllers/bundledeployment/controller.go
- pkg/apis/fleet.cattle.io/v1alpha1/bundle.go
- pkg/bundle/read.go
- pkg/helmdeployer/deployer.go
- pkg/options/calculate.go
- pkg/summary/summary.go
> [v0.4] Backport two fixes for 0.4.x

- charts/fleet/templates/deployment.yaml
> [v0.5] Add emptyDir volume to Fleet controller for /tmp

- charts/fleet/templates/deployment.yaml
Refers to original issue #1161 
Refers to backport issue #1209
> [v0.4] Backport read permission fix for 1161

- e2e/assets/single-cluster/helm-kustomize-disabled.yaml
- e2e/single-cluster/single_cluster_test.go
- pkg/helmdeployer/deployer.go
Fixes: https://github.com/rancher/fleet/issues/911
Signed-off-by: Patrick Seidensal <pseidensal@suse.com>
Helm and Kustomize have different restrictions, e.g. allowed characters for file names or archive names. If both are to be used together, Kustomize will restrict some names from working, e.g. `config+test.yaml` whereas Helm won't have an issue with those. Hence, running Kustomize even no instructions for kustomizations are present might lead to issues with names in Helm charts. Therefore Kustomize should only be run if kustomizations are to be used.
> Don't run kustomize on repos without kustomization

- charts/fleet/values.yaml
- pkg/controllers/bootstrap/bootstrap.go
copied the text from the helm chart's values.yaml
> Fix comment about bootstrap gitrepo

- .github/scripts/label-downstream-cluster.sh
- .github/scripts/register-downstream-clusters.sh
- .github/scripts/setup-latest-rancher.sh
- .github/scripts/setup-rancher.sh
- .github/workflows/e2e-ci.yml
- .github/workflows/e2e-multicluster-ci.yml
- .github/workflows/fleet-upgrade-in-rancher.yml
- .github/workflows/fleet-upgrade.yml
- .github/workflows/rancher-integration.yml
- dev/delve-debug
- dev/setup-rancher-clusters
- e2e/assets/gitrepo-simple.yaml
- e2e/installation/verify_test.go
- e2e/multi-cluster/bundle_namespace_mapping_test.go
- e2e/multi-cluster/multi_cluster_test.go
- e2e/testenv/env.go
> Fleet in Rancher Upgrade

- e2e/assets/single-cluster/helm-kustomize-disabled.yaml
- e2e/single-cluster/single_cluster_test.go
- pkg/helmdeployer/deployer.go
cherry pick https://github.com/rancher/fleet/pull/1157/commits
> [v0.6] Don't run kustomize on repos without kustomization

- e2e/single-cluster/release_names_test.go
- modules/cli/apply/apply.go
- pkg/helmdeployer/deployer.go
Fix https://github.com/rancher/fleet/issues/1278
> [v0.5] Long release names shorten once

- .drone.yml
> [v0.5] Backport Fix windows drone publish step

- .github/scripts/deploy-fleet-latest-release.sh
- .github/scripts/deploy-fleet.sh
- .github/scripts/dump-failed-k3ds.sh
- .github/workflows/e2e-ci.yml
- .github/workflows/e2e-multicluster-ci.yml
- .github/workflows/fleet-upgrade.yml
- .github/workflows/rancher-integration.yml
- dev/remove-fleet
- dev/setup-k3ds
- e2e/assets/simple/gitrepo.yaml
- e2e/installation/suite_test.go
- e2e/installation/verify_test.go
- e2e/testenv/kubectl/kubectl.go
- modules/agent/pkg/agent/app.go
- modules/agent/pkg/register/register.go
- pkg/agent/agent.go
- pkg/agent/manifest.go
- pkg/basic/objects.go
- pkg/controllers/bootstrap/bootstrap.go
- pkg/controllers/cluster/import.go
- pkg/controllers/clusterregistration/controller.go
- pkg/controllers/clusterregistrationtoken/handler.go
- pkg/controllers/controllers.go
- pkg/controllers/data.go
> [0.5] Backport "Reading contents&secrets uses specific service account"

- .github/workflows/aks.yml
- .github/workflows/e2e-ci.yml
- .github/workflows/e2e-multicluster-ci.yml
- .github/workflows/eks.yml
- .github/workflows/fleet-upgrade-in-rancher.yml
- .github/workflows/fleet-upgrade.yml
- .github/workflows/gke.yml
- .github/workflows/rancher-integration.yml
The description was not correct, because the cluster is only kept if `yes` is added to the prompt.
> Improve Github Action cluster deletion prompt

- .github/workflows/golangci-lint.yml
> Bump golangci-lint

- pkg/agent/manifest.go
- pkg/apis/fleet.cattle.io/v1alpha1/target.go
- pkg/config/config.go
Just a clean up to make the deployment manifest more visible.
> Refactor agent deployment into one function

- pkg/controllers/git/git.go
> AllowedRepoPatterns in GitRepoRestriction is matched against Repo

- pkg/helmdeployer/deployer.go
When a helm upgrade is interrupted it returns the error: `another operation (install/upgrade/rollback) is in progress`. Then the release is in a `pending-upgrade` state. This happens if the `fleet-agent` pod is killed while doing an upgrade.
To solve this we do a rollback if this error was found while doing an upgrade, then retry the upgrade.
fix https://github.com/rancher/fleet/issues/637
> retry helm upgrade if it was interrupted

- charts/fleet/templates/rbac.yaml
- charts/fleet/templates/serviceaccount.yaml
Fixes https://github.com/rancher/fleet/pull/1207 which used the wrong variable name.
> Fix bootstrap.enable, do not create service account

- dev/airgap-rancher.sh
- pkg/bundlereader/loaddirectory.go
- pkg/bundlereader/resources.go
- pkg/options/calculate.go
* fix airgap helper dev script (dev)
* remove duplicate code (clean up)
* untangle bundlereader's loop (refactoring)
> Misc Cleanup

- modules/agent/pkg/register/register.go
- pkg/controllers/cleanup/handler.go
- pkg/controllers/clusterregistration/controller.go
- pkg/secret/util.go
> [v0.7] Backport cluster registration clean up fix

- charts/fleet/templates/job_cleanup_clusterregistrations.yaml
- charts/fleet/values.yaml
- go.mod
- go.sum
- integrationtests/cli/cleanup/cleanup_test.go
- integrationtests/cli/cleanup/suite_test.go
- modules/cli/apply/apply.go
- modules/cli/cleanup/cleanup.go
- modules/cli/cmds/cleanup.go
- modules/cli/cmds/root.go
- modules/cli/pkg/client/client.go
- pkg/apis/fleet.cattle.io/v1alpha1/target.go
- pkg/controllers/cluster/controller.go
Refers to  https://github.com/rancher/fleet/issues/1692
> [v0.7] Backport cleanup clusterreg hook

- .github/workflows/e2e-ci.yml
- DEVELOPING.md
- dev/README.md
- e2e/assets/gitrepo/gitrepo.yaml
- e2e/assets/gitrepo/post-receive.sh
- e2e/multi-cluster/bundle_namespace_mapping_test.go
- e2e/multi-cluster/depends_on_test.go
- e2e/single-cluster/gitrepo_test.go
- e2e/single-cluster/values_from_test.go
- e2e/testenv/env.go
- e2e/testenv/infra/cmd/setup.go
- e2e/testenv/kubectl/kubectl.go
- e2e/testenv/template.go
- e2e/testenv/template_test.go
- integrationtests/utils/utils.go
Relates to #1496
Improves the reliability of setting up `e2e/testenv/infra` by introducing a timeout of (by default) 5 minutes on three positions. One of which has not been repeatedly tried, the others have received an increased timeout. All three can be controlled by a newly introduced environment variable `CI_OCI_TIMEOUT_DURATION` which is parsed by `time.ParseDuration` and is set to `5m` if no value has been provided.
Possibly longer waiting times.
Tests should be less flaky.
> E2E: Increase testenv reliability

- go.mod
This dependency was missing to be pinned along with other `k8s.io` dependencies, which causes `go list` command to fail (which is used by some tooling and IDEs):
```
❯ go list -m -json -mod=mod all
go: k8s.io/dynamic-resource-allocation@v0.0.0: invalid version: unknown revision v0.0.0
```
The change has no effect beyond that, since running `go build` or `go mod tidy` keep working as intended and produce no changes in `go.sum`.
> Pin version of k8s.io/dynamic-resource-allocation

- .github/scripts/deploy-fleet.sh
Part of #1496
Retry on `context deadline exceeded` errors (up to three times).
By making helm package installation `--atomic`, any changes partially applied will be rolled back for retrying. `--atomic` implies `--wait`.
> --atomic 
>
> if set, upgrade process rolls back changes made in case of failed upgrade. The --wait flag will be set automatically if --atomic is used
Tests may take a bit longer.
Errors occurring to seemingly high load may be avoided by retrying.
Occurrences of this issues are documented [here](https://github.com/p-se/fleet/actions/runs/6170318253/job/16746375975) and [here](https://github.com/rancher/fleet/actions/runs/6174345608/job/16758740672?pr=1784).
> CI: Retry on context deadline exceeded

- .github/scripts/label-downstream-cluster.sh
- .github/workflows/e2e-multicluster-ci.yml
- dev/README.md
Part of #1496
* Makes a change to be able to run the multi-clusters tests locally using the dev scripts and documents the necessary configuration.
* Makes a change to be able to run the multi-clusters tests locally with [nektos/act](https://github.com/nektos/act).
> Fixes for running multi cluster E2E tests locally

- .github/workflows/e2e-ci.yml
- .github/workflows/fleet-upgrade.yml
- .github/workflows/nightly-ci.yml
- .github/workflows/rancher-integration.yml
- .github/workflows/rancher-upgrade-fleet.yml
* add fleet 0.9 rc and rancher 2.7 rc in "upgrade fleet in rancher"
* only use one worker node in k3d
* update k8s image versions
> Upgrade k3d k8s versions in CI

- internal/cmd/agent/register/register.go
- internal/cmd/controller/agent/agent.go
- internal/cmd/controller/controllers/bootstrap/bootstrap.go
- internal/cmd/controller/controllers/cluster/import.go
- internal/cmd/controller/controllers/clusterregistrationtoken/handler.go
- internal/config/config.go
- pkg/apis/fleet.cattle.io/v1alpha1/target.go
> Document APIServerURL in the config

- internal/cmd/controller/controllers/git/git.go
> Revert "Add SecurityContext to job container"

- charts/fleet/Chart.yaml
- charts/fleet/charts/gitjob/Chart.yaml
- charts/fleet/charts/gitjob/values.yaml
- internal/cmd/controller/controllers/git/git.go
backport https://github.com/rancher/fleet/pull/1875
> [backport] Add SecurityContext to job container

- charts/fleet/templates/job_cleanup_clusterregistrations.yaml
Fix #1843 
Adds a security context (like the one defined for the fleet-agent) to the cleanup job.
The cleanup job runs just fine. I wasn't able to get the e2e tests to run on my machine, so it's up to github :)
None identified.
Maybe the possibility to define the securityContext for the containers in the helm chart would be meaningful, for use cases with restrictive security policies (like gatekeeper enforcing a complete security context for pods to run).
> Add security context to token cleanup job

- internal/cmd/controller/target/target.go
- internal/cmd/controller/target/target_test.go
Part of #1842
These changes add an indexer for BundleDeployments' Informer, which will build an index of BundleDeployment objects based on the Bundle that generated them (uniquely identified by their namespace + name). This provides an optimization over constantly using `List` with multiple label selectors.
This will be also back-ported to 0.7 and 0.8 to provide a fix for the original reporters.
Unit tests have been adapted to match the new code.
```shell
go test ./internal/cmd/controller/target
```
No expected side effects despite a marginal memory usage increase due to keeping the new index in memory.
CPU usage drop proportional to the number of bundles and downstream clusters.
> Use index when listing BundleDeployments by Bundle

- internal/cmd/agent/root.go
- internal/cmd/builder.go
- internal/cmd/cli/apply.go
- internal/cmd/cli/cleanup.go
- internal/cmd/cli/root.go
- internal/cmd/cli/test.go
- internal/cmd/controller/root.go
- internal/cmd/debug.go
Follow-up of #1896, further simplifying code and flags configuration.
> Small refactor of debug flags handling

- dev/setup-fleet
- dev/update-fleet-in-rancher-k3d
Less logging, since wrangler/v2 adds round tripper HTTP debug messages.
> Lower debug level in dev scripts

- pkg/apis/fleet.cattle.io/v1alpha1/generic_map.go
- pkg/apis/fleet.cattle.io/v1alpha1/generic_map_test.go
Relates to #1842
The current `GenericMap`'s `DeepCopy` method is calling `wrangler/pkg/convert.ToObj` in order to be a copy of the map. This function uses `encoding/json` to serialize and deserialize in order to get a new independent copy of the entire map. However, since `encoding/json` uses reflection, this approach is more CPU-intensive than other alternatives, like using native recursion.
<p align="center">
</p>
This shows how up to a 9% of the time from a 30s profile is spent on `convert.ToObj`.
Also, I ran a simple benchmark to get an estimation on how both implementations behave:
```
BenchmarkDeepCopy/json-small-12         	  160172	      7147 ns/op
BenchmarkDeepCopy/native-small-12       	 1204741	       994.6 ns/op
BenchmarkDeepCopy/json-big-12           	     781	   1510766 …
```
> Replace json-based implementation of DeepCopy on GenericMap

- internal/cmd/agent/clusterstatus.go
- internal/cmd/agent/controller.go
- internal/cmd/agent/register.go
- internal/cmd/agent/root.go
* remove logrus
Follow up to #1905
> Fix debug flag in agent commands

- package/Dockerfile
- package/Dockerfile.agent
> Switch container images to scratch and suse/git

- internal/cmd/controller/target/target.go
- internal/cmd/controller/target/target_test.go
Backporting https://github.com/rancher/fleet/pull/1857
Part of https://github.com/rancher/fleet/issues/1842
> [v0.9] Backport: Use index when listing BundleDeployments by Bundle

- e2e/assets/fleet-upgrade/gitrepo-simple.yaml
Needs https://github.com/rancher/fleet-test-data/pull/12
> Switch upgrade test to fleet-test-data repo

- .github/workflows/port-issue.yml
Copied from https://github.com/sebtestorg2/actions-test/blob/main/.github/workflows/port-issue.yml
> Add workflow for porting issues

- .github/workflows/port-issue.yml
> Use a different secret for GITHUB_TOKEN

- .github/scripts/release-against-rancher.sh
Refers to https://github.com/rancher/rancher/pull/42000
> Adapt release script to build.yaml

- manifest-agent.tmpl
- manifest.tmpl
- scripts/build
follow up to https://github.com/rancher/fleet/pull/2056
> [v0.9] remove remaining s390x drone

- .github/scripts/k3d-import-retry.sh
- .github/workflows/e2e-ci.yml
- manifest-agent.tmpl
- manifest.tmpl
- scripts/build
follow up to https://github.com/rancher/fleet/pull/2056
> [v0.8] Remove remaining s390x from drone publish

- charts/fleet/Chart.yaml
- charts/fleet/charts/gitjob/Chart.yaml
- charts/fleet/charts/gitjob/values.yaml
Refers to https://github.com/rancher/fleet/issues/1997
> Bump to gitjob chart v0.9.1

- manifest-agent.tmpl
- manifest.tmpl
- scripts/build
follow up to https://github.com/rancher/fleet/pull/1995
> Remove remaining s390x

- charts/fleet-crd/templates/gitjobs-crds.yaml
- charts/fleet/Chart.yaml
- charts/fleet/charts/gitjob/Chart.yaml
- charts/fleet/charts/gitjob/values.yaml
Refers to https://github.com/rancher/fleet/issues/2084
> Bump gitjob 0.8.1

- integrationtests/cli/assets/bundle/bundle-all.yaml
- integrationtests/cli/assets/bundle/bundle.yaml
- integrationtests/cli/assets/bundledeployment/bd-only.yaml
- integrationtests/cli/assets/bundledeployment/bd.yaml
- integrationtests/cli/assets/bundledeployment/content.yaml
- integrationtests/cli/deploy/deploy_test.go
- integrationtests/cli/deploy/suite_test.go
- integrationtests/cli/target/suite_test.go
- integrationtests/cli/target/target_test.go
- integrationtests/utils/kubeconfig.go
- internal/cmd/cli/apply.go
- internal/cmd/cli/cleanup.go
- internal/cmd/cli/deploy.go
- internal/cmd/cli/root.go
- internal/cmd/cli/target.go
- internal/cmd/cli/test.go
refers to https://github.com/rancher/fleet/issues/2110
depends on https://github.com/rancher/fleet/pull/2111
> Add target/deploy/dry-run CLI commands

- dev/README.md
Refers to https://github.com/rancher/fleet/pull/2137
> Add dev docs for changing the infra command

- charts/fleet/templates/job_cleanup_clusterregistrations.yaml
Refers to https://github.com/rancher/fleet/issues/2196
Backport of #1884
This is a backport of PR #1862 to v0.9.
> [v0.9]  Add security context to token cleanup job

- internal/cmd/controller/reconciler/bundle_controller.go
- internal/manifest/manifest.go
- internal/manifest/store.go
- internal/manifest/store_test.go
Refers to https://github.com/rancher/fleet/issues/2214
> Only create Content resource if Bundle matches any target

- .github/scripts/k3d-import-retry.sh
- .github/scripts/setup-latest-rancher.sh
There seems to be a problem with the "waiting for agent bundle" code. This seems to fix it and makes it more verbose.
Tested here: https://github.com/manno/fleet/actions/runs/8392653804/job/22985791874
> Fix "Upgrade Fleet in Rancher To HEAD" CI

- internal/cmd/controller/controllers/bundle/controller.go
> Prevent creating Content objects if Bundle does not match any target

- pkg/durations/durations.go
Related to:
- #1485
- #1809
- #1985
> cleanup unused durations constants

- charts/fleet-agent/templates/deployment.yaml
- charts/fleet-agent/templates/service.yaml
- e2e/single-cluster/sharding_test.go
- internal/cmd/controller/agentmanagement/agent/manifest.go
> Add missing serviceName in fleet-agent statefulset

- package/Dockerfile
catatonit is statically compiled and 10x larger
> Switch to tini

- internal/cmd/controller/gitops/operator.go
- internal/cmd/controller/gitops/reconciler/gitjob_controller.go
- internal/cmd/controller/gitops/reconciler/gitjob_test.go
- internal/cmd/controller/reconciler/cluster_controller.go
- pkg/git/fetch.go
- pkg/git/lsremote.go
- pkg/webhook/webhook.go
> Fix gitjob log messages for controller and webhook

- dev/README.md
> Add developer docs for monitoring

- dev/README.md
Not needed after https://github.com/rancher/fleet/pull/2378
> Remove go work section from dev README

- internal/cmd/controller/reconciler/gitrepo_controller.go
Those changes will account for updates in the status of GitRepo resources,
which previously would not have been accounted for. This means updates to the
status of a GitRepo may not always have been reflected in metrics.
Changes in other controllers where metrics are being collected were not
necessary:
- Cluster
- ClusterGroup
- Bundle
- BundleDeployment
Refers to #2344
> metrics: optimize collection calls in reconciliation loops

- pkg/webhook/webhook.go
- pkg/webhook/webhook_test.go
Forward port of: https://github.com/rancher/gitjob/pull/446
Refers to: https://github.com/rancher/fleet/issues/2352
> [Forward v0.10]. Support for Azure DevOps Webhook for gitRepos using SSH URL

- .github/workflows/release-fleet.yml
This pullrequest fixes the FOSSA credentials path and then reenable the steps
> fix: enable fossa

- internal/cmd/cli/deploy.go
- internal/cmd/cli/target.go
> CLI deploy prints to stdout

- .github/workflows/golangci-lint.yml
- internal/cmd/cli/cleanup/cleanup.go
- internal/cmd/controller/reconciler/cluster_controller.go
- internal/cmd/controller/reconciler/gitrepo_controller.go
Refers to https://github.com/rancher/fleet/issues/2448
> Do not count deleted bundledeployments in cluster status

- .github/scripts/register-downstream-clusters.sh
- .github/scripts/setup-latest-rancher.sh
- .github/scripts/setup-rancher.sh
- .github/workflows/rancher-integration.yml
- dev/setup-fleet-downstream
- dev/setup-rancher-clusters
`omg.howdoi.website` no longer works.
> Switch from omg.howdoi.website to sslip.io

- e2e/single-cluster/single_cluster_test.go
- e2e/single-cluster/status_test.go
Refers to #2427
Adds an e2e test that checks status updates happen for a simple deployment
> E2e test to checks status fields

- internal/cmd/controller/reconciler/gitrepo_controller.go
Note: not adding status check tests because the recent https://github.com/rancher/fleet/pull/2503 PR already added those.
Refers to: https://github.com/rancher/fleet/issues/2449
> Adds DeleteFunc to bundle's predicate in gitrepo's controller

- _typos.toml
> Ignore typos in embedded file

- e2e/drift/drift_test.go
- internal/cmd/agent/controller/bundledeployment_controller.go
- internal/cmd/agent/deployer/deployer.go
- internal/helmdeployer/history.go
- internal/helmdeployer/rollback.go
Refers to #2518
Forward-port of #2517
> Honor Helm's MaxHistory when using drift correction

- e2e/single-cluster/status_test.go
Ensures that a GitRepo's status is not expected to _immediately_ be updated after a bundle is deleted.
This should fix [this failure](https://github.com/rancher/fleet/actions/runs/9563292770/job/26361498374).
> Fix flaky GitRepo status tests

- .github/workflows/e2e-ci.yml
- e2e/assets/drift/correction-disabled/gitrepo.yaml
- e2e/assets/drift/correction-enabled/gitrepo.yaml
- e2e/assets/drift/force/gitrepo.yaml
- e2e/drift/drift_test.go
- e2e/drift/suite_test.go
> [0.9] Fix drift end-to-end tests and run them in CI

- e2e/assets/drift/correction-enabled/gitrepo.yaml
- e2e/drift/drift_test.go
- internal/cmd/agent/deployer/normalizers/norm.go
- internal/cmd/agent/deployer/normalizers/status.go
- internal/cmd/agent/deployer/normalizers/status_test.go
Refers to #2545
Backport of #2522
> Ignore status fields during drift detection

- e2e/drift/drift_test.go
- e2e/metrics/bundledeployment_test.go
- e2e/single-cluster/delete_namespaces_test.go
- e2e/single-cluster/finalizers_test.go
- e2e/single-cluster/gitrepo_polling_disabled_test.go
- e2e/single-cluster/gitrepo_test.go
- e2e/single-cluster/helm_auth_test.go
- e2e/single-cluster/imagescan_test.go
- e2e/single-cluster/sharding_test.go
- e2e/single-cluster/single_cluster_test.go
- e2e/single-cluster/status_test.go
- integrationtests/controller/clustergroup/status_test.go
- integrationtests/gitcloner/clone_test.go
This is an attempt to fix flaky end-to-end tests and ease troubleshooting of failures detected here and there.
> Fix flaky e2e tests

- charts/fleet/templates/deployment.yaml
- internal/cmd/controller/agentmanagement/root.go
- internal/cmd/controller/root.go
This was done in the wrong container
> Agentmanagement sub command honors FLEET_PROPAGATE_DEBUG_SETTINGS_TO_AGENTS

- charts/fleet/templates/deployment_gitjob.yaml
Refers to #2505 
Updates gitjob's deployment to take into consideration nodeSelector for each shard
> Enabling NodeSelector For Gitjob's Shards

- internal/cmd/controller/agentmanagement/controllers/cluster/controller.go
- internal/cmd/controller/agentmanagement/controllers/clusterregistration/controller.go
- internal/cmd/controller/agentmanagement/controllers/clusterregistration/controller_test.go
Refers to [SURE-8456](https://jira.suse.com/browse/SURE-8456)
This pull request adds the owner reference to cluster registration request
> [SURE-8456] fix: add owner reference to cluster registration request

- .github/workflows/e2e-fleet-upgrade-ci.yml
- .github/workflows/e2e-rancher-upgrade-fleet-to-head-ci.yml
This way filenames and titles match up with main and we don't get duplicate entries in 'Actions'
> [v0.8] Rename GitHub workflows

- internal/cmd/controller/target/query.go
Leftover logrus usage in the target module.
> Replace logrus with logger when querying targets

- integrationtests/gitjob/controller/controller_test.go
- internal/cmd/controller/grutil/status.go
It also sets all the possible conditions for the possible results we obtain from computing the job result. 
Adds condition tests for Current/InProgress/Terminating/Failed job statuses.
> Fixes a gitrepo conditions flaky test

- integrationtests/gitcloner/clone_test.go
Gitcloner tests are flaky. 
The existing `Eventually` only tests for a connection, however http.Client works with http, despite the transport.
```
h := &http.Client{Transport: &http.Transport{TLSClientConfig: &tls.Config{}}}
r, err := h.Get("http://google.com")
if err != nil {
log.Fatal(err)
}
fmt.Println("Connected", string(r.Status))
```
For example: https://github.com/rancher/fleet/actions/runs/10111213828/job/27964082088?pr=2686
```
[FAILED] [127.751 seconds]
Applying a git job gets content from git repo [BeforeAll] when Cloning an https repo when cloning a public repo that contains a README.md file providing a branch clones the README.md file [networking]
[BeforeAll] /home/runner/work/fleet/fleet/integrationtests/gitcloner/clone_test.go:70
[It] …
```
> Add tls test to integrationtest setup

- .github/scripts/deploy-fleet.sh
- charts/fleet/templates/deployment_gitjob.yaml
- dev/setup-fleet
- e2e/single-cluster/sharding_test.go
- internal/cmd/controller/agentmanagement/root.go
- internal/cmd/controller/cleanup/root.go
- internal/cmd/controller/gitops/operator.go
- internal/cmd/controller/gitops/reconciler/gitjob_controller.go
Refers to #2606
Create a gitrepo associated with a shard and verify the job created is on the same node than the sharded controller 
Added a way to retrieve controllers nodeSelector to put it in the gitjob specs
> gitjob creation on the same node as the controller shard

- e2e/assets/single-cluster/namespaceLabels_targetCustomization.yaml
- e2e/single-cluster/targetCustomization_test.go
- internal/cmd/controller/target/target.go
Cherry picked compatible changes from https://github.com/rancher/fleet/pull/2664
> [v0.10] Simplify target customisation

- internal/helmdeployer/postrender.go
> [v0.10] Changes post render error when using targetNamespace or namespace

- e2e/single-cluster/status_test.go
- internal/cmd/controller/reconciler/cluster_controller.go
Refers to https://github.com/rancher/fleet/issues/2699
> Fixes status not being populated to cluster and clustergroups

- .github/scripts/deploy-fleet.sh
- charts/fleet/templates/deployment_gitjob.yaml
Refers to https://github.com/rancher/fleet/issues/2826
Also disable debug logging for tests, since it disables the security context too
> Gitjob container has writable /tmp dir

- internal/cmd/controller/gitops/reconciler/gitjob_controller.go
In order to create cabundle secret for gitjobs, add new function in gitjobcontroller
#2824
> Create CABundle Secret for gitjob

- integrationtests/gitjob/controller/controller_test.go
This adds checks in integration tests for the presence and contents of a CA bundle secret if configured in a `GitRepo`'s spec.
By the same token, it adds checks on owner references for the CA bundle secret and RBAC resources created with a `GitRepo`.
Follow-up to #2825.
Refers to #2824.
> Add integration test checks for CA bundle secret

- .github/workflows/e2e-ci.yml
- dev/setup-rancher-clusters
- e2e/testenv/fail.go
- integrationtests/gitcloner/clone_test.go
* also remove helm repo from dev script, helm config is different per user
* remove unused block from e2e ci, workflow is never scheduled
> Integrationtest waits longer for GOGS TLS

- charts/fleet/templates/deployment.yaml
- charts/fleet/values.yaml
- internal/cmd/agent/controller/bundledeployment_controller.go
- internal/cmd/controller/reconciler/cluster_controller.go
- internal/cmd/controller/reconciler/clustergroup_controller.go
- internal/cmd/controller/reconciler/imagescan_controller.go
Backport of #2897, refers to #2908
> [v0.10] Backport of Increase worker count for reconcilers

- charts/fleet/templates/job_cleanup_clusterregistrations.yaml
- charts/fleet/templates/job_cleanup_gitrepojobs.yaml
- charts/fleet/values.yaml
- integrationtests/cli/cleanup/cleanup_clusterregistrations_test.go
- integrationtests/cli/cleanup/cleanup_jobs_test.go
- integrationtests/cli/cleanup/suite_test.go
- internal/cmd/cli/cleanup.go
- internal/cmd/cli/cleanup/cleanup.go
Backport of #2907 
Refers to #2909
> [v0.10] Cleanup completed gitrepo jobs

- internal/cmd/agent/deployer/deployer.go
This prevents a log message from being produced even when a bundle deployment and its Helm release were already installed in their latest available versions.
Related to #2869
> Limit `Deployed bundle` logs

- integrationtests/gitjob/controller/controller_test.go
- internal/cmd/controller/reconciler/bundle_controller.go
This fixes a couple of errors seen eg. in [this run](https://github.com/rancher/fleet/actions/runs/11209081946/attempts/1).
> Fix linting errors

- charts/fleet/templates/deployment.yaml
- charts/fleet/values.yaml
- docs/performance.md
- internal/cmd/controller/root.go
> Remove continuous pprof

- internal/cmd/agent/controller/bundledeployment_controller.go
- internal/cmd/agent/deployer/desiredset/desiredset_compare.go
- internal/cmd/controller/imagescan/gitcommit_job.go
- internal/cmd/controller/imagescan/tagscan_job.go
- internal/cmd/controller/reconciler/bundle_controller.go
- internal/cmd/controller/reconciler/bundledeployment_controller.go
- internal/cmd/controller/reconciler/cluster_controller.go
- internal/cmd/controller/reconciler/clustergroup_controller.go
- internal/metrics/metrics.go
Error() is printed at all verbosities
> Limit debug error messages to debug log

- internal/cmd/controller/gitops/reconciler/gitjob.go
- internal/cmd/controller/gitops/reconciler/gitjob_controller.go
- internal/cmd/controller/gitops/reconciler/gitrepo_status.go
- internal/cmd/controller/gitops/reconciler/resourcekey.go
- internal/cmd/controller/gitops/reconciler/resourcekey_test.go
- internal/cmd/controller/gitops/reconciler/restrictions.go
- internal/cmd/controller/gitops/reconciler/suite_test.go
- internal/cmd/controller/gitops/reconciler/targetsyaml.go
Refers to #3036
* Partial backport of #2997
* Small changes to ease backporting
* Backport #3027
> [0.10] Backport GitRepo status resources improvements

- .github/scripts/deploy-fleet.sh
- charts/fleet-agent/templates/deployment.yaml
- charts/fleet-agent/values.yaml
- charts/fleet/templates/deployment.yaml
- internal/cmd/controller/agentmanagement/agent/manifest.go
- internal/cmd/controller/agentmanagement/root.go
Refers to https://github.com/rancher/fleet/issues/2871
> Debug security context in agent

- internal/cmd/controller/gitops/reconciler/gitjob_controller.go
> Remove unused function

- .github/workflows/release-against-test-charts.yml
This simplifies reuse of variables across steps and jobs by making use of output variables, eliminating the need for additional environment variables.
Refers to #1640.
Follow-up to #3025.
> Fix charts repo name population

- .github/workflows/release-fleet.yml
- .goreleaser.yaml
Avoid pushing images to DockerHub when building hotfixes.
> ci: use staging registry for hotfixes

- .github/scripts/wait-for-loadbalancer.sh
Prevents
```
Error from server (NotFound): the server could not find the requested resource
```
while deploying.
> dev-scripts: Wait for ingress to appear before waiting for load balancer

- .github/workflows/e2e-ci.yml
- .github/workflows/e2e-nightly-ci.yml
- dev/README.md
- dev/env.multi-cluster-defaults
- dev/env.single-cluster-defaults
3f61ba5e removed the usage of the HELM_PATH environment variable.
> Remove HELM_PATH, tests no longer use it

- internal/cmd/controller/gitops/reconciler/gitjob_controller.go
Refers to https://github.com/rancher/fleet/issues/3161
> Adds logs for new commit or error checking for the latest

- internal/cmd/controller/gitops/reconciler/gitjob_controller.go
Refers to: https://github.com/rancher/fleet/issues/3161
Backport of: https://github.com/rancher/fleet/pull/3182
> [v0.10] Adds logs for new commit or error checking for the latest

- e2e/assets/status/chart-with-template-vars/Chart.yaml
- e2e/assets/status/chart-with-template-vars/fleet.yaml
- e2e/assets/status/chart-with-template-vars/templates/configmap.yaml
- e2e/assets/status/gitrepo.yaml
- e2e/single-cluster/gitrepo_test.go
- e2e/single-cluster/status_test.go
- internal/cmd/controller/gitops/reconciler/status_controller.go
- internal/cmd/controller/reconciler/bundle_controller.go
* Import v1alpha1 package as fleet
* Show bundle errors in Bundle and GitRepo
Refers to #2943
* Add E2E tests
Refers to #2943
(cherry picked from commit 235e8efa1e857fc482ddafc7b415ec760b343d24)
Refers to #3190
> [backport v2.10] [SURE-9137] Add template errors to bundle and gitrepo status

- internal/resourcestatus/resourcekey_test.go
While working on #3209, I realized these tests are being ignored, due to the absence of a Ginkgo suite file:
```
ok  	github.com/rancher/fleet/internal/resourcestatus	0.003s [no tests to run]
```
https://github.com/rancher/fleet/actions/runs/12823018691/job/35756872772
The existing test does not need a complex setup, so there is no need to use Ginkgo.
> Fix ./internal/resourcestatus tests not being run

- internal/cmd/controller/finalize/finalize.go
Removing finalizers is an implemention detail, also raising log level to 1
> Remove logrus message for finalizer handling

- internal/cmd/agent/controller/bundledeployment_controller.go
- internal/cmd/controller/reconciler/bundle_controller.go
Refers to #3248
Backport of #3245
> [v0.11] Prevent empty Patch updates

- internal/cmd/controller/gitops/reconciler/gitjob_controller.go
Port of: https://github.com/rancher/fleet/pull/3239
Refers to https://github.com/rancher/fleet/issues/3252
> [v0.11] - Always returns result with RequeueAfter set

- .github/workflows/release.yml
> Fix condition for hotfix releases

- .github/workflows/release-fleet.yml
> [v0.11] Fix condition for hotfix releases

- internal/cmd/controller/target/builder.go
Follow-up on #2943
Part of #3277
> Add affected cluster to template error message

- dev/k3d-clean
Fixes a regression introdued in https://github.com/rancher/fleet/commit/de40675a67f1a9ce463097d6222bcf60929f1076.
> Fix dev/k3d-clean

- internal/cmd/controller/target/builder.go
Follow-up on #2943
Part of #3277
> Remove dependency to github.com/pkg/errors

- charts/fleet-crd/templates/crds.yaml
- pkg/apis/fleet.cattle.io/v1alpha1/gitrepo_types.go
Found typo in the source code on "regristry"
> Fix typo on regristry

- charts/fleet/templates/rbac_gitjob.yaml
- integrationtests/gitjob/controller/controller_test.go
- internal/cmd/controller/gitops/reconciler/gitjob.go
- internal/cmd/controller/gitops/reconciler/gitjob_controller.go
> Migrate GitJob RBAC rules

- internal/bundlereader/loaddirectory_test.go
Helm 3.17 changed the error message
> Change helm OCI download test

- integrationtests/gitjob/git/git_test.go
Adds possibly useful information as to why an issue with the environment occurred, like
```
Feb 12 09:11:47 sshd[318]: Authentication refused: bad ownership or modes for directory /data/git/.ssh
```
in
```
➜  ~/s/fleet  git:(fix-git-integration-test) ✗ go test ./integrationtests/gitjob/git
--- FAIL: TestLatestCommitSSH (4.68s)
git_test.go:272: 
Error Trace:    /home/user/src/fleet/integrationtests/gitjob/git/git_test.go:272
Error:          Received unexpected error:
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
Test:           TestLatestCommitSSH
--- FAIL: TestLatestCommitSSH/private_repo_without_known_hosts (0.04s)
testing.go:1679: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent …
```
> integrationtest/git: Print container logs if exit status is not equal to zero

- internal/cmd/controller/target/builder.go
> [backport v2.10] Add affected cluster to template error message

- .github/workflows/ci.yml
- .github/workflows/e2e-ci.yml
- .github/workflows/e2e-fleet-upgrade-ci.yml
- .github/workflows/e2e-multicluster-ci.yml
- .github/workflows/e2e-nightly-ci.yml
- .github/workflows/e2e-rancher-upgrade-fleet-to-head-ci.yml
- .github/workflows/e2e-rancher-upgrade-fleet.yml
- .github/workflows/e2e-test-fleet-in-rancher.yml
- .github/workflows/release.yml
- integrationtests/cli/cleanup/cleanup_jobs_test.go
- integrationtests/gitjob/controller/controller_test.go
Refers to https://github.com/rancher/rancher/issues/48834
> Bump k3s in workflows for 1.32

- integrationtests/gitjob/controller/suite_test.go
- internal/cmd/controller/gitops/reconciler/gitjob_test.go
There was some issue after merging https://github.com/rancher/fleet/pull/3362
This PR addresses the errors and also implements a different fake client approach.
> Fix main after merging #3362

- internal/bundlereader/read.go
- internal/cmd/cli/apply/apply.go
- internal/cmd/cli/match/match.go
- internal/cmd/controller/gitops/reconciler/gitjob.go
Refers to https://github.com/rancher/fleet/issues/3359
> Bundlereader needs to update OCI storage bundles, too

- charts/fleet-agent/templates/deployment.yaml
- internal/cmd/agent/clusterstatus.go
- internal/cmd/agent/operator.go
- internal/cmd/agent/root.go
- internal/cmd/controller/agentmanagement/agent/manifest.go
> [SURE-9419] Move agent's clusterstatus controller into the controller container

- internal/cmd/agent/clusterstatus.go
- internal/cmd/agent/operator.go
- internal/cmd/agent/register.go
- internal/cmd/agent/register/register.go
- internal/cmd/agent/root.go
> [SURE-9419] Clean-up: Only fetch AgentInfo once

- e2e/single-cluster/finalizers_test.go
- internal/cmd/controller/agentmanagement/controllers/cluster/import.go
Follow up to https://github.com/rancher/fleet/pull/3449
Fix typo.
> Fix agent deletion on cluster import

- e2e/single-cluster/finalizers_test.go
- e2e/single-cluster/oci_registry_test.go
This amends the following end-to-end test suites to reduce the risk of intermittent failures:
* OCI storage: adding checks for the updated experimental environment variable once controller pods have restarted
* finalizers:
* removing coverage for direct bundle deployment deletion, as users are not expected to deal with that resource directly
* simplifying remaining test cases, which now only scale deployments relevant to the resource being deleted (`fleet-controller` for bundles, and `gitjob` for `GitRepo`s)
> Reduce e2e flakiness

- integrationtests/controller/bundle/bundle_targets_test.go
- internal/cmd/controller/finalize/finalize.go
- internal/cmd/controller/reconciler/bundle_controller.go
Backport of: https://github.com/rancher/fleet/pull/3509
Refers to: https://github.com/rancher/fleet/issues/2995
> [v0.12] - Delete no longer targeted bundle deployments

- dev/setup-fleet
- dev/update-agent-k3d
> Dev scripts deploy agent to cattle-fleet-local-system

- internal/cmd/agent/clusterstatus.go
- internal/cmd/agent/clusterstatus/ticker.go
- internal/cmd/agent/clusterstatus/ticker_test.go
- internal/cmd/agent/operator.go
- internal/cmd/agent/register.go
- internal/cmd/agent/register/register.go
- internal/cmd/controller/agentmanagement/controllers/controllers.go
- internal/cmd/controller/agentmanagement/start.go
- internal/cmd/controller/cleanup/controllers/controllers.go
- internal/cmd/controller/cleanup/start.go
- internal/helmdeployer/impersonate.go
> [SURE-9419] Replace wrangler with controller-runtime in agent status controller

- internal/cmd/controller/gitops/reconciler/gitjob_controller.go
- internal/cmd/controller/gitops/reconciler/gitjob_test.go
For being too complex for an issue that will possibly never occur and because the implementation fails when the strings in the bundle description have a suffix that matches the beginning of the random string generated.
It tries now all the possible characters, and if all of them are found in the bundle definitions, it returns an error.
I'll also add that to the documentation.
> Removes the random string separator calculation.

- charts/fleet/templates/deployment.yaml
- charts/fleet/tests/agent-leader-election.yaml
- charts/fleet/values.yaml
- internal/cmd/agent/root.go
- internal/cmd/controller/agentmanagement/agent/agent.go
- internal/cmd/controller/agentmanagement/agent/manifest.go
- internal/cmd/controller/agentmanagement/agent/manifest_test.go
- internal/cmd/controller/agentmanagement/controllers/manageagent/manageagent.go
- internal/cmd/controller/gitops/operator.go
- internal/cmd/controller/helmops/operator.go
- internal/cmd/controller/operator.go
- internal/cmd/options.go
> [SURE-9419] Configurable agent leader election

- internal/cmd/agent/controller/drift_controller.go
Backports https://github.com/rancher/fleet/pull/3555
> [v0.11] Prevent empty patches drift reconciler

- internal/cmd/agent/controller/drift_controller.go
Backports https://github.com/rancher/fleet/pull/3555
> [v0.12] Prevent empty Patch updates from Drift reconciler

- charts/fleet/templates/deployment.yaml
- charts/fleet/templates/deployment_gitjob.yaml
- charts/fleet/templates/deployment_helmops.yaml
- charts/fleet/tests/extraAnnotations_test.yaml
- charts/fleet/tests/extraLabels_test.yaml
- charts/fleet/values.yaml
> Set extra annotations and labels for each controller separately

- charts/fleet-crd/templates/crds.yaml
- integrationtests/controller/bundle/status_test.go
- internal/cmd/controller/gitops/reconciler/status_controller.go
- internal/cmd/controller/helmops/reconciler/helmop_status.go
- internal/cmd/controller/reconciler/bundle_controller.go
- internal/cmd/controller/reconciler/bundle_status.go
- pkg/apis/fleet.cattle.io/v1alpha1/bundle_types.go
> Remove bundle.ResourceKey computation

- e2e/metrics/exporter.go
- e2e/metrics/gitjob_test.go
- internal/cmd/controller/gitops/reconciler/gitjob.go
- internal/cmd/controller/gitops/reconciler/gitjob_controller.go
- internal/cmd/controller/operator.go
- internal/metrics/metrics.go
- pkg/git/fetch.go
*Counters*
fleet_gitrepo_fetch_latest_commit_success_total
fleet_gitrepo_fetch_latest_commit_failure_total
fleet_gitjobs_created_success_total
fleet_gitjobs_created_failure_total
*Histograms*
fleet_gitjob_duration_seconds
fleet_gitrepo_fetch_latest_commit_duration_seconds
*Gauges*
fleet_gitjob_duration_seconds_gauge
Refers to #3161
> Metrics for gitjob

- internal/cmd/agent/register/register.go
- internal/cmd/controller/agentmanagement/controllers/cluster/controller.go
- internal/cmd/controller/agentmanagement/controllers/cluster/import.go
- internal/cmd/controller/agentmanagement/controllers/clusterregistration/controller.go
- internal/cmd/controller/agentmanagement/controllers/manageagent/manageagent.go
- pkg/apis/fleet.cattle.io/v1alpha1/cluster_types.go
This allows experimenting with different agent management models.
> Add agent management label to skip clusters

- internal/bundlereader/loaddirectory.go
- internal/bundlereader/loaddirectory_test.go
> Fix panic found in OCI test

- internal/cmd/agent/operator.go
- internal/cmd/agent/register/register.go
- internal/cmd/controller/agentmanagement/controllers/controllers.go
- internal/cmd/controller/agentmanagement/start.go
- internal/cmd/controller/cleanup/controllers/controllers.go
- internal/cmd/controller/cleanup/start.go
- internal/helmdeployer/impersonate.go
Use the default rate limiter, which has high defaults.
> Remove rate limiting removal

- internal/cmd/agent/clusterstatus.go
- internal/cmd/agent/operator.go
- internal/cmd/agent/register/register.go
- internal/cmd/cli/apply/apply.go
- internal/cmd/controller/agentmanagement/controllers/cluster/import.go
- internal/cmd/controller/agentmanagement/controllers/controllers.go
- internal/cmd/controller/agentmanagement/start.go
- internal/cmd/controller/cleanup/controllers/controllers.go
- internal/cmd/controller/cleanup/start.go
- internal/cmd/controller/reconciler/bundle_controller.go
- internal/cmd/controller/reconciler/bundledeployment_controller.go
- internal/helmdeployer/impersonate.go
- internal/manifest/manifest.go
- pkg/durations/durations.go
> v0.12.5-hotfix-be90

- internal/cmd/controller/reconciler/bundle_controller.go
- internal/cmd/controller/reconciler/bundledeployment_controller.go
- pkg/durations/durations.go
https://github.com/rancher/fleet/issues/4067
> [v0.13] improve bundle value secret logging

- _typos.toml
- internal/cmd/agent/operator.go
- internal/cmd/agent/register/register.go
- internal/cmd/controller/agentmanagement/controllers/controllers.go
- internal/cmd/controller/agentmanagement/start.go
- internal/cmd/controller/cleanup/controllers/controllers.go
- internal/cmd/controller/cleanup/start.go
- internal/helmdeployer/impersonate.go
> [0.12] Undo rate limiting removal
