README.md, docs/install.md
Signed-off-by: danmx <daniel@iziourov.info>
There is not `controller` command available anymore
```console
$ fleet help install
Generate manifests for installing server and agent
Usage:
flt install [command]
Available Commands:
agent-config Generate cluster specific agent config
agent-token  Generate cluster group token and render manifest to register clusters into a specific cluster group
manager      Generate deployment manifest to run the fleet controller
simulator    Generate manifest to install a cluster simulator
Flags:
-h, --help   help for install
Global Flags:
-k, --kubeconfig string   kubeconfig for authentication
-n, --namespace string    namespace (default "default")
Use "flt install [command] --help" for more information about a command.
```
```console
$ fleet help install …
```
=> fix(docs): controller -> manager in CLI examples

modules/cli/cmds/root.go
Ref: https://github.com/rancher/fleet/issues/18
```
Usage:
flt [flags]
flt [command]
Available Commands:
apply       Render a bundle into a Kubernetes resource and apply it in the Fleet Manager
help        Help about any command
install     Generate manifests for installing server and agent
test        Match a bundle to a target and render the output
Flags:
--debug               Turn on debug logging
--debug-level int     If debugging is enabled, set klog -v=X
-h, --help                help for flt
-k, --kubeconfig string   kubeconfig for authentication
-n, --namespace string    namespace (default "default")
-v, --version             version for flt
Use "flt [command] --help" for more information about a command.
```
```
Usage:
fleet [flags]
fleet [command]
Available Commands:
apply …
```
=> Fix CLI helper menu fleet name

modules/agent/pkg/controllers/controllers.go
The fleet-agent configmap is managed by Helm.  We should
not use that configmap as it will conflict with the object
managed by Helm.
=> Don't use fleet-agent configmap for leader election

charts/fleet-agent/templates/network_policy_allow_all.yaml, charts/fleet-agent/templates/patch_default_serviceaccount.yaml, charts/fleet-agent/values.yaml
1) Adding a post-install hook to patch the default serviceaccount of fleet-system namespace
2) Adding a default network_policy to the namespace to pass CIS
https://github.com/rancher/cis-operator/issues/11
=> Adding fixes to pass hardened profile of CIS scan 

scripts/package-helm
https://github.com/rancher/fleet/issues/94
Following kubectl image's tag in the  fleet-agent chart should not be replaced when we package fleet-agent chart:
```
kubectl:
repository: rancher/kubectl
tag: v1.18.6
```
Otherwise the fleet-agent chart gets the wrong kubectl image tag which cause the post install hook to not work. 
Currently this is what gets generated under rancher/charts/fleet-agent/Values.yaml
```
kubectl:
repository: rancher/kubectl
tag: v0.3.0-beta3
```
Hence fixing the script to only replace tags `dev`
=> Fix packaging script that does tag replacement to only replace dev tag

Makefile, mkdocs.yml
(because Linux desktop users only care about themselves)
Couldn't run the docs from a mac using `make serve-docs`. There were a
couple problems:
- --net=host wouldn't allow for port forwarding, needed to use a
specific port instead
- mkdocs serve only listens on localhost by default, needed to tell it
to listen on all interfaces
- listening on all interfaces caused mkdocs to emit a warning and
strict=true means that would cause it to immediately exit, needed to
turn off strict mode :grimace:
=> Allow mkdocs development on Mac

docs/gitrepo-structure.md
In fleet 0.3.0 the list of yaml overlays must be in a yaml object instead of directly in the customization object (https://github.com/rancher/fleet/blob/786b72d2c0093f21f3a565efc86d083e7555dd1a/pkg/apis/fleet.cattle.io/v1alpha1/bundle.go#L175)
=> Fix overlays definition in example fleet.yaml in docs

pkg/options/calculate.go
Currently when `Calculate` calls `merge` it is not passing a deep copy of `spec.BundleDeploymentOptions`, which contains pointers. This results in the `merge` incorrectly modifying the `base` `BundleDeploymentOptions`. 
This PR will address an issue where targetCustomizations by one cluster override the base. i.e. helm values for a specific target apply to all targets that don't have a helm values override
Signed-off-by: Matthew DeVenny <matt@boxboat.com>
=> Use deep copy in merge function

package/Dockerfile, package/Dockerfile.agent, pkg/controllers/content/controller.go, pkg/controllers/controllers.go
Signed-off-by: Matthew DeVenny <matt@boxboat.com>
Currently fleet does not cleanup the `Content` objects that are created for a `Bundle`. Over time this will result in a very large number of `Content` objects being stored on the `fleet-controller` cluster. Added a `ContentController` to purge orphans when bundleDeployments are updated.
=> Add content controller to purge orphaned contents

.drone.yml, charts/fleet-agent/templates/deployment.yaml, charts/fleet-agent/templates/patch_default_serviceaccount.yaml, charts/fleet-agent/values.yaml, charts/fleet/templates/deployment.yaml, charts/fleet/values.yaml, manifest-agent.tmpl, manifest.tmpl, modules/cli/controllermanifest/template.go, package/Dockerfile, package/Dockerfile-windows.agent, package/Dockerfile.agent, pkg/agent/manifest.go, pkg/basic/objects.go, pkg/controllers/git/git.go, scripts/build, scripts/package, scripts/version
Relevant issue: https://github.com/rancher/rancher/issues/30516
This PR adds preliminary Windows support. The `fleet-agent` has a Windows manifest, and all other components use `tolerations` and `nodeSelector` settings to be scheduled on Linux nodes.
=> Add Windows support and consolidate drone pipelines

package/Dockerfile-windows.agent, package/README.md
Relevant issue: https://github.com/rancher/rancher/issues/30516
A/B test before this change...
```powershell
PS C:\Users\Administrator\rancher-fleet> docker run test
docker: Error response from daemon: container 0b8fb491c233356bdf95208fb8bcfbc51e77f4b13d50634c6e64da26d6c8c215 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2) extra info: {"CommandLine":"C:\u000cleet\u000cleetagent-windows.exe","WorkingDirectory":"C:\\","Environment":{"RELEASES":"releases.rancher.com","VERSION":"v0.3.4-rc4"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}.
```
...after this change...
```powershell
PS C:\Users\Administrator\rancher-fleet> docker run test
Error: --namespace …
```
=> Fix unicode in Windows Fleet agent and upgrade Git to 2.30

charts/fleet-crd/templates/crds.yaml, go.mod, pkg/apis/fleet.cattle.io/v1alpha1/bundle.go, pkg/apis/fleet.cattle.io/v1alpha1/zz_generated_deepcopy.go, pkg/bundle/resources.go
Minor tweak to `fleet apply` logic to support valuesFiles in HelmOptions.
The `fleet apply` will now parse the list in valuesFiles and merge them into the `values` for the HelmOptions.
This allows users to specify values files to better organize their GitRepos rather than having all values inline.
If the same value override is defined in multiple valuesFiles, then the one in the last file will take precedence.
Helm handles setting the same variable multiple times in the same manner.
This allows user to reference valuesFiles in the fleet.yaml
For example:
```
defaultNamespace: loki
helm:
releaseName: loki
repo: https://kubernetes-charts.banzaicloud.com
chart: loki
values:
key1: value1
valuesFiles:
- values/override.yaml
targetCustomizations:
- name: dev
helm:
valuesFiles:
- …
```
=> valuesFiles support

pkg/bundle/resources.go
Don't make any assumptions about the presence of a trailing slash, and simply add on if there isn't one already
Fixes #318
=> Update helm repo url handling

pkg/target/target.go
The PR allows users to pass values to helm charts via labels on the cluster objects.
This can include cluster specific information such as name to the downstream helm chart.
fleet already applies cluster labels as helm values to all charts on the downstream cluster.
Once this change is merged, the users will be able to refer these labels directly in the values section.
```
namespace: default
helm:
releaseName: labels
values:
clusterName: global.fleet.clusterLabels.management.cattle.io/cluster-display-name
```
The fleet controller will render the bundle deployment objects after performing the replacement, which can then be picked up by the fleet-agents on the downstream cluster.
This should help address the issue: https://github.com/rancher/fleet/issues/152
=> Ability to use cluster labels as helm values

pkg/apis/fleet.cattle.io/v1alpha1/target.go, pkg/controllers/cluster/import.go, pkg/controllers/manageagent/manageagent.go, pkg/helmdeployer/deployer.go
Context:
We switched from one fleet-agent bundle per workspace to one fleet bundle per cluster in order to support agentEnvVars per cluster https://github.com/rancher/rancher/issues/29993. This has caused a problem because we have to delete old `fleet-agent` bundle and use the new name `fleet-agent-$clustername`. When deleting the `fleet-agent` bundle, `fleet-agent` deployment will also get deleted in downstream cluster, causing https://github.com/rancher/rancher/issues/32317. We need to deploy the agent if downstream cluster doesn't have the fleet-agent deployment.
=> Redeploy agent when fleet-agent deployment is deleted

charts/fleet-crd/templates/crds.yaml, pkg/apis/fleet.cattle.io/v1alpha1/target.go, pkg/controllers/cluster/import.go
We need to drop the previous deployment check logic, as it is causing chatty connection to downstream cluster when cluster is updated. Instead we will add `agentMigrated` in cluster.status to force upgrade fleet-agent on imported clusters. This is to handle the case where we migrate from one `fleet-agent` bundle per workspace to `fleet-agent` bundle per cluster, and fleet will delete fleet-agent deployment when deleting `fleet-agent` bundle, which will cause a outage(see https://github.com/rancher/rancher/issues/32317). This is fixed in https://github.com/rancher/fleet/pull/351/files#diff-7657d93aa6e7023c8a3230bb999b94845f6b607b146c9bc7e137620032683f0fR481-R485. Once agent is fully migrated to new version, we would not need to worry about this.
So, adding a new status `agentMigrated` to …
=> Add migration logic, drop deployment check

pkg/target/target.go, pkg/target/target_test.go
Fix for parsing structs types in values.
Related to https://github.com/rancher/fleet/issues/363
Prior to this change if the label names were embedded in array struct's in values section, they would not be parsed.
```
▶ more fleetlabelsdemo/fleet.yaml
namespace: default
helm:
releaseName: labels
values:
clusterName: global.fleet.clusterLabels.name
customStruct:
- name: global.fleet.clusterLabels.name
key1: value1
key2: value2
```
The additional logic handles the same. Post processing the labels are rendered correctly
```
▶ helm get values labels -n default
USER-SUPPLIED VALUES:
clusterName: local
customStruct:
- key1: value1
key2: value2
name: local
global:
fleet:
clusterLabels:
name: local
```
=> added logic to parse array structs. GH Issue 363

charts/fleet-agent/Chart.yaml, charts/fleet-crd/Chart.yaml, charts/fleet-crd/templates/crds.yaml, charts/fleet/Chart.yaml, pkg/apis/fleet.cattle.io/v1alpha1/target.go, pkg/controllers/cluster/import.go
Add new condition so that during the upgrade the fleet-agent will get
redeployed into the correct namespace. This is for migrating fleet
rancher install to cattle-fleet-system
https://github.com/rancher/fleet/issues/395
=> Redeploy agent on import cluster during upgrade

charts/fleet/templates/deployment.yaml
Accidentally put an wrong binary name on charts.
=> Fix the wrong binary name

pkg/helmdeployer/deployer.go
We do dry-run before the real install but if CR and CRD both exists in
chart, it will fail since dry-run doesn't install CRD. We need to turn
of validation in order to prevent failure
=> Fix chart with crd folder not being deployed

modules/agent/pkg/controllers/bundledeployment/controller.go, modules/agent/pkg/deployer/monitor.go, pkg/helmdeployer/deployer.go
We need to make sure setID is consistent across fleet-agent bundle, since in import controller we use a different setID and that would include extra field that shouldn't be applied to the original fleet-agent bundle.
https://github.com/rancher/fleet/issues/422
=> Make sure setID is consistent across fleet-agent bundle

DEVELOPING.md, modules/agent/pkg/deployer/monitor.go, modules/cli/apply/apply.go, pkg/helmdeployer/deployer.go, scripts/agent-dev, scripts/build
```
- Fix double agent creation when creating a GitRepo CR by ensuring a
bad update results in the error being returned.
- Add developer documentation along with agent-dev for local agent
builds.
- Fix an armv7 bug where the wrong ENV variable was used for the build
script.
- Consolidate agent bootstrap setID to one function
```
Relevant issue: https://github.com/rancher/fleet/issues/437
=> Fix double agent creation and add developer documentation

modules/cli/cmds/apply.go, modules/cli/cmds/test.go
both `fleet test` and `fleet apply` do not take `--debug` or `--debug-level`. This fixes that.
=> BUG FIX: add debug arguments to cli test and apply

docs/imagescan.md, mkdocs.yml
https://github.com/rancher/fleet/issues/378
=> Add image scan docs

charts/fleet-crd/templates/crds.yaml, cmd/fleetagent/main.go, modules/agent/pkg/agent/app.go, modules/agent/pkg/controllers/bundledeployment/controller.go, modules/agent/pkg/controllers/controllers.go, modules/agent/pkg/deployer/manager.go, modules/agent/pkg/deployer/monitor.go, modules/agent/pkg/register/register.go, modules/agent/pkg/simulator/simulator.go, modules/cli/agentconfig/agent.go, modules/cli/agentmanifest/agent.go, pkg/agent/manifest.go, pkg/apis/fleet.cattle.io/v1alpha1/target.go, pkg/config/config.go, pkg/controllers/cluster/import.go, pkg/controllers/controllers.go, pkg/controllers/manageagent/manageagent.go, pkg/helmdeployer/deployer.go
The change opens up the ability to run two or more agents pointed to
different fleet-controllers. The specific use case where this is useful
is for fleet managing a cluster that is running fleet to manage other
clusters. More concretely we have this with Rancher managing Rancher.
In this situation you want two fleet agents, one that is running for
fleet-local and one that is run for the upstream fleet-controller.
=> Allow two agents to run on the same cluster

.drone.yml, manifest-agent.tmpl, package/Dockerfile-windows.agent
- bump to dapper 0.5.7
- remove windows server 2004 SAC from drone build steps and agent manifest templates
=> remove windows 2004 SAC, bump versions

DEVELOPING.md, Dockerfile.dapper, charts/fleet-crd/templates/gitjobs-crds.yaml, charts/fleet/charts/gitjob/Chart.yaml, charts/fleet/charts/gitjob/values.yaml, pkg/apis/go.mod
Relevant issue: https://github.com/rancher/fleet/issues/573
Note to reviewers: `golangci-lint` version was chosen to be the one that works with Go 1.16.x by default
=> Bump GitJob v0.1.22 and Dapper dependencies

docs/concepts.md, docs/examples.md
Closes #627
References: 
https://fleet.rancher.io/examples/ - added lifecycle under examples page
https://fleet.rancher.io/concepts/ - added link to new section
=> Added bundle lifecycle in examples, added link from concepts page

docs/gitrepo-structure.md
Just a simple typo fix for the docs.
=> Fix typo in documentation of gitrepo structure

docs/gitrepo-structure.md, docs/quickstart.md
Closes #250; see also https://github.com/rancher/docs/issues/3705 for Rancher docs issue.
=> Added blurb on Helm chart dependencies, linked back to Rancher

modules/cli/agentmanifest/agent.go, pkg/connection/connection.go, pkg/controllers/cluster/import.go
> "In an internal knowledge transfer for Fleet development, it was evident that the kube client connection smoke tests were difficult to understand without an explicitly named function or comment. We should consolidate them to one function."
Relevant issue: https://github.com/rancher/fleet/issues/658
=> Consolidate kube client tests and remove unused client test

docs/agent-initiated.md
Dear Fleet-Team,
I just came across a small typo in the agent registration docs where the metadata section of the described cluster CRD contained the key `namespaces` instead of `namespace`.
Hope this small fix can get merged.
=> fixed config template error in agent-initiated.md

docs/concepts.md, docs/examples.md
Closes #623 
Added to the examples with https://github.com/rancher/fleet-examples/blob/master/multi-cluster/helm/fleet.yaml use case. Also added example install directions for `GitRepo` CRs.
References:
https://fleet.rancher.io/examples/#deploy-kubernetes-manifests-across-clusters-with-customization
https://fleet.rancher.io/concepts/
=> Added example config management use case, links, and example install instructions

docs/namespaces.md, docs/troubleshooting.md
Closes #489
References:
https://fleet.rancher.io/troubleshooting/#migrate-the-local-cluster-to-the-fleet-default-cluster
https://fleet.rancher.io/namespaces/
=> Added documentation for migrating the local cluster to fleet-default 

docs/troubleshooting.md
Will close https://github.com/rancher/docs/issues/3717 in Rancher docs.
Reference: https://fleet.rancher.io/troubleshooting/#http-secrets-in-github
=> Updated fleet documentation for HTTP secrets

.gitignore
ignore the `.DS_Store` file in macOS by adding it to `.gitignore`
=> ignore the .DS_Store file in macOS

.gitignore, modules/agent/pkg/deployer/normalizers/jsonpatch.go
Before this PR, Fleet only supported one jsonpatch per resource, which is why adding multiple jsonpatches would result in only the last one being applied.
Instead, this PR takes the approach of applying the JSON patches the order provided.
It also offers a small performance enhancement of only marshaling and unmarshaling the provided struct if a patch has been tracked for it.
Related Issue: https://github.com/rancher/rancher/issues/36247
=> Add support for multiple jsonpatches on a single resource

pkg/controllers/bundle/controller.go, pkg/target/target.go
https://github.com/rancher/rancher/issues/36241
Modifying/Deleting a cluster's label doesn't remove the bundles applied via clusterSelector previously. The root cause is that when the cluster update event is processed by Fleet, the controller lists all the bundles that match the cluster, but skips those bundles that do not match the updated cluster after the update. The bundleDeployments for these bundles need to be deleted for the updated cluster.
=> Delete bundleDeployment for the fleet bundle that do not match to the updated cluster

charts/fleet-crd/templates/gitjobs-crds.yaml, charts/fleet/charts/gitjob/Chart.yaml, charts/fleet/charts/gitjob/values.yaml
Bump gitjob to v0.1.26 and tekton-utils to v0.1.5. Also update gitjob CRDs according to the [developing docs](https://github.com/rancher/fleet/blob/master/DEVELOPING.md#updating-fleet-components).
Gitjob and tekton-utils bumps are related to updates in Alpine base images.
Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>
=> Bump gitjob to v0.1.26 and tekton-utils to v0.1.5 and update gitjob CRDs

.gitignore
This also affects tools like ripgrep, which would not report any findings in the main helm chart.
Note: There is a check for a dirty repo in `scripts/validate-ci`. If some part of the build system creates a fleet binary in a sub-director, then we need to adapt this PR. However all binaries seem to have suffixes.
=> Do not git ignore the charts/fleet folder

go.mod, go.sum
https://github.com/json-iterator/go/releases - fixes several crashes
This fixes flakieness when updating fleet in Rancher and with just the
fleet helm chart.
=> Bump json-iterator to v1.1.12

docs/agent-initiated.md
It seems to me that the current link is not correct because the same version number is used both for fleet and the agent helm chart.
Current docs say:
```sh
helm -n fleet-system install --create-namespace --wait \
${CLUSTER_LABELS} \
--values values.yaml \
fleet-agent https://github.com/rancher/fleet/releases/download/v0.3.9/fleet-agent-0.3.3.tgz
```
But:
```
% curl https://github.com/rancher/fleet/releases/download/v0.3.9/fleet-agent-0.3.3.tgz
Not Found
```
It is my understanding the proposed fix should work!
=> Docs: use correct artifact version

.github/workflows/golangci-lint.yml, .golangci-full.json
This adds more linters in a separate golangci config.
Does not affect the existing linter, used by drone/dapper during release. However that linter does find an error with golangci-lint 1.45.2, so I'm unclear how `scripts/validate` passes. 
This new check should not be made required for merging, until we fixed/ignored all linter warnings. Otherwise PRs would have to deal with unrelated warnings.
=> Add Github actions workflow to lint PRs

pkg/controllers/image/image.go
This PR aims at integrating an overseen case in the ImageScan feature, when the `paths` field is empty. 
The PR adds the default value for the `paths` array, which is `[1]string{"/"}`  in an intermediate `paths` variable that is then iterated on.
This is linked to the issue #650
=> Adding the case where paths field is empty when updating manifests

charts/fleet-crd/values.yaml
Added empty values.yaml to make it installable via kustomize that expects a values.yaml - even if its empty.
fixes #785
=> added empty values.yaml for fleet-crd helm chart

.github/workflows/golangci-lint.yml, .golangci-full.json, modules/agent/pkg/deployer/monitor.go, modules/agent/pkg/deployer/normalizers/mutatingwebhook.go, modules/agent/pkg/deployer/normalizers/norm.go, modules/agent/pkg/deployer/normalizers/validatingwebhook.go, modules/agent/pkg/register/register.go, modules/cli/agentmanifest/agent.go, modules/cli/cmds/root.go, modules/cli/controllermanifest/server.go, pkg/bundle/read.go, pkg/bundle/resources.go, pkg/bundleyaml/bundleyaml_test.go, pkg/controllers/bootstrap/bootstrap.go, pkg/controllers/bundle/controller.go, pkg/controllers/cluster/import.go, pkg/controllers/clusterregistration/controller.go, pkg/controllers/clusterregistrationtoken/handler.go, pkg/controllers/content/controller.go, pkg/controllers/git/git.go, pkg/controllers/image/image.go, pkg/update/filter.go, pkg/update/setters.go
Follow up of #757, which should be merged before. It fixes the mentioned issues or ignores them if they are not valid for us.
Regarding [enforcing TLS 1.2](https://github.com/rancher/fleet/commit/5638998e520a9343d25403df7b4bf55537f75044), it was introduced 2008, it is also the Minimum in modern browsers like Firefox without know issues, so it should not be a problem.
Nevertheless we should document it in the next release notes though if some customer has a very old https setup.
The [debug endpoint](https://github.com/rancher/fleet/commit/d7bb9c4673a420198d837eb71178e8464d7c9995) should not be a security issue because it only listens on localhost but it should in my opinion still not be enabled by default. I have not changed the code by now to not change expected behavior/use cases but we …
=> Fix linter issues

docs/quickstart.md
At time of writing (20220512), the instructions available at fleet.rancher.io/quickstart/ do not work, due to fleet.helmversion expanding to 0.3.3.
The correct version for both CRD and 'main' helm charts on github, for release 0.3.9, is 0.3.9 (e.g. https://github.com/rancher/fleet/releases/download/v0.3.9/fleet-crd-0.3.9.tgz is the download URL for the CRD chart for 0.3.9). 
The project README (https://github.com/rancher/fleet/blob/master/README.md) confirms that using a single version string is currently the correct approach.
This change follows that document by using fleet.version throughout.
=> Update quickstart.md to use fleet.version

docs/gitrepo-structure.md
`helm.valueFiles` is misspelled. The correct spelling is `helm.valuesFiles` (note the `s`).
=> Fix values.yaml order of acceptance

manifest.tmpl
This is a left-over from removing ARMv7, so we can switch to BCI images.
Refers to https://github.com/rancher/rancher/issues/38248
=> Remove armv7 from container image manifest

pkg/controllers/bootstrap/bootstrap.go, pkg/controllers/clusterregistration/controller.go, pkg/controllers/clusterregistrationtoken/handler.go, pkg/controllers/controllers.go, pkg/controllers/data.go, pkg/secret/util.go
https://github.com/rancher/rancher/issues/37885
Fleet does not work in k8s 1.24 cluster because there is no auto-generated secret-based service account token anymore in K8s 1.24. Prior to 1.24, every serviceAccount created was auto-backed by K8s by a Secret token. Now with 1.24, there will be no auto population of the Secret token for serviceaccounts.
Thus we need to create the ServiceAccount Secrets ourselves in the controllers when needed for all the serviceAccounts used in Fleet.
We need to fix this issue to support the goal of running rancher in k8s 1.24
Changes include:
- If a ServiceAccount does not have a Secret token, then Fleet will create a secret of type SecretTypeServiceAccountToken   and wait for K8s to populate it
- This change is needed for fleet-controller bootstrap and …
=> Changes to Fleet to support K8s 1.24 

charts/fleet/charts/gitjob/Chart.yaml, charts/fleet/charts/gitjob/values.yaml
Cherry-picking: Bump GitJob to v0.1.29-rc1
=> [0.3] Cherry-pick Merge pull request #879 from prachidamle/bump_gtjob

.github/scripts/deploy-fleet.sh, .github/workflows/aks.yml, .github/workflows/e2e-ci.yml, .github/workflows/e2e-multicluster-ci.yml, .github/workflows/eks.yml, .github/workflows/gke.yml, .golangci.json, e2e/assets/gitrepo/sleeper-chart/.helmignore, e2e/assets/gitrepo/sleeper-chart/Chart.yaml, e2e/assets/gitrepo/sleeper-chart/templates/deployment.yaml, e2e/assets/gitrepo/sleeper-chart/values.yaml, e2e/gitrepo/gitrepo_test.go, e2e/gitrepo/suite_test.go, e2e/multi-cluster/multi_cluster_test.go, e2e/testenv/githelper/git.go, e2e/testenv/githelper/gitrepo.go, e2e/testenv/kubectl/kubectl.go
The new "gitrepo update" test needs a repo which it can control. These repos were created in a new account, which is orchestrated by the test. 
The workflows need deploy keys, one per repo as each workflow uses a separate repo to avoid conflicts.
The new AKS/EKS/GKE workflows require cloud credentials. They are triggered manually, we can activate a schedule once the secrets are set. The AKS/EKS workflows are tested: (https://github.com/manno/fleet/actions/runs/2669615696, https://github.com/manno/fleet/actions/runs/2669617653). The GKE workflow needs a service account with API keys first (like in Epinio).
Required secrets:
* ci (needed before this PR  is green)
* CI_SSH_KEY
* CI_SSH_PUBKEY
* eks (run manually only)
* AWS_ACCESS_KEY_ID
* AWS_SECRET_ACCESS_KEY
* CI_EKS_SSH_KEY
* …
=> Add CI for "gitrepo updates" and AKS/EKS/GKE

.github/scripts/deploy-fleet.sh, .github/workflows/e2e-ci.yml, .github/workflows/e2e-multicluster-ci.yml, DEVELOPING.md, README.md, charts/fleet-agent/values.yaml, charts/fleet/values.yaml, cmd/fleetcontroller/main.go, docs/agent-initiated.md, docs/gitrepo-add.md, docs/multi-cluster-install.md, docs/namespaces.md, docs/quickstart.md, docs/single-cluster-install.md, docs/troubleshooting.md, docs/uninstall.md, docs/webhook.md, modules/cli/cmds/root.go, pkg/config/config.go
throughout the documentation.
To be consistent and prevent issues we also need to change the fleet-agent chart, because https://github.com/rancher/fleet/blob/master/pkg/namespace/util.go#L18-L24 generates `systemRegistrationNamespace` by search and replace.
So if someone updates their fleet standalone installation, which uses the old name fleet-system, it is necessary to pass systemNamespace and systemRegistrationNamespace with the old names:
```
helm -n fleet-system upgrade --install ...
--set systemRegistrationNamespace="fleet-clusters-system" \
...
```
Fixes #754
=> Consistenly use cattle-fleet-system as namespace

.github/ISSUE_TEMPLATE/1-bug-report.yml, .github/ISSUE_TEMPLATE/2-feature-request.yml, .github/ISSUE_TEMPLATE/config.yml
I propose to add issue templates to encourage contributors to provide information that are useful to debug.
Feel free to look on this [epinio/docs](https://github.com/epinio/docs/issues/new/choose) to see what it would look like
Signed-off-by: Olivier Vernin <olivier.vernin@suse.com>
=> Add Fleet issue template

.github/ISSUE_TEMPLATE/1-bug-report.yml, docs/troubleshooting.md
Add troubleshooting instructions to issue template from https://github.com/rancher/fleet/pull/858
Also use labels in troubleshooting docs, so it's no longer necessary to copy paste the pod name.
=> Add troubleshooting instructions to issue template

charts/fleet-crd/templates/crds.yaml, docs/gitrepo-structure.md, pkg/apis/fleet.cattle.io/v1alpha1/bundle.go, pkg/helmdeployer/deployer.go
This feature is a pass through from fleet configuration to the
Helm SDK.
Closes: #928
=> Adding atomic flag support for Helm charts

docs/gitrepo-add.md, e2e/assets/single-cluster/multiple-paths.yaml, e2e/single-cluster/single_cluster_test.go, modules/cli/apply/apply.go
Fixes https://github.com/rancher/rancher/issues/38672
Fleet 0.3.10 introduced bundle pruning. After debugging this for a while, it seems like the pruning code was too aggressive. When constructing multiple bundles from the same git repo, the loop would prune previously created bundles.
```
% cd fleet-examples
% fleet-0.3.10 apply --debug  --debug-level 9 multiple-paths single-cluster/manifests single-cluster/helm
INFO[0000] updated: fleet-local/multiple-paths-single-cluster-manifests
DEBU[0000] Bundle to be deleted since it is not found in gitrepo multiple-paths anymore fleet-local multiple-paths-single-cluster-helm
INFO[0000] created: fleet-local/multiple-paths-single-cluster-helm
DEBU[0000] Bundle to be deleted since it is not found in gitrepo multiple-paths anymore fleet-local …
```
=> Fix gitrepos with multiple paths

.github/workflows/rancher-integration.yml, e2e/gitrepo/gitrepo_test.go, e2e/gitrepo/suite_test.go, e2e/multi-cluster/multi_cluster_test.go, e2e/multi-cluster/suite_test.go, e2e/single-cluster/single_cluster_test.go, e2e/single-cluster/suite_test.go
Disk pressure error in Rancher integration test
The rancher integration tests are flaky. The event logs show disk pressure errors.
Reduce the number of agents and apply the fix from https://k3d.io/v5.0.1/faq/faq/#pods-evicted-due-to-lack-of-disk-space
=> Fix rancher integration disk pressure

.github/workflows/gke.yml
I created the google credentials using `CI_GOOGLE_CREDENTIALS`
It's a mix of using the same credential mentioned in the GA doc https://github.com/google-github-actions/auth
and prefixing CI like all the other credentials
=> Add Google credentials to Fleet gke workflow

modules/cli/apply/apply.go
To maintain compatibility with previously generated names, createName might use two checksums.
It already added a checksum, if the input exceeds 53 characters. Now, when initially cleaning up the input, we add another checksum if special chars exists.
Refers to https://github.com/rancher/fleet/pull/964
=> Add comment for bundle name creation

.github/workflows/ci.yml
The CI test is a required job for merging pull requests. If there is a change that does not trigger this CI job the PR can't be merged as it does not meet branch protection rules. There are cases where this can happen.
While it is extra computing work to run these jobs when there are no changes to the code there is additional process overhead to deal with PRs that don't meet branch protection rules and who has access to merge those.
=> Removing ignored paths for CI runs

charts/fleet/charts/gitjob/templates/deployment.yaml, charts/fleet/charts/gitjob/values.yaml, charts/fleet/templates/deployment.yaml, charts/fleet/values.yaml
Related to https://github.com/rancher/rancher/issues/37927
The purpose of this PR is to add the ability to set a priorityClassName for fleet pods in the rancher cluster.
- Create a new Kubernetes cluster.
- Helm install with the following options
` --set priorityClassName=system-cluster-critical --set gitjob.priorityClassName=system-cluster-critical`
- Describe fleet and gitjob pods using `kubectl`
- Verify that both pods have "system-cluster-critical" set as their priorityClassName in the pod spec
=> Adds priorityClassName to deployments.

.drone.yml
The previous install location was archived and it redirected to using the new location. This updates the FOSSA install to not use an archived repo.
This location also updates to a new version of the FOSSA CLI that more gracefully handles FOSSA API flakes which are known to happen.
=> Updating FOSSA CLI

Dockerfile.dapper, charts/fleet-agent/templates/deployment.yaml, charts/fleet/templates/deployment.yaml, pkg/agent/manifest.go, pkg/basic/objects.go, scripts/build
In order to use a debugger such as [Delve](https://github.com/go-delve/delve), binaries have to be compiled with debugging symbols and disabling some optimizations.
This PR makes it possible to build binaries and container images in such a way.
```shell
make
```
is expected to continue working exactly as before, therefore stripped binaries should continue to be produced, so `file bin/fleet*` should produce something like:
```
bin/fleet-linux-arm64:           ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=..., stripped
bin/fleetagent-linux-arm64:      ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=..., stripped
bin/fleetcontroller-linux-arm64: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), …
```
=> Use debugger-friendly compile settings if DEBUG is set

pkg/controllers/clusterregistrationtoken/handler.go
The clusterregistrationtoken has an expiry time. Due to an error the time was always reset to the current time. The fleet-controller had high cpu and kept reconciling the token.
=> Fix token expiry bug

.github/workflows/aks.yml, .github/workflows/e2e-ci.yml, .github/workflows/eks.yml, .github/workflows/gke.yml, e2e/assets/single-cluster/helm-oci-with-auth.yaml, e2e/single-cluster/single_cluster_test.go, pkg/bundle/resources.go, pkg/controllers/git/git.go
The credentials are provided via a Kubernetes secret specified by `gitRepo.spec.helmSecretName`.
Creating the secret is documented under `Private Helm Repo` in https://fleet.rancher.io/gitrepo-structure/.
Refers to #191
=> Add authentication support for OCI based Helm charts

charts/fleet-crd/templates/crds.yaml, pkg/apis/fleet.cattle.io/v1alpha1/target.go, pkg/controllers/clusterregistrationtoken/handler.go, pkg/controllers/manageagent/manageagent.go, pkg/secret/util.go
Refers to #948
More information in the commit messages
Tested this manually with manual and managed downstream agents. Changing the cluster resource, updates the agent with the configured repo.
Refers to https://github.com/rancher/rancher/pull/38950
=> Support cluster repo change

.github/workflows/rancher-integration.yml
The test is still too flaky: https://github.com/rancher/fleet/actions/workflows/rancher-integration.yml?query=event%3Aschedule
This will limit the test to pushes on release tags, so it won't show up in internal PRs anymore.
=> Remove Rancher Integration from PR

e2e/assets/single-cluster/helm.yaml, e2e/single-cluster/bundle_diffs_test.go, e2e/single-cluster/single_cluster_test.go, pkg/controllers/git/git.go
According to the docs labels from GitRepo resources are applied to generated bundles.
This re-uses an existing test for the expectation, so we keep resource usage low.
fixes #1006 
refers to #385
=> Apply gitrepo labels to bundles

charts/fleet-crd/templates/crds.yaml, pkg/apis/fleet.cattle.io/v1alpha1/git.go, pkg/apis/fleet.cattle.io/v1alpha1/zz_generated_deepcopy.go, pkg/controllers/git/git.go
Add another field to GitRepoRestrictions, to limit GitRepo deployments to specific targetNamespaces.
When a GitRepoRestrictions has `allowedTargetNamespaces`, all created Gitrepos in the same namespace will be evaluated against the list of allowed namespaces. The deployment will fail if cluster-wide resources are included, or the GitRepo uses a disallowed targetNamespace.
Refers to #385
=> Add allowedTargetNamespaces to GitRepoRestriction

e2e/assets/gitrepo/gitrepo.yaml, e2e/assets/multi-cluster/bundle-namespace-mapping.yaml, e2e/multi-cluster/bundle_namespace_mapping_test.go, e2e/require-secrets/gitrepo_test.go, e2e/testenv/template.go, pkg/controllers/cluster/controller.go, pkg/controllers/git/git.go
This completes checking the gitrepo's targetNamespace against an allow
list from the gitreporestriction resource.
If a restriction is present a targetNamespace must be given, so the
restriction can not be circumvented by using a namespace in the
manifests.
The tests make use of "bundle labels", `allowedTargetNamespaces`
gitreporestrictions and bundlenamespacemappings.
The PR also extracts templating of test assets into testenv package, so we can use templated yaml files in tests.
This also adds two debug messages. The message in git.go should give some context to the "DesiredState - No change" log messages, which are emitted for gitrepos every 15s.
Refers to https://github.com/rancher/fleet/issues/385
=> Enforce presence of targetNamespace if gitreporestriction is present.

modules/agent/pkg/controllers/bundledeployment/controller.go, pkg/apis/fleet.cattle.io/v1alpha1/bundle.go, pkg/helmdeployer/deployer.go, pkg/summary/summary.go
This change fixes an issue where failed bundle deployments constantly requeued. This caused some problems including:
1. The constant requeuing put considerable load on the k8s API as it constantly looks up the Helm history
2. In some situations each retry would increment the Helm release
This change captures certain errors and turns them into status updates instead of returning errors. This avoids constant requeuing.
A new condition was added to achieve this. Deployed and Monitored are automated by generated code. When DeployBundle() returns an error Deployed is set to False. Otherwise it's true. MonitorBundle() works the same for Monitored. An Installed Condition was added that is manually managed. It contains the error that is propogated from BundleDeployment to Bundle and Gitrepo. …
=> Stop re-queuing on failed deployments

pkg/controllers/controllers.go
Skip controller handler calls from lasso when they refer to a resource which was not actually updated (in terms of changes to `resourceVersion`). That happens when the underlying Informer resyncs.
This change is expected to reduce load in some scenarios due to the reduced number of handler calls. Nevertheless it carries a risk of uncovering bugs in case handlers relied on this behavior as a "self-correction" mechanism - particularly in case of missed events. With this change in, the expectation is that controllers have alternative ways of "retrying" when necessary.
This corresponds to the `CATTLE_SYNC_ONLY_CHANGED_OBJECTS` environment variable in Rancher.
No special prescription is known at this time. Virtually all fleet behavior is influenced by this setting.
Negative impacts described …
=> Sync only changed objects

charts/fleet/templates/configmap.yaml, pkg/agent/agent.go, pkg/agent/manifest.go, pkg/agent/manifest_test.go, pkg/config/config.go, pkg/controllers/manageagent/manageagent.go
If both systemDefaultRegistry and privateRepoURL are present, remove systemDefaultRegistry from the image arg before prefixing with privateRepoURL.
To be able to remove the systemDefaultRegistry, we need to store it separately in the fleet config.
Fix #948
```shell
go test ./pkg/agent/...
```
=> Cluster specific registry replaces global registry

pkg/controllers/bundle/controller.go, pkg/controllers/display/displaycontrollers.go
It builds on #1036 capturing a bit more information on bundle changes to aid future debugging.
Tested manually on  `master`.
=> bundle controllers: improve debug logging

.github/scripts/deploy-fleet-latest-release.sh, .github/scripts/deploy-fleet.sh, .github/scripts/dump-failed-k3ds.sh, .github/workflows/e2e-ci.yml, .github/workflows/e2e-multicluster-ci.yml, .github/workflows/fleet-upgrade.yml, .github/workflows/rancher-integration.yml, dev/remove-fleet, dev/setup-k3ds, e2e/assets/simple/gitrepo.yaml, e2e/installation/suite_test.go, e2e/installation/verify_test.go, e2e/testenv/kubectl/kubectl.go, modules/agent/pkg/agent/app.go, modules/agent/pkg/register/register.go, pkg/agent/agent.go, pkg/agent/manifest.go, pkg/basic/objects.go, pkg/controllers/bootstrap/bootstrap.go, pkg/controllers/cluster/import.go, pkg/controllers/clusterregistration/controller.go, pkg/controllers/clusterregistrationtoken/handler.go, pkg/controllers/controllers.go, pkg/controllers/data.go
Fixes an issue, by moving the two roles onto specific service accounts.
RBAC previously allowed any user to get contents and any secrets in
the system registration namespace.
However, their names are random and listing was not allowed.
The agents on downstream clusters already use the`request-` account to
retrieve bundledeployments from the upstream cluster and report back the
status. We extend that account to be able to retrieve 'contents', too.
The agents use a `import-` account for reqstration, e.g. to create a
ClusterRegistration. That one is extended, so it can read the secrets in
the agent's cluster registration namespace.
I previously observed issues when updating the agent, but can no longer reproduce these, e.g. the agent log would show
`level=error msg="Failed to register agent: …
=> Reading contents&secrets uses specific service account

e2e/assets/multi-cluster/helm-target-customizations.yaml, e2e/multi-cluster/multi_cluster_test.go, pkg/bundle/read.go, pkg/bundle/resources.go, pkg/options/calculate.go
Fix #699
Fix #899
This commit fixes an issue stopping versions and repos in Helm specs from being overridden in target customizations. It applies root repos and versions to customizations where appropriate to allow targets to  properly resolve the correct target.
To test this pull request, I used the following configurations:
[https://raw.githubusercontent.com/romejoe/fleet-test/main/multi-chart-test/fleet.yaml](https://raw.githubusercontent.com/romejoe/fleet-test/main/multi-chart-test/fleet.yaml)
[https://raw.githubusercontent.com/romejoe/fleet-test/main/version-test/fleet-config/fleet.yaml](https://raw.githubusercontent.com/romejoe/fleet-test/main/version-test/fleet-config/fleet.yaml)
The first test verifies that if the entire helm reference(repo, chart and version) are specified in a …
=> Helm Target Customization Repo/Version Override

pkg/agent/agent.go, pkg/config/config.go, pkg/controllers/cluster/import.go, pkg/controllers/manageagent/manageagent.go
Fixes #1057 
A typo in a configuration parameter name prevented it from being correctly applied. rancher/rancher seems not to be affected (a grep search only surfaces the correct parameter name), so this might only affect standalone installations.
See reproduction steps in https://github.com/rancher/fleet/issues/1057
I tested this manually.
Keeping the old name around and use it if defined. From my understanding nobody really used it so far.
None.
=> Bugfix: do not ignore agentCheckinInterval

pkg/target/mapping.go, pkg/target/target.go
Potentially fixes or helps with:
- #606
- https://jira.suse.com/browse/SURE-4967
- https://jira.suse.com/browse/SURE-3613
- https://jira.suse.com/browse/SURE-3597
Fix for a handler triggered every 15' resulted and taking `O(n²)` CPU time, where `n` is the number of clusters.
In my test setup with 2000 clusters it results in a **~16x speedup** (22 seconds down from 6 minutes).
A user experienced constant CPU load on fleetcontroller, and shared the CPU pprof profile. Flame graph looked like the following:
Observations:
- the first small flame is GC work
- the second big flame has two smaller flames:
- one is about [bundle controller's OnBundleChange](https://github.com/rancher/fleet/blob/e2e4b564690287708870084781177dfcd91a78dc/pkg/controllers/bundle/controller.go#L171) (this can deduced …
=> Scaling: avoid needlessly looking up agent bundle deployments

.github/workflows/aks.yml, .github/workflows/e2e-ci.yml, .github/workflows/eks.yml, .github/workflows/gke.yml, .github/workflows/nightly.yml, package/Dockerfile, package/Dockerfile.agent
fixes #1072
Images are pushed to ghcr.io, helm charts are attached to the Github Actions run.
It was not possible to use goreleaser, since "nightly" builds are a "pro" feature.
=> Add nightly builds

pkg/controllers/bundle/controller.go, pkg/controllers/display/displaycontrollers.go
Potentially fixes or helps with:
- #606
- #721
- https://jira.suse.com/browse/SURE-4967
- https://jira.suse.com/browse/SURE-3613
- https://jira.suse.com/browse/SURE-3597
Every time a bundle changes:
- the `bundle/controller.go`'s `OnBundleChange` handler fires
- the handler code changes the bundle's `Status`
- that, in turn, fires `displaycontrollers.go`'s `OnBundleChange` handler
Both of those handler return objects that are applied via wrangler's `apply` facility, which can be heavy on the CPU.
In a user's large setup case, `apply` is fired ~24 times/s and takes up the majority of CPU time (in purple below):
This PR folds the two handlers together, thereby reducing the number of `apply` calls by 50%.
This PR should be seen as an internal-only refactoring, no user-visible behavior should …
=> Scaling: fold bundle display controller handler into main bundle controller

pkg/controllers/cluster/controller.go
Extends #1071 slightly to allow generic duration strings (with any of the standard Kubernetes units of measure).
=> Fixup: allow FLEET_CLUSTER_ENQUEUE_DELAY to be specified as a duration

e2e/assets/multi-cluster/helm-target-customizations.yaml, e2e/multi-cluster/multi_cluster_test.go
this is a small app which seems not to delete old versions so hopefully it should be stable for the foreseeable future.
The alternative would be to create our own app versions on GitHub and use them but this would be almost the same as our OCI test.
=> Fix external helm chart targetCustomization test

.github/scripts/deploy-fleet-latest-release.sh, .github/scripts/deploy-fleet.sh, .github/scripts/setup-latest-rancher.sh, .github/scripts/upgrade-rancher-fleet-to-dev-fleet.sh, dev/setup-fleet
The local agent is rolled out twice, previously our CI would sometimes flake if it tried to wait for the rollout.
```
Waiting for deployment "fleet-agent" rollout to finish: 0 out of 1 new replicas have been updated...
Waiting for deployment "fleet-agent" rollout to finish: 0 of 1 updated replicas are available...
error: object has been deleted
```
Fleet re-deployed the deployment. This might be an issue in fleet in general, but most likely this is due to fleet's registration for the local cluster. It will create the deployment (import cluster) and then later the bundle for that deployment (manageagent), thus "adopting" the deployment.
We can wait for the bundle to be ready, instead of waiting for namespaces, deployments and helm charts.
```
% kubectl get bundles -Aw
fleet-local …
```
=> Fix waiting on agent in CI setup

pkg/target/target.go
because if only one cluster misses the label the whole bundle deployments fails.
Fix #689
Deployments on some clusters might fail if the label is not available.
=> Do not fail on missing labels

DEVELOPING.md, charts/fleet/templates/deployment.yaml, charts/fleet/values.yaml, cmd/fleetcontroller/main.go, pkg/durations/durations.go
This PR adds Helm chart values to configure continuous [pprof](https://pkg.go.dev/runtime/pprof#hdr-Profiling_a_Go_program) CPU profiling on fleetcontroller.
Since CPU pprof profiling requires a writer to stream data to, this PR creates an optional volume and environment variables to configure it.
To test this pull request:
- install Fleet with the following extra Helm values:
```yaml
cpuPprof:
period: "60s"
volumeConfiguration:
hostPath:
path: /tmp/pprof
type: DirectoryOrCreate
```
Alternatively, use the following Helm commandline arguments:
```
--set cpuPprof.period=60s \
--set cpuPprof.volumeConfiguration.hostPath.path=/tmp/pprof \
--set cpuPprof.volumeConfiguration.hostPath.type=DirectoryOrCreate \
```
- make sure that `/tmp/pprof` is writable
- start Fleet
- after some minutes, check …
=> Add support to continuous pprof CPU profiling

pkg/target/target.go
This change was preventing Fleet triggering on GitJob changes shown by our "updating a git repository" test.
This reverts commit 866a6159256064aca810c7f3e6fa3fd2e073c37a.
=> Revert "Refactoring: avoid needless DeepCopy, the object is not mutated"

.gitignore, cmd/docs/generate-cli-docs.go, cmd/fleetagent/main.go, cmd/fleetcontroller/main.go, go.mod, go.sum, modules/agent/cmds/root.go, modules/controller/cmds/root.go
Copied from Epinio.
Importing 'main' as a package is not possible, so extracting the cobra command generation into separate packages, like 'fleet cli' already did.
refers to #1102
=> Add CLI to generate reference docs

go.mod, go.sum
Main motivation is to get https://github.com/rancher/wrangler/pull/232, which I had tested locally extensively over the past several weeks.
Additional unrelated changes brought in are:
- https://github.com/rancher/wrangler/pull/212 (documentation only)
- https://github.com/rancher/wrangler/pull/207 (dependabot)
- https://github.com/rancher/wrangler/pull/220 (documentation only)
- https://github.com/rancher/wrangler/pull/226 (formerly private fields/methods now made public)
- https://github.com/rancher/wrangler/pull/240 (improve behavior on SIGTERM, helps with https://github.com/rancher/fleet/issues/1096)
Therefore my understanding is that the bump should be a relatively safe one.
=> Bump wrangler version

charts/fleet/templates/deployment.yaml
This PR leverages [a recent wrangler change](https://github.com/rancher/wrangler/pull/240) to allow breakpoint-setting with debuggers such as Delve.
When stopping on a breakpoint, we want leader election to last longer and not kill the process, which was the previous behavior.
Requires: #1136
=> Allow to run longer before killing leader during debugging

.gitignore, charts/fleet-crd/templates/crds.yaml, go.mod, go.sum, pkg/apis/fleet.cattle.io/v1alpha1/bundle.go, pkg/apis/fleet.cattle.io/v1alpha1/target.go, pkg/apis/fleet.cattle.io/v1alpha1/zz_generated_deepcopy.go, pkg/options/calculate.go, pkg/target/target.go, pkg/target/target_test.go
This PR introduces the ability for fleet.yaml's `helm.values` object to contain go template strings in either the keys or values. The context of the go template also includes the cluster labels (for convenient migration from the existing `global.fleet.clusterLabels.FOO` users.
Cluster specific template variables can be added to `Cluster` CR under a new optional key in `spec.templateContext`
Related issues/PRs
- rancher/fleet#507 but adds the per-cluster custom template context
- rancher/fleet#375 
- rancher/fleet#355
=> Sprig Templating for Helm Values with Inputs from Cluster Resource

pkg/options/calculate.go, pkg/target/target.go, pkg/target/target_test.go
Let's merge this after https://github.com/rancher/fleet/pull/671 is in.
* adds recursion depth check to cluster label replacement
* rename "next" to "custom", because it is the value from  the current "targetCustomization"
* extract cluster label replacement string "global.fleet.clusterLabels." into a constant to make it more visible
=> Limit recursion depth for cluster label replacement in values

charts/fleet/templates/deployment.yaml, charts/fleet/values.yaml, pkg/agent/manifest.go
This adds a Helm configuration parameter to selectively debug the fleet controller (without fleet agents).
This contrasts with the current behavior which is to always set the same debug level on both.
Especially in large-scale scenarios, it is undesirable to have all agents restart when temporarily debugging the controller.
Install with the following Helm options:
```
--set debug=true --set propagateDebugSettingsToAgents=false
```
Or the equivalent `values.yaml` variables.
- Check that debug logging is enabled on the fleet-controller deployment (there should be a `--debug` line)
- Check that debug logging is *not* enabled on the fleet-agent deployment (there should *not* be a `--debug` line)
=> Introduce parameter to debug controller but not agents

README.md
It appears that automation introduced in https://github.com/rancher/fleet/pull/1182 broken the CRD url
=> Fix CRD download url

modules/agent/pkg/controllers/bundledeployment/controller.go
The fields are ignored in the JSON struct, however it would still
trigger a status update, which would trigger another MonitorBundle call.
The reason behind that is, that the structs are different, even though
the marshalled JSON is not.
Fixes #1174
=> [0.4] Backport Remove ignored fileds from status struct, to avoid loop

integrationtests/agent/bundle_deployment_status_test.go, modules/agent/pkg/deployer/monitor.go, pkg/helmdeployer/deployer.go
It is possible that some operators copy the `objectset.rio.cattle.io/hash` label into a dynamically created objects. Wrangler plan will look for all resources with that label, and will think they all belong to the release. However they should not be considered part of the release. We need to skip these resources because they are not part of the release, and they would appear as orphaned.
For that, we look into the previous release to see if the resource we have to delete was already present. If it was not present it means it will not be deleted, and should not be part of the release so we just skip it.
This [test](https://github.com/rancher/fleet/commit/65961b344ef6d72e052eb28a3807b1964acd79a2#diff-5d4640ccdcecacd353830fb273e4be6e72f5c1a645e8bebc35f8117c87eb5fbcR143-R164) simulates the …
=> Fix orphan resources created by operators

e2e/require-secrets/gitrepo_test.go, e2e/require-secrets/imagescan_test.go, e2e/require-secrets/suite_test.go, e2e/testenv/githelper/git.go
E2E tests were flaky, because tests were modifying env vars.
E.g. the gitrepo test suddenly tried to push to the imagescan branch:
https://github.com/rancher/fleet/actions/runs/3755744686/jobs/6381089656
=> Fix gitrepo e2e tests

pkg/config/config.go, pkg/controllers/cluster/import.go
`CattleNamespaceMigrated` `Cluster` status field is true in Rancher v2.5.16 and fleet 3.9 even though it is still using the old namespace `fleet-system`. That's a problem when migrating to the new namespace `cattle-fleet-system` as downstream clusters thinks migration already happened, and registration was already done because [agentDeployed](https://github.com/rancher/fleet/blob/v0.5.1/pkg/controllers/cluster/import.go#L170) returns true. Because of that, it's missing the `fleet-agent` secret that contains the `kubeconfig` in the `cattle-fleet-system` namespace in the downstream cluster. Therefore, new downstream `fleet-agents` can't connect to the upstream cluster.
Old agent is not removed in downstream clusters because `cluster.Spec.AgentNamespace` is always empty …
=> Fix Rancher upgrade

e2e/single-cluster/release_names_test.go, modules/agent/pkg/register/register.go, modules/cli/apply/apply.go, pkg/agent/agent.go, pkg/controllers/manageagent/manageagent.go, pkg/helmdeployer/deployer.go
Fix #1272
Long release names are shortened and a md5 hash is appended. The
existing code would shorten a release name twice. Once when creating the
bundle name and again when creating the helm release name.
This happened because name.Limit(str, 53) shortens any string smaller
than 53 chars to 53 chars. It will modify a string of 53 chars, so it's
not stable when calling it multiple times.
When the release name is different from the bundle name, fleet will
clean up such a release as it no longer belongs to a bundle.
=> Long release names, shorten only once

pkg/config/config.go, pkg/controllers/cluster/import.go
CattleNamespaceMigrated Cluster status field is true in Rancher v2.5.16 even though it is still using the old namespace fleet-system. That's a problem when migrating to the new namespace cattle-fleet-system as downstream clusters thinks migration already happened, and registration was already done. That is not true, and it's missing the fleet-agent secret that contains the kubeconfig in the downstream cluster. Therefore, new downstream fleet-agents can't connect to the upstream cluster.
Old agent is not removed in downstream clusters because cluster.Spec.AgentNamespace is always empty. cluster.Spec.AgentNamespace just changes for the local fleet agent as it is passed as a bootstrap config when installing it in Rancher.
Set CattleNamespaceMigrated to false if the agent status namespace is …
=> [v0.5] Fix Rancher upgrade

modules/cli/apply/apply.go, pkg/apis/fleet.cattle.io/v1alpha1/bundle.go, pkg/crd/crds.go, pkg/helmdeployer/deployer.go, pkg/name/name.go, pkg/name/name_test.go, pkg/name/suite_test.go
Refers to https://github.com/rancher/rancher/issues/40710
The cluster resource name is used when creating the bundle resource, however the helm release name is not shortened to 53 chars.
Enforcement of proper release name lengths was introduced with https://github.com/rancher/fleet/pull/964 to avoid reoccurring deletion of bundles. Later the fix was removed from the helmdeployer https://github.com/rancher/fleet/issues/1272 because `fleet apply` would produce valid bundles. However, the `fleet-agent` code does not use `fleet apply` and was no longer protected.
This PR keeps the bundle name intact and specifies the helm release name only.
We also switch away from wrangler's name package and use a "stable" limiter that [doesn't modify a string if its length is less or …
=> Ensure fleet-agent's helm release name has valid length

dev/delve-debug, pkg/controllers/cluster/import.go, pkg/controllers/manageagent/manageagent.go, pkg/name/name.go
Adding the token prefix to the cluster name could exceed 63 characters and the ClusterRegistrationToken would not have been created. The error was silently dropped.
Refers to https://github.com/rancher/rancher/issues/40710
=> Ensure ClusterRegistrationToken name is below 63 characters

.github/workflows/nightly.yml
With special tags for customer builds and release branches, it's hard to find the "latest official (pre-)release".
=> Change version number for nightly releases

.github/workflows/e2e-ci.yml, charts/fleet-crd/templates/crds.yaml, e2e/assets/keep-resources/do-not-keep/gitrepo.yaml, e2e/assets/keep-resources/keep/gitrepo.yaml, e2e/keep-resources/keep_resources_test.go, e2e/keep-resources/suite_test.go, integrationtests/cli/apply/apply_test.go, integrationtests/cli/assets/keep_resources/fleet.yaml, integrationtests/cli/assets/keep_resources/svc.yaml, modules/cli/apply/apply.go, modules/cli/cmds/apply.go, pkg/apis/fleet.cattle.io/v1alpha1/bundle.go, pkg/apis/fleet.cattle.io/v1alpha1/git.go, pkg/bundlereader/read.go, pkg/controllers/git/git.go, pkg/helmdeployer/deployer.go, pkg/options/calculate.go
This PR adds a new field `keepResources` to the `GitRepo` and `Bundle` CRDs. It also adds the `keep-resources` flag to the fleet cli.  `keepResources`  can also be specified in the `fleet.yaml`
When a `GitRepo` has the `keepResources` field set to true it sets the `keep-resources` flag to true when executing fleet apply in the job. Then `keepResources` is true in the generated `Bundles` and `BundleDeployments`.
The chart annotation `fleet.cattle.io/keep-resources` is set to true if `keepResources` is true when installing the helm chart. This is done because when a `BundleDeployment` is deleted it is nil in the [cleanup](https://github.com/rancher/fleet/blob/master/modules/agent/pkg/controllers/bundledeployment/controller.go#L87), so we can use this annotation to know if resources should …
=> Allow resources to be kept when deleting a GitRepo or a Bundle

dev/setup-fleet, dev/setup-fleet-managed-downstream, dev/setup-k3ds
Add scripts to test the [manager initiated registration style](https://fleet.rancher.io/manager-initiated) in development.
Possible breaking changes for devs:
* moves k3d clusters into "fleet" docker network
* `setup-fleet` tries to determine `apiServerURL` and `apiServerCA`  (should only matter if using the new `dev/setup-fleet-managed-downstream` script, though)
=> Setup a managed cluster for dev

pkg/controllers/git/git.go
Removes the boolean parameter from the function.
Comment on regex matching verbatim and log message for compilation error.
This improves on https://github.com/rancher/fleet/pull/1379  to handle gitrepo regex restrictions better.
=> Log regex compilation error in git repo restriction with patterns

pkg/helmdeployer/deployer.go
`keepResources` was not set if `releaseName` was empty. This was deleting resources when changing a cluster to a different workspace.
This PR always sets `keepResources` regardless of the `releaseName`  value
We call delete without `releaseName` [here](https://github.com/rancher/fleet/blob/master/modules/agent/pkg/deployer/manager.go#L96), which is called when a `BundleDeployment` is deleted [here](https://github.com/rancher/fleet/blob/master/modules/agent/pkg/controllers/bundledeployment/controller.go#L95). We don't have the release name because the `BundleDeployment` is nil, so we retreive it from the deployment list.
However, when the orphan Bundle[ is called](https://github.com/rancher/fleet/blob/master/modules/agent/pkg/deployer/manager.go#L72) we do have the releaseName, so we pass …
=> fix: keepResources not set properly if releaseName is empty

modules/agent/pkg/agent/app.go, modules/agent/pkg/controllers/controllers.go
`NoLeaderElect` flag was introduced with the simulator. Simulator code was recently removed in https://github.com/rancher/fleet/pull/1206, so this flag is not used anymore.
=> Remove flag to disable leaderElection

e2e/assets/multi-cluster/bundle-namespace-mapping.yaml, e2e/multi-cluster/bundle_namespace_mapping_test.go, e2e/testenv/env.go, pkg/apis/fleet.cattle.io/v1alpha1/bundle.go, pkg/apis/fleet.cattle.io/v1alpha1/target.go, pkg/crd/crds.go, pkg/target/target.go
Adds test for https://github.com/rancher/fleet/pull/1401 and cherry picks the fix.
> We noticed that the custom resource ignores the configured bundle selector. If you create a BundleNamespaceMapping all bundles in this namespace will be mapped to the downstream clusters.
> We already tested this change with our custom build which you can reach here: johnjcool/fleet:0.6.0-rc.5.7
refers to issue #1427
=> Fix BundleNamespaceMapping ignoring bundle selector

integrationtests/agent/suite_test.go, integrationtests/controller/bundle/bundle_labels_test.go, integrationtests/controller/bundle/suite_test.go, integrationtests/utils/utils.go, pkg/controllers/bundle/controller.go, pkg/target/target.go
When a label is modified in the `fleet.yaml` is also modified in the `Bundle`, but no in the `BundleDeployment`
`BundleDeployment` labels are not being updated when changed in the `fleet.yaml`. This is because we just get the labels from the `Bundle` the first time the `BundleDeployment` is created, this is done in the [resetDeployment method](https://github.com/rancher/fleet/blob/c7b02620e82b16afdca91bc466b527fa7c6232aa/pkg/target/target.go#L433). 
This PR always get the labels from the `Bundle` when creating a `BundleDeployment`
BundleDeployment patch was failing in the integration tests because wrangler was using `application/strategic-merge-patch+json` strategy for the patch. Then I was getting the error:
```
time="2023-03-24T17:04:02+01:00" level=error msg="error syncing …
```
=> Always get labels from Bundle when creating a BundleDeployment

integrationtests/controller/bundle/bundle_labels_test.go, integrationtests/controller/bundle/bundle_targets_test.go, integrationtests/controller/bundle/suite_test.go, integrationtests/controller/bundle/utils.go, pkg/bundlematcher/match.go, pkg/controllers/git/git.go, pkg/target/target.go
There are two types of Targets:
- `Targets` defined in a `GitRepo`. These targets are used to create `BundleDeployments`, and are duplicated into `TargetRestrictions`
- `TargetCustomizations` defined in `fleet.yaml`. There are used just for customization
This PR fixes two issues:
- Check if there is any `TargetCustomization` that should be applied, and it is not in the `TargetRestrictions`. Before we were matching target just if they were inside `TargetRestrictions`. This was causing some customizations to be ignored
- We were iteration a map [here](https://github.com/rancher/fleet/blob/v0.6.0/pkg/bundlematcher/match.go#L32) which order might be different in different executions. This was causing [this issue](https://github.com/rancher/fleet/issues/1254#issuecomment-1490433878). This PR …
=> Fix targeting issues

charts/fleet-crd/templates/crds.yaml, pkg/crd/crds.go
Set the maximum agent config `TolerationSeconds` to one day. 
Validate `matchLabels` and `matchExpresions` operator values to match one of the allowed values. A list with all the fields can be found [here](https://github.com/rancher/fleet/issues/1445#issuecomment-1521795460)
refers to https://github.com/rancher/fleet/issues/1445
=> Add Cluster CRD validation

pkg/agent/manifest.go
Fix #993
Makes it impossible to schedule agents on windows nodes, which is not supported.
=> Agent only selects windows nodes

.github/workflows/aks.yml, .github/workflows/eks.yml, .github/workflows/gke.yml
Fix #1499 
Update workflows to use environment file instead of deprecated `set-output` command. 
I found the workflow files that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
echo '::set-output name=ID::'$id
```
```yml
run: echo "::set-output name=uuid::$(uuidgen)"
```
**TO-BE**
```yml
echo "ID=$id" >> $GITHUB_OUTPUT
```
```yml
run: echo "uuid=$(uuidgen)" >> $GITHUB_OUTPUT
```
N/A
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
=> Replace deprecated command with environment file

.github/scripts/upgrade-rancher-fleet-to-dev-fleet.sh, .github/workflows/rancher-upgrade-fleet.yml, dev/update-fleet-in-rancher-k3d
Do not use parameter `--reuse-values` during Fleet upgrades with helm to prevent Gitjob from being updated because its image version reference is stored in the values.
`--reuse-values:  when upgrading, reuse the last release's values and merge in any overrides from the command line via --set and -f. If '--reset-values' is specified, this is ignored`
In general we should consider to move the version information from the value store to the templates.
Github Action Upgrade results:
* [Upgrade Fleet in Rancher to Latest Release](https://github.com/rancher/fleet/actions/runs/4979385018)
* [Upgrade Fleet in Rancher To HEAD](https://github.com/rancher/fleet/actions/runs/4979385765/jobs/8910908099)
* [Upgrade Fleet Standalone to HEAD](https://github.com/rancher/fleet/actions/runs/4979387138/jobs/8 …
=> Fix Upgrade CI

charts/fleet-crd/templates/crds.yaml, integrationtests/cli/apply/apply_test.go, integrationtests/cli/apply/suite_test.go, integrationtests/cli/assets/helm_chart_url/fleet.yaml, integrationtests/cli/assets/helm_path_credentials/fleet.yaml, integrationtests/cli/assets/helm_path_credentials/subfolder/fleet.yaml, integrationtests/cli/helm/helm_test.go, integrationtests/cli/helm/repository.go, integrationtests/cli/helm/suite_test.go, modules/cli/apply/apply.go, modules/cli/cmds/apply.go, modules/cli/cmds/apply_test.go, pkg/apis/fleet.cattle.io/v1alpha1/git.go, pkg/bundlereader/resources.go, pkg/controllers/git/git.go
This PR adds a new field `HelmSecretNameForPaths` to the `GitRepo`. Fleet will look for a secret that contains credentials for helm repositories for specific paths. These credentials will be used when fetching from the helm repositories in the relevant paths. `HelmSecretName` will be ignored if `HelmSecretNameForPaths` is provided.
Example of a file used to create the `HelmSecretNameForPaths` secret:
```yaml
helm-test: # path helm-test must exist in the repository
username: user
password: pass
helm-test-two:  # path helm-test-two must exist in the repository
username: user2
password: pass2
caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCiAgICBNSUlEblRDQ0FvV2dBd0lCQWdJVUNwMHB2SVJTb2c0eHJKN2Q1SUI2ME1ka0k1WXdEUVlKS29aSWh2Y05BUUVMCiAgICBCUUF3WGpFTE1Ba0dBMVVFQmhNQ1FWVXhFekFSQmdOVkJBZ01DbE52YldVd …
```
=> Allow helm credentials to be defined for each path

pkg/agent/agent.go, pkg/controllers/bootstrap/bootstrap.go, pkg/controllers/cluster/import.go, pkg/helmdeployer/deployer.go
* use the existing constant for "fleet-agent-bootstrap"
* remove io.Writer from AgentWithConfig, return objs instead
* move GetHostFromConfig/GetHostFromConfig into bootstrap package, the
only consumer, and make them private
* rename agentToken to agentBootstrapSecret and only create the secret
* move buildSecret closer to usage
=> Refactorings registration

charts/fleet-crd/templates/crds.yaml, pkg/apis/fleet.cattle.io/v1alpha1/target.go, pkg/controllers/cluster/import.go, pkg/controllers/manageagent/manageagent.go
This fixes two issues with recovering from an unsuccessful agent deployment. 
We taint the nodes on a downstream cluster `kubectl taint nodes k3d-downstream-server-0 key1=value1:NoSchedule`.
After `dev/setup-fleet`, we try to register the downstream cluster with `dev/setup-fleet-managed-downstream`. 
The deployment is created on the downstream cluster, but cannot start since all nodes are tainted.
We update the cluster resource so it tolerates the taint:
```
agentTolerations:
- effect: NoSchedule
key: key1
operator: Equal
value: value1
- effect: NoSchedule
key: key1
operator: Exists
```
Result: The deployment is not updated with the taint. The bundle is updated, but the fleet-agent is not running and can't update itself. 
This happens when starting Rancher with `--no-cacerts` and updating …
=> Agent registration recovery

.github/workflows/rancher-upgrade-fleet.yml
because the test was not reliable enough and is partly covered by other upgrade tests.
=> Remove schedule run for "Upgrade Fleet in Rancher to Latest Release CI"

charts/fleet-crd/templates/crds.yaml, integrationtests/cli/apply/apply_test.go, integrationtests/cli/apply/suite_test.go, integrationtests/cli/apply/target_test.go, integrationtests/cli/assets/targets/override/fleet.yaml, integrationtests/cli/assets/targets/simple/fleet.yaml, integrationtests/cli/helpers.go, integrationtests/controller/bundle/bundle_targets_test.go, pkg/apis/fleet.cattle.io/v1alpha1/bundle.go, pkg/bundlereader/read.go, pkg/target/target.go
`BundleDeployments` will not be created for targets that matches a `targetCustomization` that has `DoNotDeploy` set to true, which means no resources will be deployed. If a `targetCustomization` match has `DoNotDeploy` set to true we skip this `BundleDeployment` creation [here](https://github.com/raulcabello/fleet/blob/4e36ea8f82b6bf9b2a805a169850bb234f55183f/pkg/target/target.go#L279-L282). `targetCustomization`  are defined in the `fleet.yaml`.
In the following example:
```yaml
targetCustomizations:
- name: test
doNotDeploy: true
clusterSelector:
matchLabels:
env: test
```
Resources will not be deployed for `Clusters` that contains the `env: test` label.
Targets defined in a `GitRepo` will be overridden if a `Bundle` defines `overrideTargets` in the `fleet.yaml`. 
Fleet controller …
=> Add DoNotDeploy and OverrideTargets

.drone.yml
That package was missing and led to the pipeline failing.
See [this example](https://drone-publish.rancher.io/rancher/fleet/1863/1/3).
=> Install `tar` in linux-amd64/fossa Drone CI pipeline

scripts/package-helm
and not the Gitjob version constraint.
https://github.com/rancher/fleet/blob/master/charts/fleet/Chart.yaml#L16
This fixes the Gitjob version constraint in our future helm-chart release tarballs.
e.g. https://github.com/rancher/fleet/releases/download/v0.7.0/fleet-0.7.0.tgz
=> Only replace the Chart version during release

e2e/require-secrets/gitrepo_test.go, e2e/require-secrets/oci_auth_test.go
After merging #1613 , I noticed that end-to-end tests requiring secrets were:
* [failing](https://github.com/rancher/fleet/actions/runs/5375871548/jobs/9752249661) because of templating issues caused by recent additions to the `single-cluster` test suite
* ~no longer triggered automatically~ → they are scheduled to run [nightly](https://github.com/rancher/fleet/actions/workflows/nightly-ci.yml).
Not sure if there is any other option to test this than merging it...
=> Fix e2e tests requiring secrets

.github/workflows/aks.yml, .github/workflows/e2e-ci.yml, .github/workflows/e2e-multicluster-ci.yml, .github/workflows/eks.yml, .github/workflows/fleet-upgrade.yml, .github/workflows/gke.yml, .github/workflows/nightly-ci.yml, .github/workflows/rancher-integration.yml, .github/workflows/rancher-upgrade-fleet.yml
This will eliminate warnings about version mismatches, since Fleet tests now make use of a more recent, frequently updated version of Ginkgo.
Checks passing on this PR without warnings about Ginkgo version mismatches should validate it.
When Ginkgo releases versions beyond v2, package URLs should change to be suffixed with eg. `/v3/ginkgo` instead of the current `/v2/ginkgo`.
=> Unpin ginkgo version installed in CI

pkg/helmdeployer/deployer.go
Helps with #1465/[SURE-6125](https://jira.suse.com/browse/SURE-6125)
This patch reduces the number of Helm history entries per deployment from 10 or 5 (defaults were not consistent) down to 2.
Rationale:
1. retrieving the Helm history can be a costly operation in terms of downstream control plane load
1. Helm history retrieval load grows (roughly linearly) with the maximum number of entries kept
1. fleet only ever needs the present and immediately previous entries (at least according to my understanding)
1. users should not interact with Helm directly
Note: current users will see their Helm histories trimmed at first round of updates of the respective deployment bundles/releases. For a one-off cleanup, where needed, this script can be used: …
=> Rationalize Helm history

internal/bundlereader/loaddirectory.go, internal/bundlereader/loaddirectory_test.go
This provides basic support for `.fleetignore` files, in the same
fashion as .gitignore, so that specific files or paths can be excluded
instead of enforcing a blanket exclusion of non-YAML files.
Basic support means that the following is supported:
* Glob syntax is used to match files or directories, using Golang's
[`filepath.Match`](https://pkg.go.dev/path/filepath#Match)
* Empty lines are skipped, and can therefore be used to improve
readability
* Comments, ie lines starting with unescaped `#`, are skipped
* A given line can match a file or a directory, even if no separator
is provided (eg. `subdir/*` and `subdir` are both valid
`.fleetignore` lines)
* A match may be found for a file or directory at any level below
the directory where a `.fleetignore` lives, ie `foo.yaml` will
match …
=> Support exclusion of files and directories from bundles

internal/bundlereader/loaddirectory.go, internal/bundlereader/loaddirectory_test.go
This fixes a bug where a `.fleetignore` entry in a parent directory would be ignored in a subdirectory which had its own `.fleetignore` file.
Refers to #583
```shell
go test ./internal/bundlereader
```
=> Fix `.fleetignore` entry propagation to subdirectories

internal/name/name.go, internal/name/name_test.go
A Helm release name is generated for each bundle deployed by Fleet. In case that name is longer than 53 characters, the maximum length of Helm release names, it is then truncated to 46 characters and the remaining characters are a dash followed by a hash.
This fixes an edge case where the truncated release name already ends with a dash, leading to the final release name (in the form `<truncated>-<hash>`) containing a double dash. Since this caused discrepancies between deployed release names and what the Fleet agent would expect to be deployed, Fleet would frequently delete and re-create bundles as a result.
Refers to #1511
```shell
go test ./internal/name/...
```
=> Fix Helm release name generation to prevent double dashes

.github/workflows/nightly-ci.yml
This prevents nightly CI workflows from [failing](https://github.com/weyfonk/fleet/actions/runs/5516888584/jobs/10058792635) due to not finding the Dockerfile for the test git server.
=> Provide path to relevant directory when building git server image for nightly CI workflow

internal/name/name.go, internal/name/name_test.go
When a release name must be truncated to comply with Helm's maximum release name length, Fleet truncates the name and builds a new release name as `<name>-<hash>`.
In cases where the last character of `<name>` is a dash, a previous commit would include the character immediately following the dash and place it before the hash, which might cause confusion.
Instead, this commit does not include that character in such cases and increases the hash length by 1, so that characters after the last dash in the release name remain hexadecimal.
Refers to #1511
```shell
go test ./internal/name/...
```
=> Prevent non-hex chars in release name hash

e2e/single-cluster/gitrepo_test.go, internal/bundlereader/loaddirectory_test.go, internal/cmd/agent/deployer/monitor.go, internal/cmd/controller/target/target.go
This fixes a few (mostly formatting) errors output by the linter, although not all of them. The following are left:
```
internal/cmd/agent/deployer/internal/scheme/scheme.go:7:2: blank-imports: a blank import should be only in a main or test package, or have a comment justifying it (revive)
_ "k8s.io/kubernetes/pkg/apis/admission/install"
^
internal/cmd/controller/controllers/clusterregistration/controller.go:39:2: G101: Potential hardcoded credentials (gosec)
AgentCredentialSecretType     = "fleet.cattle.io/agent-credential"
^
internal/cmd/agent/register/register.go:266:15: G107: Potential HTTP request made with variable url (gosec)
if _, err := http.Get(apiServerURL); err == nil {
^
internal/cmd/agent/deployer/internal/normalizers/knowntypes_normalizer.go:32:79: unexported-return: …
```
=> Fix linting errors

.github/workflows/golangci-lint.yml
The CI action is failing its scheduled runs: https://github.com/rancher/fleet/actions/workflows/golangci-lint.yml
=> Bump golangci-lint to 1.53

charts/fleet-crd/templates/crds.yaml, modules/agent/pkg/register/register.go, pkg/apis/fleet.cattle.io/v1alpha1/target.go, pkg/controllers/cluster/controller.go, pkg/controllers/cluster/import.go, pkg/controllers/clusterregistration/controller.go, pkg/controllers/clusterregistrationtoken/handler.go, pkg/controllers/git/git.go, pkg/controllers/manageagent/manageagent.go, pkg/name/keyhash.go
Refers to https://github.com/rancher/fleet/issues/1656
* Delete old clusterregistrations when granting a new one
* Remember the api server for each cluster in the status
* Clean cattle.io cluster labels from registration
The labels of the existing cluster, were put into the agents config map on the downstream cluster.
Then the agent used them when creating the cluster registration resource.
If the cluster resource doesn't exist (anymore), fleet-controller would
create a new one and use these labels.
They're not needed by the downstream agent.
Example of old labels:
```
clusterLabels:
management.cattle.io/cluster-display-name: sec
management.cattle.io/cluster-name: c-m-h57lm9n4
objectset.rio.cattle.io/hash: 790691648d4c0e69c36440a3bc4f6bddc6d9109d
provider.cattle.io: k3s
```
* Add comments …
=> [v.0.7] Backport clean up clusterregistrations

pkg/name/name.go, pkg/name/name_test.go
=> [v0.7] Backport helm release name fix

internal/cmd/agent/register/register.go, internal/cmd/controller/controllers/cleanup/handler.go, internal/cmd/controller/controllers/clusterregistration/controller.go, internal/cmd/controller/secret/util.go
Refers to #1651
Previous fix would clean up cluster registrations that were still used by the agent, if the agent restarted quickly.
=> Clusteregistration less aggressive cleanup

.github/workflows/e2e-ci.yml, .github/workflows/e2e-multicluster-ci.yml, internal/cmd/controller/controllers/clusterregistration/controller_test.go
We have a couple of flakes in our CI, however the setup itself seems unstable. It's not just specific tests.
This reduces the k3d docker containers to one.
Also remove the two year old `rancher/k3s:v1.20.15-k3s1` from the matrix. 1.20 is no longer in the support matrix of Rancher manager: https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-1/
=> Remove k8s 1.20 from PR CI matrix

integrationtests/cli/cleanup/cleanup_test.go, internal/cmd/cli/cleanup.go, internal/cmd/cli/cleanup/cleanup.go
Fix notes from code review, having ms and s was confusing. Instead properly parse durations from string aruments, e.g. "10s" and make "factor" an argument, too.
Refers to https://github.com/rancher/fleet/pull/1689
=> Cleanup command takes string durations as arguments

internal/cmd/agent/controllers/bundledeployment/controller.go, internal/cmd/agent/controllers/controllers.go, internal/cmd/agent/register/register.go, internal/cmd/agent/start.go, internal/cmd/controller/controllers/data.go
Refers to https://github.com/rancher/fleet/issues/1679 (see also https://github.com/rancher/fleet/issues/1388 and https://github.com/rancher/fleet/issues/1651)
When upgrading fleet  the agent's deployment is deleted and recreated and maybe updated. 
The k8s deployment controller doesn't ensure that only one pod is running. In fact it tries to keep the old pod running, so that it can finish remaining requests, while it simultaneously starts the new pod for new requests. Even switching to a "replace" update strategy doesn't guarantee that only one pod is running.
However, when the agent pod starts up and a `fleet-bootstrap-secret` is present, it will run the cluster registration. Once the registration is finished the bootstrap secret is deleted. The cluster registration in …
=> Restrict registration to leader agent

internal/cmd/controller/agent/manifest.go, internal/cmd/controller/agent/manifest_test.go, internal/cmd/controller/controllers/cluster/import.go, internal/cmd/controller/controllers/manageagent/manageagent.go
Refers to https://github.com/rancher/fleet/issues/1679 (see also #1388 and #1651)
There is a GENERATION env var on the agent deployment, which makes the agent restart every time it is changed.
When a cluster is created, the agent is deployed via `import.go`. The value is set to correspond to the `cluster.Generation`.  
The cluster event also triggers a namespace event for `manageagent` and it will create/update  the `bundles` for all `clusters`. These bundles contain an identical agent deployment, except for the `GENERATION` env var, which is set to 'bundle'. 
As soon as the agent is registered it will update itself from the bundle and restart itself, since a change to an env var of a deployment's pod spec triggers an update.
To avoid that restart, we cannot replace "bundled" with the …
=> Do not restart agents when adopting them with a bundle

integrationtests/agent/helm_capabilities_test.go, internal/helmdeployer/capabilities.go
Some charts, like cert-manager check the helm version, since fleet uses the SDK we need to set it.
Refers to https://github.com/rancher/fleet/issues/1643
=> Add helm version to capabilities

internal/cmd/controller/agent/manifest.go, internal/cmd/controller/root.go
Fixes #1694
The variable used to populate the agent's `--debug-level` flag was being set after starting the controller, which is causing the value not to be ready by the time it's accessed.
I've also taken the chance to move the handling of the environment variable that controls this propagation to the root command.
I confirmed the issue by installing Fleet controller with debug enabled, then checking the `fleet-agent` deployment that gets automatically installed:
```
❯ kubectl -n cattle-fleet-system get deploy/fleet-agent -o=jsonpath='{.spec.template.spec.containers[0].command}'
["fleetagent","--debug","--debug-level","0"]
```
After my changes, we can see that the debug level flag matches the value used in the controller:
```
❯ kubectl -n cattle-fleet-system get deploy/fleet-agent …
```
=> Incorrect agent's DebugLevel when settings propagation is set

charts/fleet-crd/templates/crds.yaml, e2e/assets/single-cluster/helm-options-skip-schema-validation.yaml, e2e/single-cluster/helm_options_test.go, internal/helmdeployer/deployer.go, pkg/apis/fleet.cattle.io/v1alpha1/bundle.go
Fix #1430
This PR allows preventing Helm to execute the validation of `values.schema.json`, intended to validate the provided chart values.
The implementation is a workaround for helm/helm#10398, since it removes the `Schema` field after loading the `Chart` object, but should be straightforward to replace once the functionality of the mentioned issue is merged and available.
An end-to-end test have been added to exercise this functionality (see https://github.com/rancher/fleet-test-data/pull/5).
In order to manually test it, you can add the following top-level property to a `fleet.yaml`:
```yaml
helm:
skipSchemaValidation: true
```
Then it must be applied in a cluster running Fleet, where the updated version of the CRDs are installed and an updated version of the `fleet-controller` and …
=> Allow skipping Helm's schema validation through fleet.yaml

e2e/single-cluster/suite_test.go, e2e/testenv/kubectl/kubectl.go
Part of #1496
Increases logging in case of errors, or if `-v` is used. Otherwise the verbosity is unchanged.
Importing Ginkgo in `e2e/testenv` might make it more difficult to use testenv outside of the context of testing. That said, [this isn't the first occurrence of Ginko in `e2e/testenv`](https://github.com/rancher/fleet/blob/master/e2e/testenv/template.go#L44) (but the second PR to add Ginkgo as dependency to testenv).
Error occurring with `kubectl` operations are usually pretty unhelpful. With this change, it'll be evident which command failed and perhaps even why. A remote test from my fork [demonstrates the usefulness](https://github.com/p-se/fleet/actions/runs/6171821087/job/16750825094). You can compare that with other occurrences of the same issue in other PRs …
=> E2E: Increase logging

e2e/single-cluster/gitrepo_test.go
Part of https://github.com/rancher/fleet/issues/1496
Wraps harmless looking instructions into an `Eventually` because they fail occasionally.
See
* https://github.com/rancher/fleet/actions/runs/6145269754/job/16672311663#step:13:70
* https://github.com/p-se/fleet/actions/runs/6171821087/job/16750825094#step:13:98
* https://github.com/rancher/fleet/actions/runs/6166897811/job/16737086460?pr=1781#step:13:70
* https://github.com/rancher/fleet/actions/runs/6121172337/job/16711445433?pr=1765#step:13:70
=> E2E: Fix flaky single cluster tests

dev/README.md, dev/env.multi-cluster-defaults, dev/env.single-cluster-defaults, dev/k3d-act-clean, dev/setup-cluster-config, dev/setup-multi-cluster, dev/setup-single-cluster
Part of #1496
Adding scripts to not have to copy and paste instructions from `dev/README.md` with sane defaults to spin up the environment and run the tests out-of-the-box. Contains appropriate adaptations of the `dev/README.md`.
=> Add dev scripts to simplify using E2E tests

.github/scripts/k3d-import-retry.sh, .github/workflows/e2e-ci.yml, .github/workflows/e2e-multicluster-ci.yml, .github/workflows/fleet-upgrade.yml, .github/workflows/nightly-ci.yml
Refers to https://github.com/rancher/fleet/issues/1496
This is a workaround until [k3d import is fixed upstream](https://github.com/k3d-io/k3d/issues/1072).
=> Retry k3d image import in workflows

charts/fleet-crd/templates/crds.yaml, internal/cmd/controller/controllers/cluster/import.go, pkg/apis/fleet.cattle.io/v1alpha1/target.go
Fix https://github.com/rancher/fleet/issues/1787
Introduce the `.spec.kubeConfigSecretNamespace` annotation to facilitate specifying an alternate namespace for grabbing the KUBECONFIG of an imported cluster. This should only affect manager-based registration since it's only affecting the imported cluster workflow.
Listed in issue
No regression possibilities. This is an opt-in feature.
=> Add support for spec field identifying KUBECONFIG namespace for imported clusters

cmd/codegen/hack/patch_crd_descriptions.sh
Docker build output was appended to the `crds.yaml` when `yq` is not installed. 
This PR discards the output of the docker build command, so it doesn't get appended to the `crds.yaml`
=> Fix patch_crd_descriptions.sh when yq is not installed

integrationtests/agent/suite_test.go, internal/helmdeployer/deployer.go, internal/helmdeployer/helmcache/secret.go, internal/helmdeployer/helmcache/secret_test.go
Helm is internally listing all secrets each time we retrieve information about the release. We were using the helm storage secrets driver, which is meant to be used as a cli. It uses a k8s client to get/list/create.. secrets, and it doesn't use any cache (see implementation [here](https://github.com/helm/helm/blob/v3.12.3/pkg/action/lazyclient.go#L60-L125))
This PR adds a new helm storage driver that uses the `SecretCache` from wrangler for getting and listing secrets. All other operations uses a k8s client like the helm secrets driver does.  `SecretCache` from wrangler is internally using a `ShareInformer` for creating the cache.
This PR undoes the cache implemented in https://github.com/rancher/fleet/commit/8b0d9b7031570b7f6c0b8b5e969e34542339d181
The helm globalCfg is created with an …
=> Helm Storage Backend With Caching

docs/release.md
`rancher/tekton-utils` is no longer a dependency of `rancher/gitjob`.
This is a follow-up to #1504.
=> Remove Tekton references from release docs

.github/workflows/nightly-ci.yml
This should help troubleshoot failures happening in tests requiring secrets, which can therefore not be run locally nor against Fleet forks.
=> Add tmate debugging info to Nightly E2E workflow

internal/cmd/controller/controllers/git/git.go
Make sure the `gitjob` pod and the job init container runs in an unprivileged `securityContext`. The following `securityContext` has been added:
```
securityContext:
allowPrivilegeEscalation: false
readOnlyRootFilesystem: true
privileged: false
runAsNonRoot: true
seccompProfile:
type: RuntimeDefault
capabilities:
drop:
- ALL
```
`emptyDir` volume is mounted in the ` /tmp` dir in order to prevent issues when creating temporary files as `readOnlyRootFilesystem` is set to true
refers to https://github.com/rancher/fleet/issues/1845
=> Add SecurityContext to job container

.github/workflows/check-changes.yml, .github/workflows/ci.yml, .github/workflows/e2e-ci.yml, .github/workflows/e2e-multicluster-ci.yml, .github/workflows/fleet-upgrade.yml, .github/workflows/nightly-ci.yml, .github/workflows/nightly.yml, .github/workflows/rancher-integration.yml, .github/workflows/rancher-upgrade-fleet.yml
This should speed up workflow runs, while keeping cache usage to a minimum, ie for Rancher CLI binaries.
Refers to #1866
* `actions/cache@v3` use is kept for Rancher CLI binaries, eg. [here](https://github.com/rancher/fleet/blob/master/.github/workflows/rancher-integration.yml#L58).
=> Remove cache action for Go build artifacts

.drone.yml
Drone CI is pushing new DockerHub images for every tag pushed to the repository, as well as creating a GitHub release with the binaries.
This change will omit this step for debug images, which are tagged like `v<X.Y.Z>-debug-<GH_issue_ID>-<count>`, only causing the release of the images.
=> Prevent debug images from creating GitHub releases

e2e/assets/keep-resources/do-not-keep/gitrepo.yaml, e2e/assets/keep-resources/keep/gitrepo.yaml, e2e/keep-resources/keep_resources_test.go
This covers a similar use case but with a lower footprint than via a full-blown example using Redis pods.
Refers to #1866.
=> Use configmap example for `keepResources` E2E tests

.github/workflows/e2e-ci.yml, .github/workflows/nightly-ci.yml, e2e/assets/single-cluster/helm-oci.yaml, e2e/drift/suite_test.go, e2e/keep-resources/keep_resources_test.go, e2e/keep-resources/suite_test.go, e2e/single-cluster/helm_auth_test.go, e2e/single-cluster/single_cluster_test.go, e2e/testenv/infra/cmd/root.go, e2e/testenv/infra/cmd/setup.go, e2e/testenv/infra/cmd/teardown.go
Refers to #1866
This provides a few improvements to minimise the footprint of E2E tests, in the hope of reducing their flakiness when running on Github runners:
* cleans up resources created by `keep-resources` tests once done
* runs each test type (acceptance tests, E2E tests without secrets, E2E tests with secrets) on a separate Github runner
* sets up and tears down the minimal set of test infrastructure (git server, Helm registry, OCI registry) depending on each set of test cases, which are now labeled for those sets to be easier to manage
* uses a [minimal chart](https://github.com/orgs/rancher/packages/container/package/fleet-test-configmap-chart) containing only a config map, instead of a `guestbook` chart including a front-end server and a Redis instance, to test Helm chart …
=> Clean up e2e test resources

.github/workflows/golangci-lint.yml
This should eliminate typecheck errors happening in the standard library.
=> Bump golangci-lint to latest version

charts/fleet/templates/deployment.yaml, internal/cmd/controller/cleanup/content/purge.go, internal/cmd/controller/cleanup/controllers/cleanup/controller.go, internal/cmd/controller/cleanup/controllers/controllers.go, internal/cmd/controller/cleanup/root.go, internal/cmd/controller/cleanup/start.go, internal/cmd/controller/controllers/bundle/controller.go, internal/cmd/controller/controllers/controllers.go, internal/cmd/controller/root.go
Move the cleanup controller and the code that's cleaning orphan `contents`,  `bundles` and `imageScans` to a different binary.
Run the fleet-cleanup in a different container
=> Move cleanup to a different container

internal/cmd/agent/register/register_test.go
Registering a cluster with a made up API server URL, not pointing to any actual server, will fail. Whether it fails with a timeout or a `connection refused` error is not relevant; what matters in this smoke test case is that the agent does not crash (see test case description).
See [this run](https://github.com/rancher/fleet/actions/runs/6646995070/job/18061545739?pr=1901) for an example of a failure fixed by this PR.
Refers to #1866.
```shell
go test ./internal/cmd/agent/register/...
```
=> Fix flaky smoke test for cluster registration

.github/workflows/aks.yml, .github/workflows/gke.yml
Refers to #1866.
See [this AKS run](https://github.com/rancher/fleet/actions/runs/6692075203/job/18180527152) and [this GKE run](https://github.com/rancher/fleet/actions/runs/6692077842/job/18180535541).
Multi-cluster tests are still not included in those workflows because they are more complex to set up in hyperscaler environments.
=> Add acceptance tests to AKS and GKE CI workflows

e2e/single-cluster/single_cluster_test.go
Any PR against `release/0.9` fails due to this test, which was adapted as part of #1876.
=> [0.9] Backport OCI test changes

e2e/require-secrets/oci_auth_test.go
Follow-up of #1959, since this test is only run when merged, not during PRs.
Backports #1898
=> [0.9] Backport OCI auth test changes 

e2e/require-secrets/oci_auth_test.go
Backporting part of #1898
Twin PR on `release/v0.9`: #1961
=> [0.8] Backport OCI auth test changes

.github/workflows/fleet-upgrade.yml, e2e/assets/installation/bundle-diffs.yaml, e2e/single-cluster/bundle_diffs_test.go
The test was flaky, probably since both specs used the same namespace. The specs tried to work around that by waiting, but that's probably not effective.
The bundle-diffs.yaml was used in another test and was cloned, so that test doesn't have to change.
=> Switch bundle diff test to use random target namespaces

pkg/apis/fleet.cattle.io/v1alpha1/bundle_types.go
This is a follow-up to #1772
During code review we noticed several strings in the public api type package, which could be constants.
=> Change variables to constants in bundle type

charts/fleet-crd/templates/crds.yaml, internal/bundlereader/read.go, internal/cmd/agent/deployer/monitor.go, internal/cmd/cli/apply/apply.go, internal/cmd/controller/controllers/git/git.go, internal/cmd/controller/options/calculate.go, pkg/apis/fleet.cattle.io/v1alpha1/bundledeployment_types.go, pkg/apis/fleet.cattle.io/v1alpha1/gitrepo_types.go, pkg/apis/fleet.cattle.io/v1alpha1/zz_generated_deepcopy.go
This PR overrides `correctDrift` if it appears in `targetCustomizations`. This allows user to override this setting per cluster.
refers to https://github.com/rancher/fleet/issues/1794
=> Allow correctDrift to be overridden in target customization

charts/fleet/templates/deployment.yaml, charts/fleet/values.yaml
Part of #1491
It makes leader election parameters configurable via Helm chart values, and adapts the default values by applying the following reasoning:
* The purpose of leader election on Fleet is to ensure only instance is running at a time.
* `fleet-controller` deployment is configured to use only 1 replica, but users could still try to scale it up.
* Rolling updates could cause to temporarily have 2 living instances of fleet.  
* This could be mitigated by using `StatefulSet` instead of `Deployment`, although this would still not prevent users from manually scaling up the `StatefulSet` too
* The definition of `LeaseDuration` says that any candidate should wait at lease this duration before attempting to become leader, so long duration could slow down the rollout of new images.
* For …
=> Configurable leader election via chart values

charts/fleet-crd/templates/crds.yaml, internal/helmdeployer/deployer.go, internal/helmdeployer/deployer_test.go, pkg/apis/fleet.cattle.io/v1alpha1/bundledeployment_types.go
Just delete CRDs if `deleteCRDResources` is set to true in the `fleet.yaml`. Otherwise CRDs are kept in the cluster.
This PR adds the `helm.sh/resource-policy` annotation for CRDs if `deleteCRDResources` is false or not set. This will prevent helm from deleting CRDs when a `Bundle` is deleted.
Refers to https://github.com/rancher/fleet/issues/1978
=> [v0.9] Keep CRDs when deleting a Bundle

package/Dockerfile, package/Dockerfile.agent
BCI images are stable, specifying minor will allow us to pull in the latest image shortly before the actual release.
=> [v0.9] BCI base version

internal/cmd/agent/controller/bundledeployment_controller.go, internal/cmd/agent/deployer/monitor/updatestatus.go
This is a follow-up to https://github.com/rancher/fleet/pull/1772
We discussed if that re-queue is still needed. Also, why are agent resources deleted?
=> Remove bd requeue, rely on drift correction

go.mod, go.sum, internal/cmd/controller/controllers/bundle/controller.go, internal/cmd/controller/controllers/git/git.go, pkg/generated/controllers/fleet.cattle.io/v1alpha1/bundle.go, pkg/generated/controllers/fleet.cattle.io/v1alpha1/bundledeployment.go, pkg/generated/controllers/fleet.cattle.io/v1alpha1/cluster.go, pkg/generated/controllers/fleet.cattle.io/v1alpha1/clustergroup.go, pkg/generated/controllers/fleet.cattle.io/v1alpha1/clusterregistration.go, pkg/generated/controllers/fleet.cattle.io/v1alpha1/clusterregistrationtoken.go, pkg/generated/controllers/fleet.cattle.io/v1alpha1/gitrepo.go, pkg/generated/controllers/fleet.cattle.io/v1alpha1/imagescan.go
Refers to #2054
CPU improvements were merged into a new wrangler v1 version. Upgrade and also reduce the number of Apply calls from the `Bundle` and `GitRepo` handlers.
=> [v0.8] Use UniqueApplyForResourceVersion in Bundle and GitRepo GeneratingHandlers

.github/workflows/golangci-lint.yml
According to the [README](https://github.com/golangci/golangci-lint-action) we should disable the setup-go cache.
Maybe this helps with the cache errors/warnings?
=> Disable cache in golangci-lint action

.github/scripts/release-against-charts.sh, .github/scripts/release-against-rancher.sh, .github/workflows/release-against-charts.yml, .github/workflows/release-against-rancher.yml
Ideally the `.github/scripts` don't contain much configuration complexity and tailored to the CI.
However, we do execute this locally and duping it into dev seems unnecessary, when I can just remove a variable and an if condition instead.
This also allows me to use any charts dir, like `charts-2.7`.
=> Release scripts chart dir var

.github/scripts/run-integration-tests.sh, integrationtests/agent/suite_test.go, integrationtests/agent/watcher_trigger_test.go, internal/cmd/agent/trigger/watcher.go, pkg/durations/durations.go
Refers to #2058
These changes aim for reducing the number of time that the BundleDeployment reconciler is executed. This happens due to the Fleet Agent configuring a watcher on every deployed resources, which will trigger a requeue of the BundleDeployment handler in the agent for every watch event. Since this handler refreshes the conditions timestamp in the BundleDeployment status, this has a direct effect on the Fleet controller as well, which will react to the update in the BundleDeployment object.
This patch consists of the following changes:
- The `TriggerSleep` delay has been removed, since it could cause modification events happening in that time window to be missed (this was the case for the integration tests). This is connected to the next change:
- `ADDED` watch events are now …
=> [v0.9] Reduce BundleDeployment triggering on deployed resources updates

integrationtests/cli/helpers.go, internal/bundlereader/resources_test.go, internal/cmd/cli/apply.go, internal/cmd/controller/agentmanagement/agent/agent.go, internal/cmd/controller/target/target_test.go, internal/helmdeployer/install.go
Wrangler would just call
`yamlDecoder.NewYAMLToJSONDecoder(bytes.NewBuffer(data)).Decode(v)`
Wrangler `yaml` uses https://github.com/ghodss/yaml and https://github.com/kubernetes/apimachinery/blob/master/pkg/util/yaml/decoder.go. The first is old, while apimachinery wraps "sigs.k8s.io/yaml", which uses 
"sigs.k8s.io/yaml/goyaml.v2".
=> Use apimachinery yaml package directly

internal/cmd/agent/deployer/deployer.go, internal/cmd/agent/deployer/deployer_test.go
We are using the label `name` to retrieve the namespace used for the fleet deployment. The label `name` is added to all namespaces created by Fleet (and all namespaces created with helm). However, this label is missing for namespaces created in other ways (e.g. kubectl).
This PRs changes the `client.MatchingLabels` to use the `kubernetes.io/metadata.name` label instead. `kubernetes.io/metadata.name` is added to all namespaces.
Refers to https://github.com/rancher/fleet/issues/1994
=> Filter namespaces by the kubernetes.io/metadata.name label

internal/cmd/cli/test.go
Will be replaced by https://github.com/rancher/fleet/issues/2110
The `fleet test` command, `match.Matcher` in the code, seems to be mostly useless. See discussion in https://github.com/rancher/fleet/issues/1385#issuecomment-1527758555
=> Deprecate "fleet test" command, previously used to debug chart

internal/cmd/agent/operator.go, internal/helmdeployer/deployer.go
Noticed during https://github.com/rancher/fleet/issues/2110
The helmdeployer does not consider `--kubeconfig`.  We don't seem to use the flag, except in upcoming CLI tests to target the testenv cluster.
=> Fix helm deployer ignoring kubeconfig CLI arg

.github/scripts/deploy-fleet.sh, .github/workflows/aks.yml, .github/workflows/gke.yml, .github/workflows/nightly-ci.yml
This commit ensures that gitjob end-to-end tests run in all CI workflows which run end-to-end tests requiring secrets. This entails setting the gitjob-specific SSH key in all such workflows.
This fixes failures for:
- Nighly E2E Fleet ([before](https://github.com/rancher/fleet/actions/runs/7722443912/job/21050630477)/[after](https://github.com/rancher/fleet/actions/runs/7723663716/job/21054482926))
- CI GKE ([before](https://github.com/rancher/fleet/actions/runs/7719988713/job/21044174369)/[after](https://github.com/rancher/fleet/actions/runs/7724550665/job/21056923633))
- CI AKS ([before](https://github.com/rancher/fleet/actions/runs/7709609929/job/21011176521)/[after](https://github.com/rancher/fleet/actions/runs/7724557547/job/21056942936))
Refers to #2008
=> Add gitjob end-to-end tests with SSH key

package/Dockerfile.gitjob
Follow-up to #2098, refers to #2008.
[Original PR](https://github.com/rancher/gitjob/pull/421) submitted to `rancher/gitjob` by @macedogm, with the following description (verbatim):
1. Use `major:minor` version for base image`registry.suse.com/bci/bci-base:15.5` instead of `registry.suse.com/bci/bci-base:15.5.36.5.68`, which is already a month old.
~2. Patch bump of `github.com/cloudflare/circl` to `v1.3.7` to fix advisory GHSA-9763-4f94-gfch.~ → already applied to `master` via #2098, removed from this PR.
=> Update gitjob base image

package/Dockerfile.gitjob
Follow-up to #2098, refers to #2008.
[Original PR](https://github.com/rancher/gitjob/pull/422) submitted to `rancher/gitjob` by @macedogm, with the following description (verbatim):
Use the base level package `git-core` that has less dependencies than `git`, reducing image size and possibly future CVEs ("less packages normally means less CVEs").
**git**
```shell
/ # zypper in git
Refreshing service 'container-suseconnect-zypp'.
Loading repository data...
Reading installed packages...
Resolving package dependencies...
The following 12 NEW packages are going to be installed:
file git git-core less libexpat1 libgdbm4 libpcre2-8-0 libsha1detectcoll1 perl perl-Error perl-Git which
The following 12 packages are not supported by their vendor:
file git git-core less libexpat1 libgdbm4 …
```
=> Use git-core pkg instead of git

charts/fleet-agent/values.yaml
This kubectl is only used by the standalone chart.
Maybe this should be same image as the one used by Rancher to limit downloads?
=> Bump fleet-agent chart's kubectl to 1.29

package/Dockerfile, package/Dockerfile.agent
Also moving the USER statement to the bottom. Experiments show it works
in any place, but it's confusing to read. Note, the USER statement is
the default UID if no securityContext is used. However, Fleet uses a
securityContext/RunAsUser, but scanners complain when USER is missing.
This is probably because scanners don't distinguish between the docker
container runtime and the container runtime used in k8s.
=> [v0.9] Switch base images to smaller images [SURE-7269]

e2e/testenv/infra/go.mod, e2e/testenv/infra/go.sum
We have trouble updating our `go.mod`. Often, we need to update `e2e/testenv/infra/go.mod` when the main `go.mod` updates.
That's because the infra module imports the local fleet module via `replace github.com/rancher/fleet => ../../../`.
This PR imports a published go.mod instead, since the infra command only uses the testenv helpers from e2e, the dependency does not have to be updated often.
When making changes to the infra command, one might want to edit and use the helpers directly. Without the need to tag a version for every change. Go workspaces can help:
```
cd e2e/testenv/infra
go work init
go work use ../../../
go work use .
```
This is similar to a replace statement. Never commit the `go.work` file, though.
It might still be necessary split the PR into two, one for the helpers …
=> Infra e2e command uses a published fleet module

go.mod, go.sum, internal/helmdeployer/install.go
In tag `v3.14.0-fleet2`, `rancher/helm` replaces `ForceAdopt` with `TakeOwnership` to clarify the purpose of that feature.
=> Update helm fork, rename ForceAdopt/Adopt to TakeOwnership

.github/scripts/build-fleet-binaries.sh, dev/build-fleet, package/Dockerfile.gitjob, scripts/package
refers to https://github.com/rancher/fleet/issues/2151
follow up for https://github.com/rancher/fleet/pull/2152
This also adds TARGETARCH support for buildx based builders, like goreleaser
=> Build for gitjob binaries supports multiple archs

.drone.yml, .github/scripts/build-fleet-images.sh, .github/scripts/deploy-fleet.sh, .github/workflows/aks.yml, .github/workflows/e2e-ci.yml, .github/workflows/e2e-multicluster-ci.yml, .github/workflows/fleet-upgrade.yml, .github/workflows/gke.yml, .github/workflows/nightly-ci.yml, charts/fleet/values.yaml, cmd/gitjob/main.go, dev/build-fleet, dev/import-images-k3d, manifest-gitjob.tmpl
Naming that image `rancher/gitjob` instead of `rancher/fleet-gitjob` should allow us to keep releasing it with existing permissions.
The risk of confusion for `rancher/gitjob` users is minimal, given that only Fleet is expected to use that repository and its images.
Follow-up to #2008
Also relevant to #2151
=> Rename gitjob image

e2e/assets/imagescan/pre-releases-ignored/deployment.yaml, e2e/assets/imagescan/pre-releases-ignored/fleet.yaml, e2e/assets/imagescan/pre-releases-ok/deployment.yaml, e2e/assets/imagescan/pre-releases-ok/fleet.yaml, e2e/single-cluster/imagescan_test.go, e2e/testenv/githelper/git.go, internal/cmd/controller/imagescan/tagscan_job.go
When using pre-releases in imagescan combined with
```yaml
semver:
range: *
```
it failed because `semver` ignores pre-releases unless they're explicitly described in the `semver.range`.
For example:
```yaml
semver:
range: ">= 0.0.0-40"
```
works fine because it is explicitly using a pre-release.
This fixes the `*` case by checking if there's any version found (lastVersion != nil)
It also adds `e2e` tests for the following imagescans cases:
* Deploy gitrepo with imagescan using `semver.range = ">= 0.0.0-40"` deploying image `0.0.0-40` and after that pushing image `0.0.0-50`
* Same as above but for the case that whis branch fixed (using `semver.range = "*"` with pre-releases.
Refers to: https://github.com/rancher/fleet/issues/2096
=> Fixes panic when imagescan uses prereleases and *

e2e/assets/imagescan/pre-releases-ignored/deployment.yaml, e2e/assets/imagescan/pre-releases-ignored/fleet.yaml, e2e/assets/imagescan/pre-releases-ok/deployment.yaml, e2e/assets/imagescan/pre-releases-ok/fleet.yaml, e2e/single-cluster/imagescan_test.go, e2e/testenv/githelper/git.go, internal/cmd/controller/controllers/image/image.go
When using pre-releases in imagescan combined with
```yaml
semver:
range: *
```
it failed because `semver` ignores pre-releases unless they're explicitly described in the `semver.range`.
For example:
```yaml
semver:
range: ">= 0.0.0-40"
```
works fine because it is explicitly using a pre-release.
This fixes the `*` case by checking if there's any version found (lastVersion != nil)
It also adds `e2e` tests for the following imagescans cases:
* Deploy gitrepo with imagescan using `semver.range = ">= 0.0.0-40"` deploying image `0.0.0-40` and after that pushing image `0.0.0-50`
* Same as above but for the case that whis branch fixed (using `semver.range = "*"` with pre-releases.
Refers to: https://github.com/rancher/fleet/issues/2181
=> [v0.9] Fixes panic when imagescan uses prereleases and *

internal/cmd/agent/controllers/bundledeployment/controller.go, internal/cmd/agent/controllers/bundledeployment/controller_test.go
Refers to #2195 
Filter by `kubernetes.io/metadata.name` label
Use the label `kubernetes.io/metadata.name`, which is added by k8s to all
namespaces, instead of the helm "name" label. The helm "name" label
might be missing from pre-existing namespaces.
Switch `fetchNamespace` to Get instead of list
Was using List with a label, that's set by k8s to the name of the
namespace. Only returned the first result.
Testdata assumed label and namespace name could be different.
=> Fix Existing Namespace Not Found By Label

.github/workflows/release-fleet.yml, .goreleaser.yml, package/Dockerfile, package/Dockerfile.agent, package/Dockerfile.gitjob
This provides a new `release-fleet.yaml` CI workflow to replace our `.drone.yml` pipelines.
[Here](https://github.com/weyfonk/fleet/releases/tag/v42.0.26-test) is an example of a release generated by this new workflow.
Refers to #2121
* Linting
* Integration tests
* `gitjob` and `gitcloner` binaries
* Single checksum file, as per GoReleaser limitation (this may change [soon](https://github.com/goreleaser/goreleaser/issues/4618)); could be mitigated by using a separate workflow step to compute checksums by target arch
* [No Windows-based images](https://github.com/orgs/goreleaser/discussions/2440) for now, although there may be a way (see [experimental branch](https://github.com/weyfonk/fleet/tree/2121-build-windows-images)) involving a patch to GoReleaser
* Further discussion suggested …
=> Replace Drone pipeline with Github actions

internal/cmd/controller/imagescan/tagscan_job.go, internal/cmd/controller/imagescan/tagscan_job_test.go
Previously if users wanted to use image scan with descending alphabetical policy, they had to use uppercase `DESC`, as shown below:
```yaml
imageScans:
- policy:
alphabetical:
order: DESC
```
This is not very intuitive, because the [documentation](https://fleet.rancher.io/imagescan) gives an example in lowercase:
```yaml
imageScans:
- policy:
semver:
range: "*"
alphabetical:
order: asc
```
This PR makes the string check case insensitive, removing the need to use uppercase `DESC` in the `fleet.yaml`
=> Make AlphabeticalPolicy string check case insensitive

go.mod, integrationtests/gitcloner/clone_test.go, integrationtests/gitjob/git/git_test.go
This eliminates linter [errors](https://github.com/rancher/fleet/actions/runs/8291590248/job/22691555805).
Those were not caught when bumping `testcontainers/testcontainers-go` because when running against pull requests, `golangci-lint` only runs against the diff which in that case only affected the go mod and sum files.
=> Use portable API for bind mounts in integration tests

.github/workflows/rancher-integration.yml, .github/workflows/rancher-upgrade-fleet-to-head.yml, .github/workflows/rancher-upgrade-fleet.yml
> Upgrade Fleet in specific Rancher versions to latest fleet release and run MC tests
Can be used to manually verify if a Fleet version would run on an older Rancher install.
Doesn't trigger on tag push events anymore. Doesn't use a matrix. Can only run with fleet > 0.10.0-rc.4.
Switched to reuse values when updating fleet in rancher.
Careful, if not using `--reuse-values` fields like `bootstrap.agentNamespace` are empty. See [fleetcluster](https://github.com/rancher/rancher/blob/a6bb9619c947a9c79ad420660e05cb10b02bf515/pkg/controllers/dashboard/fleetcharts/controller.go#L110-L121) for a list of values.
When using `--resuse-values`, the subchart values are not updated and new defaults are null.
> Upgrade fleet in latest Rancher to dev version and run MC tests
This is the old …
=> Upgrade Fleet in Rancher only triggered manually

charts/fleet/templates/deployment_gitjob.yaml, dev/build-fleet, internal/cmd/gitjob/gitjob.go, package/Dockerfile, package/Dockerfile.agent
Gitjob deployment uses same fields as in the other deployments.
* nodeSelector for linux
* securityContext for uid
* tolerations for linux
Fixed dev script error, tried to copy binary that wasn't build.
Fleet CLI is now on the fleet controller image, update git job to use the new image.
Refers to https://github.com/rancher/fleet/issues/2184
=> Fixes for image reference and CI

.github/scripts/run-integration-tests.sh, dev/run-integration-tests.sh
Devs modify these scripts to run tests locally. Protect the CI scripts from accidential changes, as these are overlooked easily in PR reviews.
=> Duplicate integrationtests scripts for devs

.github/workflows/golangci-lint.yml, .github/workflows/typos.yaml, .golangci.json
Bumping `goglangci-lint` to 4.0.0 and 1.57.2 and adding `skip-pkg-cache: true`.
Using `typos` 1.19.0 as 1.20.0 and 1.20.1 introduced false errors.
False positive introduced in 1.20.1 is:
```
error: `ro` should be `to`
--> ./fleet/cmd/codegen/hack/patch_crd_descriptions.sh:27:59
|
27 |     container_id=$(docker create --rm -i -v ${PWD}:${PWD}:ro -w ${PWD} -v ${tmpdir}:${tmpdir} ${image} yq $@ )
|                                                           ^^
|
```
=> CI bumps golangci-lint and uses typos 1.19.0

.github/workflows/typos.yaml
The false positive issue we had with 1.20.0 and 1.20.1 has been fixed. 
We can get back to master to run the latest.
=> [Backport 0.9] CI: Revert typos back to master

.github/workflows/typos.yaml, _typos.toml
The false positive issue we had with 1.20.0 and 1.20.1 has been fixed. 
We can get back to master to run the latest.
=> CI: Revert typos back to master

internal/bundlereader/loaddirectory.go, internal/bundlereader/loaddirectory_test.go
Refers to #1606 
The module we use would panic if version wasn't set or invalid.
With this change, an explicit version is not required for OCI charts. The module will reach out to the registry and fetch the tags and will resolve them to a version.
```
// If empty, try to get the highest available tag
// If exact version, try to find it
// If semver constraint string, try to find a match
```
https://github.com/helm/helm/blob/release-3.14/pkg/downloader/chart_downloader.go#L144-L175
=> Catch OCI version errors and return them

e2e/assets/single-cluster/helm-status-check.yaml, e2e/single-cluster/single_cluster_test.go
Adding an extra test that deploys a bit more complex scenario so it exercises the Watcher area and events that were filtered in PR: https://github.com/rancher/fleet/pull/2031 
This test should fail from `v0.9.1-rc.2` to `v0.9.1-rc.6` and was fixed after reverting the above PR in `v0.9.2-rc.1`
It also introduces the following changes in CI:
* ~bumps `golangci-lint` to the last version~
* ~adds the `skip-pkg-cache: true` to `golangci-lint`~
* ~Uses typos `v1.19.0` as latest version (v1.20.1) adds false positives~ → see #2269 and #2273 
Related to: https://github.com/rancher/fleet/issues/2128
=> Adds extra e2e test to check status display

package/Dockerfile
We don't need the server
```
> rpm -ql openssh-server
/etc/pam.d/sshd
/etc/slp.reg.d
/etc/slp.reg.d/ssh.reg
/etc/ssh/sshd_config
/etc/sysconfig/SuSEfirewall2.d
/etc/sysconfig/SuSEfirewall2.d/services
/etc/sysconfig/SuSEfirewall2.d/services/sshd
/usr/lib/ssh/sftp-server
/usr/lib/systemd/system/sshd.service
/usr/lib/sysusers.d/sshd.conf
/usr/sbin/rcsshd
/usr/sbin/sshd
/usr/sbin/sshd-gen-keys-start
/usr/share/fillup-templates/sysconfig.ssh
/usr/share/man/man5/sshd_config.5.gz
/usr/share/man/man8/sftp-server.8.gz
/usr/share/man/man8/sshd.8.gz
/var/lib/sshd
```
=> Controller image only install ssh clients

go.mod, go.sum
This version of helm fixes issues with OCI PROXY vars: https://github.com/helm/helm/commit/aa7d95333d5fbc1ea9ed20cc56f011c068e004be
Fork now uses code from open PR for TakeOwnership: https://github.com/rancher/helm/commit/5c115d8b4319705619fa5b86b9232c1c0f2abce6
Refers to https://github.com/rancher/fleet/issues/2246
=> Bump helm fork to 3.14.4

.github/scripts/deploy-fleet.sh, .github/workflows/e2e-ci.yml, charts/fleet/templates/deployment.yaml, dev/setup-fleet, dev/setup-single-cluster, e2e/assets/gitrepo/gitrepo_sharded.yaml, e2e/single-cluster/imagescan_test.go, e2e/single-cluster/sharding_test.go, internal/cmd/controller/operator.go, internal/cmd/controller/reconciler/bundle_controller.go, internal/cmd/controller/reconciler/bundledeployment_controller.go, internal/cmd/controller/reconciler/cluster_controller.go, internal/cmd/controller/reconciler/clustergroup_controller.go, internal/cmd/controller/reconciler/config_controller.go, internal/cmd/controller/reconciler/gitrepo_controller.go, internal/cmd/controller/reconciler/imagescan_controller.go, internal/cmd/controller/root.go, pkg/sharding/sharding.go
This adds support for static sharding to Fleet controllers, as follows:
* Fleet can be deployed with `--set shards="<comma-separated IDs>"`, which will create one controller per shard, named after that shard, plus the usual (unsharded) Fleet controller
* Each sharded Fleet controller is labeled with `shard=<shard ID>`
* Any invalid shard ID, which would not fit in a k8s resource name, will lead to the corresponding Fleet controller not being deployed
Then, a `GitRepo` can be deployed with label `fleet.cattle.io/shard: <shard ID>`, meaning that only the Fleet controller with that label will reconcile it and its children (bundles, bundle deployments). This is end-to-end tested with `GitRepo` creation, but should also work when creating bundles directly.
Any unsharded resource will be …
=> Add static sharding support

internal/cmd/controller/reconciler/bundle_controller.go
Refers to https://github.com/rancher/fleet/issues/1972
The status was not updated in the cluster, we just trigger another reconcile.
=> Remove unused update status code from bundle reconciler

charts/fleet/templates/deployment.yaml
This prevents nil pointer errors when deploying Fleet without any `shards` Helm value, in which case a single controller should and now will be deployed.
It should fix [this CI failure](https://github.com/rancher/fleet/actions/runs/8784583508/job/24103116168).
Refers to #1740
=> Simplify shards configuration detection

dev/README.md
This update enables certain updated Github Actions to run, like `actions/setup-go@v5`.
=> Update dev/README Dockerfile for act container image

pkg/apis/fleet.cattle.io/v1alpha1/groupversion_info.go, pkg/apis/go.mod, pkg/apis/go.sum, pkg/apis/internal/scheme.go
Users of our apis package should not need to import controller-runtime
=> Embed controller-runtimes SchemeBuilder

e2e/assets/gitrepo/gitrepo_sharded.yaml, e2e/single-cluster/sharding_test.go
This makes sharding end-to-end tests more lightweight by relying on `GitRepo`s pointing to an external repository. Relying on test infrastructure and creating git repositories on-the-fly is not necessary, because sharding tests don't need to push any commit.
Checks on Fleet controller logs are now more reliable, by consistently tailing the last 100 log entries.
=> Simplify sharding end-to-end tests

e2e/assets/cluster-template.yaml, e2e/metrics/bundle_test.go, e2e/metrics/bundledeployment_test.go, e2e/metrics/cluster_test.go, e2e/metrics/clustergroup_test.go, e2e/metrics/exporter.go, e2e/metrics/gitrepo_test.go, e2e/metrics/suite_test.go, e2e/testenv/template.go
- **e2e/metrics: use a single instance of ExporterTest**
- **e2e/metrics: remove unused functions**
- **e2e/metrics: add E2E test for cluster deletion and modifications**
- **e2e/metrics: simplify testing cluster resources**
- **e2e/metrics: properly test fleet_cluster_state metric**
Refers to #2315
=> metrics: Add E2E test for cluster deletion

e2e/testenv/infra/cmd/setup.go
Those [security warnings](https://github.com/rancher/fleet/actions/runs/8889578834) output by the linter are not very relevant in this context of an ephemeral, local test setup.
=> Ignore gosec errors in end-to-end tests infra setup

.github/workflows/aks.yml, .github/workflows/gke.yml, .github/workflows/nightly-ci.yml
With sharding end-to-end tests now running without needing test infra (see #2396), those tests will run in AKS and GKE workflows, where Fleet deployments need sharding enabled to allow those tests to pass.
This PR also fixes Fleet deployments in a similar way for the nightly CI workflow.
This should fix CI failures such as [this one](https://github.com/rancher/fleet/actions/runs/8935401076/job/24543850540) (nightly) and [that one](https://github.com/rancher/fleet/actions/runs/8937525971/job/24549947791) (AKS).
=> Add sharding to Fleet deployments in CI workflows running end-to-end tests

internal/cmd/agent/clusterstatus.go, internal/cmd/agent/register.go, internal/cmd/agent/root.go, internal/cmd/builder.go, internal/cmd/controller/agentmanagement/root.go, internal/cmd/controller/cleanup/root.go, internal/cmd/controller/gitops/operator.go, internal/cmd/controller/root.go
The binaries run a default action if no sub command is given. The flags of the default action, e.g. running the main fleet controller, aka manager, are inherited by the sub commands as global flags.
This is a easy fix to hide the unsupported flags. We could turn all parent commands into sub commands one day, but it seems low priority.
This does not seem to affect doc generation with `go run cmd/docs/generate-cli-docs.go ../docs/docs/cli/`, so we still need to look out for the options in docs: https://github.com/rancher/fleet-docs/pull/128
Refers to https://github.com/rancher/fleet/issues/2342
=> Hide global CLI flags on sub commands

charts/fleet-crd/templates/crds.yaml, e2e/assets/single-cluster/delete-namespace/gitrepo.yaml, e2e/single-cluster/delete_namespaces_test.go, internal/bundlereader/read.go, internal/cmd/cli/apply.go, internal/cmd/cli/apply/apply.go, internal/cmd/controller/gitops/reconciler/gitjob_controller.go, internal/cmd/controller/reconciler/gitrepo_controller.go, pkg/apis/fleet.cattle.io/v1alpha1/bundledeployment_types.go, pkg/apis/fleet.cattle.io/v1alpha1/gitrepo_types.go
Refers to #1564
This PR introduces a new attribute `spec.deleteNamespace: boolean` in gitRepo to delete the namespace when gitRepo is deleted. This namespace is created by fleet to deploy the services. 
Thanks @weyfonk :heart:
=> Delete namespace when a gitRepo is deleted

dev/setup-fleet-downstream, dev/setup-k3ds
The dev scripts failed to work on a customized setup of docker where `/etc/docker/daemon.json` contains the following JSON to prevent conflicts on the host with a different configuration.
```json
{
"bip": "172.26.0.1/16",
"default-address-pools": [
{
"base": "172.27.0.0/16",
"size": 24
},
{
"base": "172.28.0.0/16",
"size": 24
},
{
"base": "172.29.0.0/16",
"size": 24
},
{
"base": "172.30.0.0/16",
"size": 24
},
{
"base": "172.31.0.0/16",
"size": 24
},
{
"base": "172.32.0.0/16",
"size": 24
}
]
}
```
The update makes the certificate usable for the internal DNS name of the upstream cluster. The `apiServerURL` is then configured to talk to the upstream server directly rather than through the bridge of the host.
Refers to #XXX
=> dev-scripts: Change apiServerURL for setup-fleet-downstream

charts/fleet/templates/deployment.yaml, charts/fleet/values.yaml, internal/cmd/controller/operator.go, internal/cmd/controller/reconciler/bundle_controller.go, internal/cmd/controller/reconciler/bundledeployment_controller.go, internal/cmd/controller/reconciler/gitrepo_controller.go, internal/cmd/controller/root.go
Refers to https://github.com/rancher/fleet/issues/2415
Added a new environment var for each type of reconciler (gitrepo, bundle, bundledeployment) to configure their worker count (in values.yaml)
No test for this, we need a large scale fleet to test to test it
=> Add a Parameter to Configure Worker count for fleet-controller

.github/workflows/e2e-ci.yml, .github/workflows/nightly-ci.yml, charts/fleet/templates/service.yaml, dev/README.md, e2e/assets/clustergroup-template.yaml, e2e/assets/gitrepo-template.yaml, e2e/assets/metrics/fleetcontroller_service.yaml, e2e/metrics/bundle_test.go, e2e/metrics/bundledeployment_test.go, e2e/metrics/cluster_test.go, e2e/metrics/clustergroup_test.go, e2e/metrics/exporter.go, e2e/metrics/gitrepo_test.go, e2e/metrics/suite_test.go, e2e/single-cluster/values_from_test.go, e2e/testenv/template.go
=> metrics: make sure metrics work well with sharding

.golangci.json, dev/update-controller-k3d, e2e/metrics/bundle_test.go, e2e/metrics/bundledeployment_test.go, e2e/multi-cluster/bundle_namespace_mapping_test.go, e2e/multi-cluster/depends_on_test.go, e2e/single-cluster/values_from_test.go, e2e/testenv/template.go, integrationtests/gitjob/controller/controller_test.go, internal/cmd/controller/gitops/reconciler/gitjob_controller.go, internal/cmd/controller/summary/summary.go
The gitjob reconciler updates the gitrepo resource with information it was acting on.
* ObservedGeneration, this is also updated in the gitrepo reconciler. However the gitjob reconciler updates the status and should note the generation it worked on.
* Job termination message, if the gitrepo reconciler is conflicting with the gitjob reconciler while trying to update the status, the gitjob reconciler will store the message as it was when it triggered.
Also fixes several tests that were not waiting for setup to be complete, or trying to update outdated resources.
Refers to #2435
=> Gitjob controller updates GitRepo with generation it is reconciling

charts/fleet/templates/configmap.yaml
Refers to #XXX
This causes `Error("trailing comma", line: 16, column: 13)` when using serde_json to deserialize the value and do something with apiServerURL and apiServerCA. Unfortunately this rust framework does not tolerate invalid json content.
=> Remove trailing comma from bootstrap template

charts/fleet/templates/deployment.yaml, charts/fleet/templates/service.yaml, e2e/assets/gitrepo-template.yaml, e2e/assets/gitrepo/gitrepo_sharded.yaml, e2e/assets/metrics/fleetcontroller_service.yaml, e2e/metrics/cluster_test.go, e2e/metrics/clustergroup_test.go, e2e/single-cluster/imagescan_test.go, e2e/single-cluster/sharding_test.go, pkg/sharding/sharding.go
Refers to https://github.com/rancher/fleet/issues/2358
=> Rename sharding labels

internal/cmd/cli/apply.go
That command does not render bundles into Kubernetes resources, but rather creates bundles from directories.
=> Fix `fleet apply` command description

.github/ISSUE_TEMPLATE/1-bug-report.yml
While creating issue to the Fleet repository, I got to know that collapsed blocks are not closed.
=> Fix summary and details tags in bug report template

integrationtests/gitjob/controller/controller_test.go, internal/cmd/controller/gitops/reconciler/gitjob_controller.go
`gitrepo`s `Status.UpdateGeneration` value was changed but not updated, which made the controller to enter in an infinite loop regenerating the job.
Refers to: https://github.com/rancher/fleet/issues/2474
=> Fixes infinite job generation after ForceSyncGeneration changed

charts/fleet/templates/rbac_gitjob.yaml, integrationtests/controller/gitrepo/gitrepo_test.go, integrationtests/gitjob/controller/controller_test.go, integrationtests/gitjob/controller/suite_test.go, internal/cmd/controller/errorutil/errorutil.go, internal/cmd/controller/gitops/reconciler/gitjob_controller.go, internal/cmd/controller/gitrepo/status.go, internal/cmd/controller/reconciler/cluster_controller.go, internal/cmd/controller/reconciler/clustergroup_controller.go, internal/cmd/controller/reconciler/gitrepo_controller.go
Moves the following from `gitrepo` controller to `gitjob` controller:
* AuthorizeAndAssignDefaults
* RBAC resources creation
* Helm secrets check
* NewTargetsConfigMap
The `gitrepo` controller still purges `bundles` and `bundledeployments` on `gitrepo` deletion and handles the status coming from `bundles` and `bundledeployments`
Some functionality that was shared between both controllers has been moved to a common package to avoid code repetition.
Refers to: https://github.com/rancher/fleet/issues/2435
=> Moves functionality from gitrepo to gitjob controller

charts/fleet/templates/deployment.yaml, charts/fleet/templates/deployment_gitjob.yaml, charts/fleet/values.yaml
This will enable to pass, for example, experimental features to the upstream fleet pods.
Refers to: https://github.com/rancher/fleet/issues/2465
Related to: https://github.com/rancher/fleet/issues/2114
=> Adds extraEnv to gitjob and fleet-controller deployments

charts/fleet/values.yaml
Refers to #XXX
Try installing the chart with the example in the values.yaml uncommented, this will not apply cleanly.
This changes the example in the values.yaml for enabling the OCI storage to be valid for insertion into the "env" for a container.
Previously, it was a boolean, which would lead to a failure to unmarshal a bool to a string.
=> Fix example values.yaml for enabling OCI storage

integrationtests/controller/bundle/bundle_labels_test.go, integrationtests/controller/bundle/bundle_targets_test.go, integrationtests/controller/bundle/status_test.go, integrationtests/controller/bundle/suite_test.go, integrationtests/controller/bundledeployment/status_test.go, integrationtests/controller/bundledeployment/suite_test.go, integrationtests/controller/cluster/status_test.go, integrationtests/controller/cluster/suite_test.go, integrationtests/controller/clustergroup/status_test.go, integrationtests/controller/clustergroup/suite_test.go, integrationtests/controller/gitrepo/status_test.go, integrationtests/controller/gitrepo/suite_test.go, integrationtests/utils/envtest.go, integrationtests/utils/helpers.go, internal/cmd/controller/reconciler/cluster_controller.go
Refers to https://github.com/rancher/fleet/pull/2400
Add integration tests to check status reconciles
* BundleDeployment triggers Bundle
* Bundle triggers GitRepo
* BundleDeployment triggers Cluster
* uses BundleDeployment and GitRepo for update
* Cluster triggers ClusterGroup
=> Add status reconcile tests

integrationtests/agent/bundle_deployment_status_test.go, integrationtests/gitcloner/clone_test.go, internal/cmd/agent/controller/bundledeployment_controller.go
* clone test doesn't work with docker in VM, needs more than k8s API port exposed
* agent/bundle_deployment_status_test is flaky, missed error in ModifiedStatus. Is this the correct agent behavior?
=> Fix flaky agent modified status test

charts/fleet/templates/deployment_gitjob.yaml
The settings were not effective, see helm warning when installing the chart with debug=false.
Settings need to be in the containers `securityContext`, not the pod's.
Refers to https://github.com/rancher/fleet/issues/2359
=> Security context needs to be on container

integrationtests/agent/bundle_deployment_status_test.go
Applies the fix from https://github.com/rancher/fleet/pull/2504 to another flaky test
=> Fixes flaky agent integration test

.github/workflows/release-fleet.yml, .goreleaser.yaml
I have migrated the config following: https://goreleaser.com/blog/goreleaser-v2/
Since we do not seem to use any deprecated options, I have just had to add the version to the config file.
I have ran the goreleaser check with the following output:
```
$ goreleaser check
• checking                                 path=.goreleaser.yaml
• 1 configuration file(s) validated
• thanks for using goreleaser!
```
=> Bump go releaser config

integrationtests/gitjob/controller/controller_test.go
That test relied on branch `renovate/golang.org-x-crypto-0.x`, which no longer exists on `rancher/fleet`.
Instead, this now relies on an old release branch, which is both less likely to be deleted and unlikely to be updated, since the corresponding version is no longer maintained.
=> Fix flaky integration test for git job with polling disabled

e2e/drift/drift_test.go, internal/cmd/agent/deployer/monitor.go, internal/helmdeployer/deployer.go
Refers to #2515
* Drift correction (self-healing) uses Helm's [Rollback action](https://pkg.go.dev/helm.sh/helm/v3/pkg/action#Rollback), which has a `MaxHistory` field. This value takes precedence over the config value. Unlike the [`Upgrade` action](https://github.com/rancher/fleet/blob/68597ce1aca9bfac58547f8b92ad060b7aa90cf5/internal/helmdeployer/install.go#L163-L166), we omitted to set this value, so the releases will only shrink when running an upgrade but not rollbacks`.
* I noticed that sometimes, a regular upgrades would be deployed (creating a new). Initially I thought this would happen if all the releases in the remaining history were rollbacks, but realized the problem is that the BundleDeployment status has a `release` field, referencing the latest release installed. This value …
=> [0.9] Honor Helm's MaxHistory when using drift correction

pkg/apis/fleet.cattle.io/v1alpha1/bundle_types.go, pkg/apis/fleet.cattle.io/v1alpha1/bundledeployment_types.go, pkg/apis/fleet.cattle.io/v1alpha1/bundlenamespacemapping_types.go, pkg/apis/fleet.cattle.io/v1alpha1/cluster_types.go, pkg/apis/fleet.cattle.io/v1alpha1/clustergroup_types.go, pkg/apis/fleet.cattle.io/v1alpha1/clusterregistration_types.go, pkg/apis/fleet.cattle.io/v1alpha1/clusterregistrationtoken_types.go, pkg/apis/fleet.cattle.io/v1alpha1/content_types.go, pkg/apis/fleet.cattle.io/v1alpha1/gitrepo_types.go, pkg/apis/fleet.cattle.io/v1alpha1/gitreporestriction_types.go, pkg/apis/fleet.cattle.io/v1alpha1/groupversion_info.go, pkg/apis/fleet.cattle.io/v1alpha1/imagescan_types.go, pkg/apis/go.mod, pkg/apis/go.sum, pkg/apis/internal/scheme.go
Refers to https://github.com/rancher/rancher/pull/45271 and https://github.com/rancher/fleet/pull/2377
rancher/rancher and rancher/shepherd are expecting `SchemeBuilder` to be a `apimachinery.SchemeBuilder`, we want to use the [one from controller runtime](https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/scheme/scheme.go) internally. Embedding the c-r code, so consumers don't inherit the controller-runtime dependency from our API pkg. Hasn't changed for years.
=> Keep schemebuilder type

.github/workflows/aks.yml, .github/workflows/e2e-ci.yml, .github/workflows/gke.yml, .github/workflows/nightly-ci.yml, e2e/assets/drift/correction-disabled/gitrepo.yaml, e2e/assets/drift/correction-enabled/gitrepo.yaml, e2e/assets/drift/force/gitrepo.yaml, e2e/drift/drift_test.go, e2e/drift/suite_test.go
This includes drift tests, previously omitted, in our CI workflows running single-cluster end-to-end tests.
=> Include drift end-to-end tests in CI workflows

charts/fleet/templates/service_gitops_metrics.yaml, internal/cmd/controller/gitops/operator.go
Refers to #2450 
Introduced a new service for gitops metrics
=> Add metrics to gitops controller

e2e/assets/drift/correction-enabled/gitrepo.yaml, e2e/drift/drift_test.go, internal/cmd/agent/deployer/normalizers/norm.go, internal/cmd/agent/deployer/normalizers/status.go, internal/cmd/agent/deployer/normalizers/status_test.go
Refers to #2521
Use a new `StatusNormalizer` when comparing deployed resources against the desired spec, since `status` is normally not part of it.
=> Ignore status fields during drift detection

integrationtests/controller/bundle/status_test.go, internal/cmd/controller/reconciler/bundle_controller.go, internal/cmd/controller/reconciler/bundle_status.go
=> Populate bundle status from bundleDeployment status resources

pkg/durations/durations.go, pkg/git/poll/gitrepopolljob.go, pkg/git/poll/gitrepopolljob_test.go, pkg/git/poll/handler.go, pkg/git/poll/handler_test.go
When the gitpoller job returns an error it is added to the `gitrepo` conditions so it can be properly displayed by the UI.
It also reschedules the gitpoller job when the `gitrepo` spec is changed so the job is immediately executed.
Refers to: https://github.com/rancher/fleet/issues/2520
=> Fixes error display and improves user experience in git poller

internal/bundlereader/read.go, internal/cmd/agent/controller/bundledeployment_controller.go, internal/cmd/controller/options/calculate.go, internal/cmd/controller/reconciler/bundle_controller.go, internal/cmd/controller/reconciler/bundledeployment_controller.go, internal/cmd/controller/reconciler/cluster_controller.go, internal/cmd/controller/reconciler/clustergroup_controller.go, internal/cmd/controller/reconciler/config_controller.go, internal/cmd/controller/reconciler/imagescan_controller.go, internal/cmd/controller/target/builder.go
We often lookup what triggers a reconcile, though receiver funcs are not
alphabetically sorted anymore, this should be easier to find now.
Targets returns a list of targets and an error.
foldInDeployments cleverly mutated the returned list. No more.
=> Refactor reconcilers and remove foldin func

.github/scripts/deploy-fleet.sh, .github/workflows/e2e-ci.yml, .github/workflows/e2e-multicluster-ci.yml, .github/workflows/nightly-ci.yml, charts/fleet-agent/templates/configmap.yaml, charts/fleet-agent/values.yaml, charts/fleet-crd/templates/crds.yaml, charts/fleet/templates/configmap.yaml, charts/fleet/values.yaml, dev/setup-fleet-downstream, e2e/multi-cluster/installation/agent_test.go, e2e/multi-cluster/installation/suite_test.go, internal/cmd/agent/register/register.go, internal/cmd/controller/agentmanagement/agent/config.go, internal/cmd/controller/agentmanagement/controllers/cluster/import.go, internal/config/config.go, pkg/apis/fleet.cattle.io/v1alpha1/cluster_types.go
Refers to #2171
This adds a new Helm value named `agentTLSMode`, with two supported values:
* `system-store`, the default: in this mode, the Fleet agent behaves as it has so far, trusting certificates signed by any CA installed in the system store when registering against an upstream cluster.
* In this mode, Fleet will also ignore a configured CA, if the system trust store is sufficient.
* `strict`, to ignore the system store during the cluster registration process
Updating that value in the `fleet-controller` config map triggers redeployment of the Fleet agent, on the upstream cluster and on downstream clusters _which had been registered following a manager-initiated process_ (as would typically be the case when importing clusters through Rancher). This does not work for agent-initiated …
=> Add strict TLS mode support

dev/build-fleet, dev/k3d-act-clean, dev/setup-single-cluster
By using different git worktrees with different environment variables for configuring the single-cluster environment, specifically the `FLEET_E2E_CLUSTER` variable, you can use `./dev/setup-single-cluster` to start independent k3d clusters next to each other.
Please note that, at the time of creating a cluster, there is a possibility of a conflict still. While clusters can be run at the same time with `dev/setup-single-cluster`, they cannot be created simultaneously (yet).
=> dev: Make setup-single-cluster capable of setting up multiple clusters

internal/cmd/agent/register/register.go, internal/config/overrides.go
Strict TLS mode must be applied not only in the `fleet-agent-register` init container, but also in the main agent container itself, which also reaches out to the upstream cluster.
Refers to #2171.
Follow-up to #2507.
=> Extend strict TLS mode to `fleet-agent` container

internal/cmd/agent/register/register.go, internal/cmd/cli/gitcloner/cloner.go, internal/cmd/cli/gitcloner/cloner_test.go
Refers to https://github.com/rancher/fleet/issues/2492
Pull request content for Rancher QA verification.
Since switching to go-git, Fleet would no longer clone submodules.
According to the go-git documentation this is how to enable submodule cloning.
Tested with fleet-test-data submodule in https://github.com/manno/fleet-experiments
```
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
name: crd-experiment
spec:
repo: https://github.com/manno/fleet-experiments
branch: main
paths:
- fleet-test-data/simple-chart
targets:
- clusterSelector: {}
```
We would need another repo like rancher/fleet-test-data to include as a submodule.
Too many nested repos are a problem for performance.
=> Gitcloner recurses submodules

.github/workflows/release-fleet.yml
to not interfere with releases when a new linter is released.
=> Remove linter from release pipeline

.github/scripts/deploy-fleet.sh, .github/workflows/aks.yml, .github/workflows/gke.yml
This should prevent CI failures ([AKS](https://github.com/rancher/fleet/actions/runs/9731245163/job/26855427978), [GKE](https://github.com/rancher/fleet/actions/runs/9736989252/job/26868427918)) caused by nodes not being created by k3d on those clusters.
The root cause for these failures is the recent introduction of logic to override the API server URL and CA for strict TLS mode testing.
=> Override Kubernetes node when deploying Fleet to AKS/GKE

charts/fleet/templates/deployment_gitjob.yaml, go.mod, internal/cmd/agent/clusterstatus.go, internal/cmd/agent/register.go, internal/cmd/agent/root.go, internal/cmd/controller/gitops/operator.go, internal/cmd/controller/root.go, internal/cmd/debug.go
Refers to https://github.com/rancher/fleet/issues/2472
=> Override zap log level from old flag

internal/cmd/controller/finalize/finalize.go
When testing https://github.com/rancher/fleet/issues/2586 the `Bundle` reconciler found that the `Bundle` was gone as was trying to delete the same `BundleDeployments` in parallel.
Deleting the `Bundle` after deleting all its `BundleDeployments` seems to help to prevent that race condition between both reconcilers
Refers to: https://github.com/rancher/fleet/issues/2586
=> Deletes `Bundles` after deleting all its `BundleDeployments`

internal/cmd/controller/gitops/operator.go
Refers to #2138 
Going from
> A zero Group is valid, has no limit on the number of active goroutines, and does not cancel on error.
to
> WithContext returns a new Group and an associated Context derived from ctx.
> 
> The derived Context is canceled the first time a function passed to Go returns a non-nil error or the first time Wait returns, whichever occurs first.
>
=> Make gitops controller exit when losing leader lease

internal/cmd/controller/finalize/finalize.go
As we are using finalizers for Bundles we can let the Bundle reconciler deal with its BundleDeployments and just delete the Bundle in the gitops reconciler.
That way we avoid having race conditions between both reconcilers trying to delete the same BundleDeployments
Related to: https://github.com/rancher/fleet/issues/2586
=> Gitopts reconciler just deletes the Bundle, not BundleDeployments

charts/fleet-crd/templates/crds.yaml, dev/update-agent-k3d, dev/update-controller-k3d, pkg/apis/fleet.cattle.io/v1alpha1/bundle_types.go, pkg/apis/fleet.cattle.io/v1alpha1/cluster_types.go, pkg/apis/fleet.cattle.io/v1alpha1/gitrepo_types.go
Gitops controller was complaining about `KubeAPIWarningLogger	unknown field "status.resources[0].perClusterState[0].patch.data"`
Diff against 0.9.3 showed some missing markers in the generated CRD.
=> Remove kubeapiwarning message via crds

.github/workflows/ci.yml, charts/fleet-agent/.helmignore, charts/fleet-agent/ci/default-values.yaml, charts/fleet-agent/values.yaml, charts/fleet/.helmignore, charts/fleet/ci/debug-values.yaml, charts/fleet/ci/nobootstrap-values.yaml, charts/fleet/ci/nodebug-values.yaml, charts/fleet/ci/nogitops-values.yaml, charts/fleet/templates/deployment_gitjob.yaml, charts/fleet/values.yaml
Setting debug to false would put the additional env vars outside the env block.
```
% helm template --set 'extraEnv[0].name="foo"' --set 'extraEnv[0].value="bar"' fleet charts/fleet
Error: YAML parse error on fleet/templates/deployment_gitjob.yaml: error converting YAML to JSON: yaml: line 47: did not find expected key
Use --debug flag to render out invalid YAML
```
=> Fix extraEnv in gitjob controller template

.github/workflows/release-fleet.yml
We still get the signal from the tests, but we can still produce builds for testing.
=> Release workflow continues on test errors for RC

internal/helmdeployer/postrender.go
Changes the error message when `targetNamespace` or `namespace` is specified and there are cluster wide resources to be deployed. 
I've tested also with `rancher` so we can see how it looks like in the UI (pretty large, but hopefully more explanatory) 
Refers to: https://github.com/rancher/fleet/issues/2484
=> Changes post render error when using targetNamespace or namespace

integrationtests/cli/assets/bundledeployment/bd-with-kube-version.yaml, integrationtests/cli/deploy/deploy_test.go, internal/cmd/cli/deploy.go, internal/cmd/cli/match/match.go, internal/helmdeployer/capabilities.go, internal/helmdeployer/template.go
Refers to #2633
This Pull Requests fixes the kubeVersion validation error by:
1.) Introducing a new argument `--kube-version` to allow users to override the target version Helm charts can be validated against. This follows the exact same semantics as the `--kube-version` argument of the `helm template` command.
2.) Where no `--kuberversion` is specified, a more reasonable default of 1.25.0 is provided.
An integration test, "Printing results with --dry-run where the chart specifies kubeVersion >= 1.26.0", was added  in integrationtests/cli/deploy/deploy_test.go to illustrate both the issue and the fix
=> KubeVersion fix for fleet deploy --dry-run

internal/cmd/controller/agentmanagement/agent/manifest.go, internal/cmd/controller/agentmanagement/agent/manifest_test.go
Getting an agent StatefulSet from a manifest for unit tests always happens in namespace `fleet-system`, which is now a package-wide constant.
To prevent that constant from being used in the implementation package, unit tests now live in a separate `agent_test` package.
This should fix `golangci-lint` workflow failures such as [this one](https://github.com/rancher/fleet/actions/runs/10138467073/job/28030207568).
=> Fix linting error

charts/fleet/templates/configmap.yaml, charts/fleet/values.yaml, integrationtests/gitjob/controller/controller_test.go, integrationtests/gitjob/controller/suite_test.go, integrationtests/gitjob/git/git_test.go, internal/cmd/controller/gitops/operator.go, internal/cmd/controller/reconciler/config_controller.go, internal/config/config.go, pkg/git/fetch.go, pkg/git/fetch_test.go, pkg/git/netutils.go, pkg/git/netutils_test.go, pkg/git/remote.go, pkg/git/vendor.go, pkg/git/vendor_test.go
Fixes #2188
Also fixes an issue in the config reconciler which has prevented the
config from being reloaded when it was changed.
=> Configurable git client timeout

internal/cmd/controller/reconciler/bundledeployment_controller.go
Purging content resources happens when triggering bundle deployment deletion from a bundle deletion, or even a `GitRepo` deletion.
Direct bundle deployment deletion is not supported, and does not work because:
* a bundle deployment is not meant to be created on its own, ie without a bundle
* deleting a bundle deployment before deleting the bundle from which it was created will lead to that bundle deployment being re-created by the bundle reconciler.
Follow-up to #2566
Refers to #2464
=> Remove content cleanup from bundle deployment reconciler

e2e/assets/single-cluster/namespaceLabels_targetCustomization.yaml, e2e/single-cluster/targetCustomization_test.go, internal/cmd/agent/deployer/deployer.go, internal/cmd/agent/deployer/deployer_test.go, internal/cmd/controller/target/target.go, pkg/apis/fleet.cattle.io/v1alpha1/bundle_types.go, pkg/apis/fleet.cattle.io/v1alpha1/bundledeployment_types.go, pkg/apis/fleet.cattle.io/v1alpha1/zz_generated.deepcopy.go
Follow-up to #2583.
Refers to #2262 and #2441.
This simplifies end-to-end tests and the implementation for using namespace labels and annotations as target customisations.
In bundle deployment options, maps are used directly instead of pointers to maps for namespace labels and namespace annotations.
Manual tests suggest that Kubernetes represents bundles deployments with identical YAML in both cases, ie whether pointers to maps or simple maps are used to represent those fields.
=> Simplify target customisations for namespace labels and annotations

internal/cmd/controller/gitops/operator.go, internal/cmd/controller/gitops/reconciler/gitjob_controller.go, internal/cmd/controller/gitops/reconciler/gitjob_test.go
Due to `  Error: internal/cmd/controller/gitops/reconciler/gitjob_controller.go:137:1: cyclomatic complexity 35 of func `(*GitJobReconciler).Reconcile` is high (> 30) (gocyclo)`
* simplify names
* order imports into groups
* extract the job handling into a function
=> Refactor gitjops reconciler to remove complexity warning

e2e/single-cluster/gitrepo_polling_disabled_test.go
Avoid waiting for namespace to be deleted.
This was causing issues like on other e2e tests.
The output is used in case of error.
I've been testing in a loop for a few hours while doing other stuff and all namespaces were deleted correctly.
=> Fixes e2e flaky test.

charts/fleet-agent/Chart.yaml, charts/fleet-agent/values.yaml, charts/fleet-crd/Chart.yaml, charts/fleet-crd/README.md, charts/fleet-crd/templates/crds.yaml, charts/fleet/Chart.yaml, cmd/docs/generate-cli-docs.go, internal/cmd/controller/root.go, internal/config/config.go, pkg/apis/fleet.cattle.io/v1alpha1/cluster_types.go
This removes manager references from non-controller Fleet chart descriptions, and renames the `FleetManager` struct as `FleetController` to enable correct Markdown documentation to be generated from it through `generate-cli-docs.go`.
This could be taken further by renaming eg. `Manager-initiated [cluster] registration` as `Controller-initiated registration` for more consistency.
=> Rename Fleet manager references as Fleet controller

dev/setup-fleet-managed-downstream, dev/setup-fleet-multi-cluster, dev/setup-rancher-clusters
I had problems with the agent-initiated dev script, which needs a public URL.
* also remove unneeded token
* disable strict TLS mode
=> Switch dev scripts to managed clusters

internal/helmdeployer/install.go
With `--skip-schema-validation` supported in Helm's `Install` and `Upgrade` operations through https://github.com/helm/helm/pull/12743, Fleet no longer needs to manipulate chart data to skip that validation.
Depends on #2747, left in draft state until that one is merged.
=> Skip schema validation through helm

.github/workflows/golangci-lint.yml, charts/fleet/values.yaml, internal/config/config.go, internal/config/config_test.go, internal/config/suite_test.go
A zero value for the gitClientTimeout setting would mean that the request would not have a client side timeout set, potentially resulting in an endless waiting state. Although it should not happen that this value is missing, which would lead to it being zero, it should be safer to fall back to 30s as in previous versions of Fleet, thereby preventing the user from disabling the git client timeout completely.
Follow-up for #2188
=> Prevent `0` as value for gitClientTimeout

internal/cmd/controller/reconciler/bundledeployment_controller.go
This issue is affecting the `BundleDeployment` when it is deleted after targetting discards it as a valid target.
The reconciler was not called when `DeletionTimestamp` was set and there was a typo that prevented the finalizer to be deleted.
Refers to: https://github.com/rancher/fleet/issues/2768
Backport of: https://github.com/rancher/fleet/pull/2820
=> [v0.10] Fixes finalizer deletion in bundle deployments

internal/cmd/controller/gitops/reconciler/gitjob_controller.go
Backport of #2825
Refers to #2829.
=> [v0.10] Create cabundle secret

.github/scripts/deploy-fleet.sh, charts/fleet/templates/deployment_gitjob.yaml
Refers to https://github.com/rancher/fleet/issues/2828
Backport of #2827.
Also disable debug logging for tests, since it disables the security context too
=> [v0.10] Gitjob container has writable /tmp dir

integrationtests/agent/assets/deployment-v1.yaml, integrationtests/agent/bundle_deployment_drift_test.go, integrationtests/agent/bundle_deployment_status_test.go, integrationtests/agent/suite_test.go, internal/cmd/agent/controller/bundledeployment_controller.go
This gives more visibility to errors which may happen when correcting drift.
A known example causing such errors is updating a port on a service (see https://github.com/kubernetes/kubernetes/issues/105610).
Refers to #2609.
Comes with new integration tests, paving the way for migrating at least some of our end-to-end drift test suite to integration tests (#2771).
=> Propagate drift correction error to bundle deployment status

e2e/single-cluster/sharding_test.go
Sharding end-to-end tests would previously read `debug` controller logs, which was brittle as it would fail:
* when running the test suite multiple times, as those checks relied on the _absence_ of some logs
* when debug logging was disabled
They now check that bundles and bundle deployments created through `GitRepo`s are labelled with the right shard ID instead.
Refers to #2826
=> Skip checks on logs in sharding end-to-end tests

e2e/drift/drift_test.go, integrationtests/agent/bundle_deployment_drift_test.go, internal/helmdeployer/install.go
This enables drift correction to be forced after the fact, which can help users deal with edge cases such as patching ports services, a case known not to be [supported](https://github.com/helm/helm/issues/12974) by Helm.
Depends on #2792.
Refers to #2609
=> Propagate drift correction force mode to Helm rollback

e2e/single-cluster/sharding_test.go
* Skip checks on logs in sharding tests
This prevents test failures when tests are run more than once, without logs being cleared (eg. without deployments being scaled down and back up) between runs, or when debug logs are disabled
* Add shard ID checks on bundle and bundle deployment
Sharding end-to-end tests now check that Fleet resources created from a `GitRepo` bear the same shard ID value, through the `fleet.cattle.io/shard-ref` label, as specified in the `GitRepo` itself.
User resources contained in bundle deployments are not labelled with the shard ID.
* Fix check on configmap absence
When checking for a config map not being created, we must check that it _consistently_ doesn't exist, instead of verifying that it eventually (at a unique point in time) doesn't exist.
Backport of …
=> [v0.10] Skip checks on logs in sharding end-to-end tests

e2e/assets/multi-cluster/bundle-deployment-labels.yaml, e2e/multi-cluster/not_matching_targets_delete_bd_test.go, e2e/testenv/env.go, e2e/testenv/kubectl/kubectl.go
This adds a new test to check that when applying a gitrepo that targets based on labels it deploys/deletes the bundledeployment depending if the label for targetting is present or not in the downstream cluster
This is related to: https://github.com/rancher/fleet/pull/2820
Refers to: https://github.com/rancher/fleet/issues/2768
=> Adds e2e test to check that bundledeployments are deleted

.golangci.json, internal/cmd/agent/clusterstatus.go, internal/cmd/controller/agentmanagement/controllers/controllers.go, internal/cmd/controller/cleanup/controllers/controllers.go
This updates rate limiters where possible to make use of newer, generic, rate limiters.
Eliminating remaining errors would require updating `rancher/lasso`'s [SharedControllerFactoryOptions](https://github.com/rancher/lasso/blob/master/pkg/controller/sharedcontrollerfactory.go#L31), therefore this commit simply ignores them through `golangci-lint` configuration.
=> Fix linting errors caused by workqueue rate limiter

e2e/drift/drift_test.go, integrationtests/agent/bundle_deployment_drift_test.go, internal/helmdeployer/install.go
Refers to #2834.
Backport of #2798 to v0.10.
Depends on #2835.
Depends on #2838 for sharding end-to-end tests to pass, following #2830.
=> [v0.10] Propagate drift correction force mode to Helm rollback

.github/workflows/e2e-nightly-ci.yml
The name should be unique for all matrix jobs
=> Fix log artifact name in e2e-nightly

internal/helmdeployer/postrender.go, internal/helmdeployer/postrender_test.go
Refers to #2716
When `deleteCRDResources` was disabled (default), the `helm.sh/resource-policy` annotation was added to more resources than just CRDs, because as soon as there was one CRD, the `annotations` variable was modified which also gets used by other resources in the loop (resources that were processed before the first CRD are fine). The fix is now to only modify a copy of the annotations that doesn't get reused for other resources.
This same bug also exists in the 0.9 branch in the [`deployer.go`](https://github.com/rancher/fleet/blob/release/v0.9/internal/helmdeployer/deployer.go#L170-L175). Should I also create a separate PR for that branch?
=> Fix helm.sh/resource-policy being added to everything and not just CRDs

charts/fleet-crd/templates/crds.yaml, integrationtests/cli/deploy/deploy_test.go, internal/cmd/agent/controller/bundledeployment_controller.go, internal/cmd/agent/deployer/deployer.go, internal/cmd/cli/deploy.go, internal/helmdeployer/deployer.go, internal/helmdeployer/history.go, internal/helmdeployer/install.go, internal/helmdeployer/rollback.go, internal/helmdeployer/template.go, pkg/apis/fleet.cattle.io/v1alpha1/bundledeployment_types.go
Previously `--dry-run` would output the list of resources and a deploy would output the resources struct, which contained the list of resources, too.
This also optimized Deployer.Deploy in the agent not to unpack (`objs, err := yaml.ToObjects`) the helm manifest needlessly.
=> Fleet deploy CLI always outputs list of deployed resources

integrationtests/gitjob/controller/controller_test.go
Backport of #2846 to `release/v0.10`.
Refers to #2829.
When a git job is created for a `GitRepo` with a configured CA bundle, integration tests now validate that a secret is created with the contents of that bundle and validate its contents against the `GitRepo` spec.
This also validates through integration tests that RBAC resources and the CA bundle secret are owned by their `GitRepo` and will therefore be deleted as soon as the `GitRepo` is.
Validation does not actually delete anything, due to a limitation [1] of the test framework.
[1]: https://book.kubebuilder.io/reference/envtest#testing-considerations
=> [v0.10] Add integration test checks for CA bundle secret

internal/cmd/controller/gitops/reconciler/gitjob_controller.go
In order to bootstrap cluster with fleet (to deploy CPI), we need gitjob to tolerate unitialized node taint
Refers to #2862
Backport of #2782.
=> [v0.10] Tolerate unitialized node taint

internal/helmdeployer/postrender.go, internal/helmdeployer/postrender_test.go
When `deleteCRDResources` was disabled (default), the `helm.sh/resource-policy` annotation was added to almost all resources instead of just to the CRDs as it was intended. The fix is to not change the shared `annotations` that also get added to other resources, but only modify a copy that's only used for one resource.
Refers to #2860
Backport of #2850.
=> [v0.10] Fix helm.sh/resource-policy being added to everything and not just CRDs

internal/cmd/controller/gitops/reconciler/gitjob_controller.go
This PR deletes retries in the gitops job created to call `gitCloner` + `fleet apply`. The user experience is affected because we need to wait for all the retries to finish before we can show up any possible error.
Jobs created are managed by the job controller in kubernetes, so we don't have control on the retry pods or when the job is finally considered as failed.
=> Deletes retries in the gitops job.

charts/fleet-crd/templates/crds.yaml, integrationtests/agent/adoption_test.go, integrationtests/agent/bundle_deployment_drift_test.go, integrationtests/agent/bundle_deployment_status_test.go, integrationtests/agent/helm_capabilities_test.go, integrationtests/agent/suite_test.go, internal/cmd/agent/deployer/monitor/updatestatus.go, internal/cmd/agent/operator.go, pkg/apis/fleet.cattle.io/v1alpha1/bundledeployment_types.go
When a resource of a BundleDeployment is removed after the Bundle has been created, the BundleDeployment says it is missing. This is also the case if the resource is not removed but changes its owner. In that case, the message of a resource that is missing might be misleading. These changes adapt the message to say "<resource> is not owned by us" instead of saying that the "\<resource\> is missing".
Part of #2134
=> BundleDeployment status error message improvement 

internal/cmd/agent/deployer/deployer.go, internal/cmd/cli/apply.go, internal/cmd/controller/gitops/operator.go, internal/cmd/controller/gitops/reconciler/gitjob_controller.go, internal/cmd/controller/reconciler/bundle_controller.go, internal/metrics/bundle_metrics.go, internal/metrics/bundledeployment_metrics.go, internal/metrics/metrics.go, pkg/apis/fleet.cattle.io/v1alpha1/gitrepo_types.go
=> [v0.10] Increase visibility of gitjob controller logs and events

internal/cmd/agent/deployer/deployer.go, internal/cmd/cli/apply.go, internal/cmd/controller/gitops/operator.go, internal/cmd/controller/gitops/reconciler/gitjob_controller.go, internal/cmd/controller/reconciler/bundle_controller.go, internal/metrics/bundle_metrics.go, internal/metrics/bundledeployment_metrics.go, internal/metrics/metrics.go, pkg/apis/fleet.cattle.io/v1alpha1/gitrepo_types.go
This adds the `fleet_` prefix to Kubernetes events generated by the `gitjob` controller, to clarify their context.
It also lowers verbosity of log messages indicating creation, deletion or reconciliation of `GitRepo`s, making them visible when debug logging is disabled.
=> Increase visibility of gitjob controller logs and events

charts/fleet/templates/job_cleanup_clusterregistrations.yaml, charts/fleet/templates/job_cleanup_gitrepojobs.yaml, charts/fleet/values.yaml, integrationtests/cli/cleanup/cleanup_clusterregistrations_test.go, integrationtests/cli/cleanup/cleanup_jobs_test.go, integrationtests/cli/cleanup/suite_test.go, internal/cmd/cli/cleanup.go, internal/cmd/cli/cleanup/cleanup.go
Refers to https://github.com/rancher/fleet/issues/2870
This is a workaround until the gitops controller removes jobs as needed in a future release.
After creating several commits in a git repo, observe there are many completed jobs. One per commit.
Change the new CronJob schedule to minutes: `* */1 * * *`, observe that all but the latest job are removed for each gitrepo .
=> Cleanup completed gitjobs

integrationtests/gitjob/controller/controller_test.go, internal/cmd/controller/gitops/reconciler/gitjob_controller.go
When no `caBundle` field is configured on a `GitRepo`, the gitOps controller now skips creation of the corresponding secret.
Refers to #2904.
=> Skip CA bundle secret creation with empty payload

integrationtests/gitjob/controller/controller_test.go, internal/cmd/controller/gitops/reconciler/gitjob_controller.go
When no `caBundle` field is configured on a `GitRepo`, the gitOps controller now skips creation of the corresponding secret.
Refers to #2922
Backport of #2918 to `release/v0.10`.
=> [v0.10] Skip CA bundle secret creation with empty payload

charts/fleet-crd/templates/crds.yaml, e2e/single-cluster/gitrepo_test.go, integrationtests/gitjob/controller/controller_test.go, internal/cmd/controller/gitops/reconciler/gitjob_controller.go, pkg/apis/fleet.cattle.io/v1alpha1/gitrepo_types.go, pkg/webhook/webhook.go, pkg/webhook/webhook_test.go
Changes the job handling so jobs are deleted after they succeed. Jobs are created when they are needed, this avoids having always a minimum of 1 job per gitrepo resource.
It also deletes the Owns(job) statement from the reconciler setup as we're already setting the controller reference when creating the job and the Owns statement makes extra reconciler calls that are not needed.
Backport of: https://github.com/rancher/fleet/pull/2903
Refers to https://github.com/rancher/fleet/issues/2931
=> [v0.10] Changes job handling in gitops controller

internal/cmd/controller/gitops/reconciler/gitjob_controller.go
Changes the way jobs are handled when `ForceSyncGeneration` or `Generation` change in the `GitRepo`.
It adds 2 new labels in the `job` with the actual values of `ForceSyncGeneration` and `Generation` in the `GitRepo`s spec. 
That way, if we encounter a race condition in which any of those 2 values are still not set in the database when a new reconcile is triggered, we can compare the value of the `job` against the expected generation values.
We would delete the job only when the values don't match.
=> Fix job deletion when generation is not updated on time

charts/fleet-crd/templates/crds.yaml, pkg/apis/fleet.cattle.io/v1alpha1/bundledeployment_types.go, pkg/apis/fleet.cattle.io/v1alpha1/gitrepo_types.go
I think they are not needed, yet they show up as empty in every resource 🤷
=> Remove empty fields from gitrepo/bd resources

integrationtests/agent/suite_test.go, internal/cmd/agent/controller/bundledeployment_controller.go, internal/cmd/agent/controller/drift_controller.go, internal/cmd/agent/deployer/driftdetect/driftdetect.go, internal/cmd/agent/deployer/normalizers/norm.go, internal/cmd/agent/operator.go, pkg/durations/durations.go
Refers to https://github.com/rancher/fleet/issues/2916
This adds a new reconciler, which reacts to a channel source, to remove
the bd update workaround. The driftdetect mini controller previously
signaled change via the bundledeployment's status to the
controller-runtime based reconciler.
The bundledeployment reconciler is now split into two, one
reconciler to install bundles and another to handle drift.
Both can update the status of the bundledeployment resource with the
current state of the deployment.
=> Remove update workaround from drift detection 

.github/workflows/e2e-test-fleet-in-rancher.yml, dev/README.md
That step uses a Github action which is no longer allowed in the Rancher org.
Refers to #1640
Follow-up to #2804.
=> Remove tmate step from Fleet-in-Rancher test workflow

charts/fleet/ci/debug-values.yaml, charts/fleet/templates/deployment.yaml, charts/fleet/templates/deployment_gitjob.yaml, charts/fleet/values.yaml
The securityContext needs to be disabled to allow for debugging with a debugger.
However it should be possible to run debug logs with security contexts enabled.
=> Add helm value to disable securityContext

internal/cmd/controller/reconciler/bundledeployment_controller.go
refers to SURE-9104
fleetcontroller was updating the whole status, instead of the changed fields.
=> Fix status conflict between agent and fleetcontroller

internal/cmd/agent/deployer/monitor/updatestatus.go
Code should not use context.Background.
Note: I wonder if we can somehow use `plan.Delete` to get rid of the extra `Get`.
=> Add missing context to agent's updatestatus

internal/cmd/controller/reconciler/bundledeployment_controller.go
Follow up to https://github.com/rancher/fleet/pull/2998
Accidentally changed when metrics are generated.
=> Bundledeployment controller does not write metrics on error

integrationtests/gitjob/controller/controller_test.go, internal/cmd/controller/gitops/reconciler/gitjob_controller.go
* Adds predicate when webhook commit changes
This adds a new predicate when the webhook commit is changed in the `GitRepo`. It also filters out `Job` events for creation/deletion, because they add extra reconcile loops that only increase the possibility of race conditions and that are not required.
The reconciler already knows when a `Job` is created/deleted because it is the owner and does not need to react upon those 2 events from the cluster.
Refers to: https://github.com/rancher/fleet/issues/2969
Refers to: https://github.com/rancher/fleet/issues/3003
=> [v0.10] Backport of Adds predicate when webhook commit changes

.github/workflows/e2e-test-fleet-in-rancher.yml, .github/workflows/release-against-test-charts.yml
Scheduling the workflow running end-to-end tests against Rancher would not work, as Rancher would be installed with an empty Fleet version setting, not find that Fleet version, and [time out](https://github.com/rancher/fleet/actions/runs/11480809015/job/31950035334).
Instead, this commit schedules the workflow releasing test charts for the head of `rancher/fleet`'s `main` branch, which then calls the test workflow with the right version, repo and branch parameters for Rancher to install those test charts.
Refers to #1640
Follow-up to #2804.
=> Schedule workflow releasing test charts

internal/cmd/controller/reconciler/bundle_controller.go, internal/manifest/store.go
I observed some log messages when the agents were down.
When two reconciles try to create the same content resource, one will error, however content resources are meant to be shared between bundles.
We also don't need to update the content for a finalizer, when no finalizer was added.
=> Avoid retries for bundle and content resources

internal/cmd/controller/gitops/reconciler/resourcekey.go, internal/cmd/controller/gitops/reconciler/resourcekey_test.go, internal/cmd/controller/gitops/reconciler/suite_test.go
Refers to https://github.com/rancher/dashboard/issues/11643
This is a hotfix to avoid a conflict with UI code, which multiplies the resources list per cluster. Multiplying a GitRepo's resources from all clusters with the number of clusters potentially freezes the UI.
With this PR `gitrepo.Status.Resources` reports resources only once, even if they are deployed to multiple clusters. If any cluster has a nonready/modified status for the resource, it is still added to the `PerClusterState` field. 
That means, it's no longer possible to tell if a resource was not deployed to a cluster, e.g. because it was excluded via helm chart values.
Future code needs to respect that some resources are not present in each bundledeployment.
Users can for example use targetCustomization to deploy resources …
=> GitRepo resources list doesn't list resources multiple times

internal/cmd/agent/controller/drift_controller.go
This prevents that new controller from making heavy-handed updates to bundle deployment statuses, reducing the risk of conflicts, as already done for the bundle deployment reconciler.
Follow-up to #3021
Refers to #3020
=> Patch bundle deployment status in drift controller

internal/cmd/controller/gitops/reconciler/status_controller.go
Refers to #3045
Addresses this warning seen when updating a `GitRepo`:
```
"Warning: Reconciler returned both a non-zero result and a non-nil error.
The result will always be ignored if the error is non-nil and the non-nil error causes 
reqeueuing with exponential backoff. For more details, 
see: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile#Reconciler"
```
=> Remove reconcile error from retry

internal/cmd/agent/deployer/deployer.go
When Helm, and hence Fleet, is unable to install a release, for instance to undo drift without force mode on a `Service`, this ensures that bundle deployment status resources will not be computed based on a failing Helm release.
That behaviour caused discrepancies between bundle and bundle deployment statuses, and eventually to bundles appearing as ready for drifting bundle deployments.
Tested manually with Rancher 2.9.3, using [this build](https://github.com/rancher/fleet/actions/runs/11613075014).
Refers to #2834
=> [v0.10] Skip install loop for invalid patches

.github/workflows/release-against-test-charts.yml
When releasing test Fleet charts, the test release workflow looks for the latest existing Fleet release, to use it as a base before making a few edits.
The previous logic used to find the latest available chart was buggy, in that it would list releases in alphabetical order, which could differ from semver. For instance, chart version `103.1.10+up0.9.11` would be listed between versions `103.1.0+up0.9.0` and `103.1.2+up0.9.2`.
Instead, this commit simplifies resolution by first looking at the `package.yaml` file, extracting the chart version from there and looking for the corresponding Fleet version in the charts repository. Resolution would then fail if no corresponding version is found in the repository, but that is far less likely to happen than with the previous logic and would …
=> Fix base Fleet chart version resolution for test release

.github/workflows/e2e-multicluster-ci.yml, .github/workflows/e2e-test-fleet-in-rancher.yml, .github/workflows/release-against-test-charts.yml, e2e/multi-cluster/not_matching_targets_delete_bd_test.go, e2e/multi-cluster/suite_test.go
Depending on the context in which multi-cluster end-to-end tests are
run, there may not be any registered downstream cluster called `second`,
reachable through context `k3d-managed-downstream`.
In such cases, such as when testing Fleet in Rancher the CI workflow
computes the name of the registered cluster and exports it as an
environment variable, for the tests to use instead of `second`.
To make the multi-cluster end-to-end test suite compatible between workflows, it no longer relies on context `k3d-managed-downstream`, labeling the cluster registered in non-managed mode instead to use it for label-based targeting.
This also takes the opportunity to use `dev-v2.10` as the new default `rancher/charts` base branch for Fleet charts, in line with the most recent releases.
Tested with [this …
=> Inject registered cluster name into multi-cluster tests

internal/cmd/controller/gitops/reconciler/gitjob_controller.go, internal/cmd/controller/gitops/reconciler/restrictions.go, internal/cmd/controller/gitops/reconciler/restrictions_test.go, internal/cmd/controller/gitops/reconciler/status_controller.go
Refers to https://github.com/rancher/fleet/issues/3077
The [gitreporestriction defaulting feature](https://fleet.rancher.io/namespaces#restricting-gitrepos) seems broken in 0.10 and 0.11.
This PR prevents a returned value from staying unused which, incidentally, made our linter complain.
=> Apply defaults from gitrepo restrictions

e2e/assets/single-cluster/namespaceLabels_targetCustomization.yaml, e2e/single-cluster/targetCustomization_test.go, internal/cmd/agent/deployer/deployer.go, internal/cmd/controller/agentmanagement/controllers/cluster/import.go, internal/cmd/controller/gitops/reconciler/gitjob_controller.go, internal/cmd/controller/gitops/reconciler/restrictions.go, internal/cmd/controller/gitops/reconciler/restrictions_test.go, internal/cmd/controller/reconciler/bundledeployment_controller.go
Refers to https://github.com/rancher/fleet/issues/3083
* Apply defaults from gitrepo restrictions
* Add unit tests covering defaults auth and assign
=> [v0.10] Fix apply defaults from gitrepo restriction

dev/README.md, dev/setup-k3d, dev/setup-single-cluster, e2e/assets/helm/repo/oci-with-auth/fleet.yaml, e2e/assets/helm/zot_configmap.yaml, e2e/assets/helm/zot_deployment.yaml, e2e/assets/helm/zot_service.yaml, e2e/single-cluster/imagescan_test.go, e2e/single-cluster/oci_registry_test.go, e2e/testenv/infra/cmd/setup.go, go.mod, go.sum
This PR changes some e2e environment files to be able to run e2e tests in systems in which we cannot access load balancers IPs from clusters.
This is specially intented to be able to execute the e2e tests locally in MAC OS systems in which docker IPs cannot be accessed.
* Get your IP address ( `localhost` or `127.0.0.1` is not valid. See [this](https://github.com/helm/helm/issues/11683#issuecomment-2183304555) )
* Export your IP with `export external_ip=YOUR_IP` or edit the dev/env.single-cluster-defaults file and add it there.
* Export the Git server URL with your ip (127.0.01 is also valid in this case).
`export CI_GIT_REPO_URL=http://YOUR_IP:8080` either in the the dev/env.single-cluster-defaults file or exporting before running
* Run e2e tests normally
Note: when running tests with …
=> Enables e2e tests using k3d services export to external ips

_typos.toml, e2e/testenv/infra/cmd/setup.go
It also adds `go.sum` to the list of excluded files for `typos` after `v1.28` was released
=> Deletes no longer valid comment in infra

.github/workflows/typos.yaml
Locks version of typos as version 1.28 requires extra changes
=> [v0.11] Locks typos to version 1.27.3

.github/workflows/typos.yaml
Locks version of typos as version 1.28 requires extra changes
=> [v0.10] Locks typos to version 1.27.3

.github/workflows/typos.yaml
Locks version of `typos` as version `1.28` requires extra changes
=> [v0.9] Locks typos to version 1.27.3

.github/workflows/e2e-rancher-upgrade-fleet-to-head-ci.yml
This prevents failures in CI job `rancher-fleet-integration` caused by cluster `second` not existing.
See runs [before](https://github.com/rancher/fleet/actions/runs/12222044318) vs [after](https://github.com/rancher/fleet/actions/runs/12235629253/job/34127316931).
=> Set registered cluster name before running Fleet tests

charts/fleet-agent/templates/deployment.yaml, charts/fleet-agent/values.yaml, charts/fleet/templates/deployment.yaml, charts/fleet/values.yaml, internal/cmd/agent/controller/bundledeployment_controller.go, internal/cmd/agent/controller/drift_controller.go, internal/cmd/agent/operator.go, internal/cmd/agent/root.go, internal/cmd/controller/operator.go, internal/cmd/controller/reconciler/cluster_controller.go, internal/cmd/controller/reconciler/clustergroup_controller.go, internal/cmd/controller/reconciler/imagescan_controller.go, internal/cmd/controller/root.go
This makes max concurrent reconciles configurable, through worker counts, for reconcilers which had hard-coded counts in the Fleet controller (ie cluster, cluster group and imagescan reconcilers), and for reconcilers living in the agent.
The same default value (`50`) is used everywhere, although different values could make more sense as defaults, eg. a lower value for the drfit reconciler.
Refers to #2915.
=> Make max concurrent reconciles configurable for agent and remaining controllers

.github/scripts/label-downstream-cluster.sh, dev/import-images-k3d, dev/setup-fleet-managed-downstream, dev/setup-k3ds, dev/setup-multi-cluster
Using the environment variable FLEET_E2E_DS_CLUSTER_COUNT, an arbitrary
amount of downstream clusters can be spawned, e.g.:
```
FLEET_E2E_DS_CLUSTER_COUNT=4 ./dev/setup-multi-cluster
```
This environment variable affects
- dev/setup-k3ds
- dev/import-images-k3d
- dev/setup-multi-cluster
=> dev-scripts: Spawn arbitrary amount of downstream clusters

charts/fleet-agent/templates/validate.yaml
This fixes error messages shown in case of namespace or release name mismatch.
=> Fix fleet-agent chart validation

dev/env.single-cluster-defaults, dev/setup-k3d, e2e/metrics/gitrepo_test.go, e2e/metrics/suite_test.go, e2e/single-cluster/oci_registry_test.go, e2e/testenv/githelper/git.go
It also deletes the HELM_PATH env variable as it is no longer used.
Fixes errors in metrics tests when the test is trying to check for metrics when the service exporting them it's still not fully up.
Adds a custom file to add extra env variables (This was added so the `dev/env.single-cluster-defaults` is not changed and to avoid pushing changes to it by mistake)  
Adds an extra check in OCI e2 tests to verify that the `CI_OCI_USERNAME` and `CI_OCI_PASSWORD` are set.
Deletes the `CI_GIT_REPO_URL` env variable and uses the already existing `external_ip`.
1. Create a file with your custom environment
```bash
export external_ip=192.168.1.47
export METRICS_CONTROLLER_PORT=8083
export METRICS_GITJOB_PORT=8084
```
2. Setup the cluster
```bash
export CUSTOM_ENV_FILE=PATH_TO_YOUR_CUSTOM_ENV
source …
```
=> Exports Metrics URLs to test with external IPs

charts/fleet-agent/templates/deployment.yaml, charts/fleet-agent/values.yaml, charts/fleet/templates/configmap.yaml, charts/fleet/templates/deployment.yaml, charts/fleet/values.yaml, internal/cmd/agent/controller/bundledeployment_controller.go, internal/cmd/agent/controller/drift_controller.go, internal/cmd/agent/operator.go, internal/cmd/agent/root.go, internal/cmd/controller/agentmanagement/agent/agent.go, internal/cmd/controller/agentmanagement/agent/manifest.go, internal/cmd/controller/agentmanagement/controllers/cluster/import.go, internal/cmd/controller/agentmanagement/controllers/manageagent/manageagent.go, internal/cmd/controller/operator.go, internal/cmd/controller/reconciler/cluster_controller.go, internal/cmd/controller/reconciler/clustergroup_controller.go, internal/cmd/controller/reconciler/imagescan_controller.go, internal/cmd/controller/root.go, internal/config/config.go
Backport of #3094 and #3152 to v0.11.
Refers to #3121.
=> [v0.11] Make agent worker counts configurable

dev/README.md, dev/setup-k3d, dev/setup-k3ds-downstream, dev/setup-multi-cluster, dev/setup-single-cluster
* support PORT_OFFSET for upstream in both, to avoid conflicts with host ports
* for simplicity downstreams always have a number in their name
The `setup-k3d` script exposes four kinds of ports:
- API server port
- tls port
- service ports
- optional: metric ports
=> Separate k3d dev scripts for upstream/downstream

internal/cmd/controller/gitops/reconciler/gitjob_controller.go
Refers to: https://github.com/rancher/fleet/issues/3161
Backport of: https://github.com/rancher/fleet/pull/3182
=> [v0.11] Adds logs for new commit or error checking for the latest

e2e/assets/status/chart-with-template-vars/Chart.yaml, e2e/assets/status/chart-with-template-vars/fleet.yaml, e2e/assets/status/chart-with-template-vars/templates/configmap.yaml, e2e/assets/status/gitrepo.yaml, e2e/single-cluster/gitrepo_test.go, e2e/single-cluster/status_test.go, internal/cmd/controller/gitops/reconciler/status_controller.go, internal/cmd/controller/reconciler/bundle_controller.go
When fleet.yaml is evaluated for targeting, errors can occur due to missing values, like for instance, if a cluster has a missing label that is used in the fleet.yaml file.
Those kind of errors would previously only be visible in logs. This PR introduces error messages in the bundle, more specifically in the Ready condition of the Bundle status, when errors occur on rendering the templates for targeting. Subsequently the error message is being copied from the Bundle to the GitRepo. It will not show up in Clusters or ClusterGroups.
It is new that Bundles will have their own errors. Errors are commonly created in BundleDeployments and are aggregated in the status of Bundle. Now, additionally, the bundle itself may have errors that result in a status change. Those errors will take precedence …
=> [SURE-9137] Add template errors to bundle and gitrepo status

charts/fleet/templates/deployment_gitjob.yaml, charts/fleet/values.yaml, internal/cmd/agent/controller/bundledeployment_controller.go, internal/cmd/controller/gitops/operator.go, internal/cmd/controller/gitops/reconciler/gitjob_controller.go, internal/cmd/controller/gitops/reconciler/predicate.go, internal/cmd/controller/helmops/reconciler/helmapp_controller.go, internal/cmd/controller/reconciler/config_controller.go, internal/cmd/controller/reconciler/imagescan_controller.go
refers to https://github.com/rancher/fleet/issues/3138
* Add jitter to the pollingInterval of GitRepos, jitter is plus minus 1/10 the polling interval
* Gitops controller resyncs every hour, if gitrepos are lost from requeueAfter polling, resync should add them again.
* Since the 10h cache sync is an update event, change predicates like GenerationChanged, prevent the reconcile from running.
=> Add jitter and resync to polling

e2e/assets/status/chart-with-template-vars/Chart.yaml, e2e/assets/status/chart-with-template-vars/fleet.yaml, e2e/assets/status/chart-with-template-vars/templates/configmap.yaml, e2e/assets/status/gitrepo.yaml, e2e/single-cluster/gitrepo_test.go, e2e/single-cluster/status_test.go, internal/cmd/controller/gitops/reconciler/gitjob_controller.go, internal/cmd/controller/reconciler/bundle_controller.go
* Import v1alpha1 package as fleet
* Show bundle errors in Bundle and GitRepo
Refers to #2943
* Add E2E tests
Refers to #2943
(cherry picked from commit 235e8efa1e857fc482ddafc7b415ec760b343d24) (cherry picked from commit 34170715e2947a413c0d51fae3da6c525f2c0257)
Refers to #3191
=> [backport v2.9] [SURE-9137] Add template errors to bundle and gitrepo status

.github/workflows/ci.yml, .github/workflows/release-fleet.yml, .golangci.json, benchmarks/assets/create-1-bundle/bundle.yaml, benchmarks/assets/create-1-bundledeployment-10-resources/bundle.yaml, benchmarks/assets/create-1-gitrepo-1-big-bundle/gitrepo.yaml, benchmarks/assets/create-1-gitrepo-1-bundle/gitrepo.yaml, benchmarks/assets/create-1-gitrepo-50-bundle/gitrepo.yaml, benchmarks/assets/create-50-bundle/bundles.yaml, benchmarks/assets/create-50-gitrepo-50-bundle/gitrepos.yaml, benchmarks/deploy_test.go, benchmarks/gitrepo_bundle_test.go, benchmarks/record/record.go, benchmarks/report/report.go, benchmarks/suite_test.go, benchmarks/targeting_test.go, dev/benchmarks.sh, go.mod, go.sum
* add benchmarks
* add test data
* experiments use group label instead of repo-name label w fleet 0.9.11
* add toggle for metrics
* script uses stable benchmark order via --seed
* check for at least one cluster
* skip confusing report table printing as we don't use sampling
TODO
=> Add benchmark suite

.github/scripts/register-downstream-clusters.sh, dev/README.md, dev/env.multi-cluster-defaults, dev/import-images-k3d, dev/remove-fleet, dev/setup-fleet-downstream, dev/setup-k3d, dev/setup-rancher-clusters, dev/setup-rancher-with-dev-fleet
* use same docker network for upstream/downstream
* switch all defaults to "downstream1"
* dev/setup-rancher-with-dev-fleet idempotency
=> Dev scripts use same docker network 

benchmarks/deploy_test.go, benchmarks/report/report.go
Refers to https://github.com/rancher/fleet/issues/3217
=> Add TotalDuration to benchmark report

dev/setup-k3d, e2e/metrics/suite_test.go
This is added to be able to define the port used when setting up the metrics service for helmops Helps also to be able to run e2e tests in conjunction with an external ip (and to run e2e test on Mac OS)
=> [CI/e2e] Adds definition of helmops metrics port

.github/workflows/release-fleet.yml
to be able to test newer implemenations without merging them before.
=> Add manual trigger to Fleet release action

internal/cmd/controller/gitops/reconciler/gitjob_controller.go
Changes the gitops reconciler result to always have the polling interval in RequeueAfter. This way we take advantage of the fact that if there is already an event in the RequeueAfter queue the next ones will be dropped and we won't miss the polling cycle if there is a race condition between RequeueAfter events and any other event in the reconciler.
This is only added when `DisablePolling` is not set.
Refers to https://github.com/rancher/fleet/issues/3138
=> [v0.10] - Always returns result with RequeueAfter set

internal/cmd/agent/controller/bundledeployment_controller.go, internal/cmd/controller/reconciler/bundle_controller.go
Refers to #3253
Backport of #3245
=> [v0.10] Prevent empty Patch updates

internal/resourcestatus/resourcekey.go, internal/resourcestatus/resourcekey_test.go
Refers to #3186
This PR concludes the work started on #3203 and #3209, by refactoring how the `status.resources` (and especially `perClusterState`) are calculated.
The goal of this refactor is to keep all the information accessible, while still producing the same opinionated representation. This will allow to later change the format in an easier way, or adding new fields from the same information (e.g. `PerClusterResources`).
=> Rework how resources are calculated

charts/fleet/templates/job_cleanup_clusterregistrations.yaml, charts/fleet/templates/job_cleanup_gitrepojobs.yaml
This fixes a bug which would prevent jobs from running on a cluster where all nodes are tainted, leading to failures to install Fleet charts.
Refers to #3280
=> Propagate tolerations from values to jobs

charts/fleet/templates/job_cleanup_clusterregistrations.yaml, charts/fleet/templates/job_cleanup_gitrepojobs.yaml
This fixes a bug which would prevent jobs from running on a cluster where all nodes are tainted, leading to failures to install Fleet charts.
Refers to #3180.
=> [v0.11] Propagate tolerations from values to jobs

internal/cmd/controller/gitops/reconciler/status_controller.go, internal/cmd/controller/helmops/reconciler/helmapp_status.go, internal/cmd/controller/reconciler/cluster_controller.go, internal/resourcestatus/resourcekey.go, internal/resourcestatus/resourcekey_test.go
Refers to #3186
Also, changes `fromResources` to order BundleDeployments before processing instead of sorting the resulting resources, which should be more efficient while producing the same result.
=> Small refactor for setting resource statuses

charts/fleet-crd/templates/crds.yaml, internal/cmd/controller/options/calculate.go, internal/cmd/controller/target/builder.go, internal/cmd/controller/target/target_test.go, pkg/apis/fleet.cattle.io/v1alpha1/bundledeployment_types.go, pkg/apis/fleet.cattle.io/v1alpha1/zz_generated.deepcopy.go
Refers to #3266 
Implement new field inside `Helm` options: `templateValues`, which performs templating of each individual value before converting data to yaml. This allows to use more complex template expressions then currently available to template string data, like creation of maps and lists.
=> Add `templateValues` to HelmApp, Bundle, etc

dev/remove-fleet
This allows our dev scripts to uninstall and reinstall Fleet multiple times in a row without hanging.
=> Remove finalizers on contents when uninstalling Fleet

.github/workflows/e2e-nightly-ci.yml, e2e/single-cluster/oci_registry_test.go
This aligns runner specs with the regular end-to-end tests CI workflow, which runs against pull requests.
It may fix end-to-end test failures which, while not related to sharding, only happen with sharding enabled.
Refers to #3215
=> Increase runner CPUs for nightly CI workflow

internal/cmd/controller/gitops/reconciler/gitjob_controller.go
This is a port to main of the RequeueAfter fix already merged in 0.9 and 0.10 
Refers to https://github.com/rancher/fleet/issues/3252
=> Always returns result with RequeueAfter set

internal/cmd/controller/imagescan/gitcommit_job.go, pkg/apis/fleet.cattle.io/v1alpha1/gitrepo_types.go, pkg/apis/fleet.cattle.io/v1alpha1/zz_generated.deepcopy.go
As ImageScanCommit is an optional field inside the GitRepo spec this PR changes it to be a pointer.
Not doing so means that the veru first time the `GitRepo` is stored in the cluster default values will be created and generation will be incresed, which means a double polling for the `GitRepo` when it is created.
The first time the `GitRepo` is polled because the `LastPollingTime` is not set. The second time it is polled because of the generation change mentioned above.
Aside from double polling in a short period of time this PR also tries to prevent an extra reconciler call that is not needed.
Backport of https://github.com/rancher/fleet/pull/3302
=> [v0.11] - Change ImageScanCommit in GitRepo spec to a pointer (#3302)

e2e/single-cluster/sharding_test.go, integrationtests/agent/assets/deployment-v1.yaml, integrationtests/agent/bundle_deployment_drift_test.go, integrationtests/agent/bundle_deployment_status_test.go, integrationtests/agent/suite_test.go
After applying ginkgolinter fixes, several tests failed. Some tests where not effective, as they were missing `Should(Succeed())`.
This fixes test expectations and relaxes some tests.
It seems `UpdateStatus` sometimes overwrites the Ready error message or resets the conditions. The  error appears in either Ready or Deployed as "modified" or "cannot patch".
=> Fix integrationtest for drift correction

internal/cmd/agent/controller/bundledeployment_controller.go, internal/cmd/agent/deployer/monitor/updatestatus.go, internal/cmd/controller/reconciler/bundle_controller.go, pkg/apis/fleet.cattle.io/v1alpha1/bundle_types.go
Noticed while reading logs. Also makes bundledeployment creation logging visible at INFO.
```
// fleet-controller-686cbf94bb-7zbnm fleet-controller 2025-02-05T17:16:04Z	ERROR	bundle	Reconcile failed to add content finalizer	{"controller": "bundle", "controllerGroup": "fleet.cattle.io", "controllerKind": "Bundle", "Bundle": {"name":"bm-1-gitrepo-1-bundle-benchmarks-create-1-gitre-773b4","namespace":"fleet-local"}, "namespace": "fleet-local", "name": "bm-1-gitrepo-1-bundle-benchmarks-create-1-gitre-773b4", "reconcileID": "9a95535b-199b-4478-b77b-fa5fae945a93", "gitrepo": "bm-1-gitrepo-1-bundle", "commit": "faca22290f9659e491e9a329ab3f23e6c9681139", "content ID": "s-bacd6eda76a6e0fef955f1656ac4d4bab9e0027580f1865a36689f71ae75a", "error": "resource name may not be empty"}
```
=> Retry reconcile when we cannot add finalizer to content resource

integrationtests/agent/assets/deployment-v1.yaml, integrationtests/agent/bundle_deployment_diffs_test.go, integrationtests/agent/bundle_deployment_drift_test.go, integrationtests/agent/suite_test.go, internal/cmd/agent/controller/drift_controller.go
The test for switching on forced drift correction after a failed drift correction attempt is flaky.
=> Add logging around drift correction and disable test

integrationtests/gitjob/git/git_test.go
The issue seems to be specific to Ubuntu (or possibly other Linux distributions) as I have had it for both my Ubuntu machines.
Fixes
```
--- FAIL: TestLatestCommitSSH (4.68s)
git_test.go:272: 
Error Trace:    /home/user/src/fleet/integrationtests/gitjob/git/git_test.go:272
Error:          Received unexpected error:
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
Test:           TestLatestCommitSSH
--- FAIL: TestLatestCommitSSH/private_repo_without_known_hosts (0.04s)
testing.go:1679: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
```
=> Fix integration test issue with git tests

internal/resourcestatus/resourcekey.go
Follow up to #3209
Found while testing https://github.com/rancher/dashboard/pull/13244
#3209 changed the default state for resources from the Bundle summary state to use the BundleDeployment, but I didn't take into account that this is sometimes calculated from the resource states (when it's not `WaitApplied` or `ErrApplied`).
This change prevents that, and provides resources with correct default state assumptions.
=> Fix default state for GitRepo resources

pkg/webhook/webhook.go, pkg/webhook/webhook_test.go
Updating the status sub resource, does not update the spec.
=> Using a webhook sets the intervall to one hour again

.github/scripts/create-secrets.sh, .github/scripts/create-zot-certs.sh, .github/workflows/e2e-ci.yml, .github/workflows/e2e-nightly-ci.yml, dev/create-secrets, dev/setup-multi-cluster, dev/setup-single-cluster, e2e/assets/gitrepo/nginx_deployment.yaml, e2e/assets/gitrepo/nginx_git.conf, e2e/assets/gitrepo/nginx_service.yaml, e2e/single-cluster/gitrepo_test.go, e2e/single-cluster/helm_auth_test.go, e2e/testenv/githelper/git.go, integrationtests/gitjob/controller/controller_test.go, integrationtests/gitjob/controller/suite_test.go, integrationtests/gitjob/git/git_test.go, internal/cmd/controller/gitops/reconciler/gitjob_controller.go, internal/cmd/controller/gitops/reconciler/gitjob_test.go, pkg/cert/cabundle.go, pkg/cert/cabundle_test.go, pkg/git/fetch.go, pkg/git/fetch_test.go
This enables Fleet to rely on Rancher-configured CA bundle [secrets](https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/installation-references/helm-chart-options#additional-trusted-cas) in the following clients:
* git remote lister and cloner: those CA bundles no longer need to be provided in a `GitRepo`'s spec. Fleet will extract CA bundle data from Rancher secrets if (and only if) no CA bundle is provided for a `GitRepo`.
* Helm client: Fleet will extract, populate and mount Rancher CA bundles in the following cases:
* no `HelmSecretName` nor `HelmSecretNameForPaths` secret is provided on a `GitRepo`
* one of those secrets is provided, but only specifies username(s) and password(s), without a CA bundle
This is tested through a combination of:
* unit tests …
=> Fall back to Rancher-configured CA bundles

integrationtests/cli/apply/helm_test.go, internal/bundlereader/resources.go
Error example (using the provided git repository)
```bash
time="2025-02-18T10:37:59+01:00" level=fatal msg="repo=https://charts.rancher.io chart=rancher-monitoring-crds version=104.1.2+up57.0.3: no chart name found"
```
Refers to: https://github.com/rancher/fleet/issues/3160
=> Add extra error info when downloading remote charts

charts/fleet/templates/rbac.yaml, charts/fleet/templates/rbac_gitjob.yaml, integrationtests/gitjob/controller/suite_test.go, internal/cmd/controller/agentmanagement/controllers/bootstrap/bootstrap.go, internal/cmd/controller/agentmanagement/controllers/controllers.go, internal/cmd/controller/gitops/operator.go, internal/cmd/controller/gitops/reconciler/gitjob_controller.go, internal/cmd/controller/gitops/reconciler/gitjob_test.go
Adding the toleration needed to the helm chart in Fleet is not enough when running the agent and the fleet apply job.
This PR adds the tolerations found in the `fleet-controller` deployment to the agent and to the fleet apply job.
Refers to: https://github.com/rancher/fleet/issues/3313
=> Adds tolerations from fleet-controller Deployment

integrationtests/cli/apply/helm_test.go, internal/bundlereader/read.go, internal/bundlereader/resources.go, internal/cmd/cli/apply.go, internal/cmd/cli/apply/apply.go, internal/cmd/cli/gitcloner/cloner.go, internal/cmd/cli/gitcloner/cloner_test.go, internal/cmd/controller/gitops/reconciler/gitjob_controller.go, internal/cmd/controller/gitops/reconciler/gitjob_test.go
Adds context to message in fleet apply. Specially to those running inside loops.
For example, when loading directories, remote charts, etc...
Contexts are wrapped in top of the previous one.
It also fixes the `gitjob` init container to use `log.sh` and redirect the errors to `/dev/termination-log` 
Related to: https://github.com/rancher/fleet/issues/3234
=> Adds message context to fleet apply errors

.github/scripts/deploy-fleet.sh, .github/scripts/upgrade-rancher-fleet-to-dev-fleet.sh, charts/fleet-agent/templates/deployment.yaml, charts/fleet-agent/templates/service.yaml, charts/fleet-agent/values.yaml, dev/setup-fleet, e2e/installation/verify_test.go, e2e/multi-cluster/installation/agent_test.go, e2e/multi-cluster/installation/suite_test.go, internal/cmd/agent/clusterstatus.go, internal/cmd/agent/register.go, internal/cmd/agent/root.go, internal/cmd/controller/agentmanagement/agent/manifest.go, internal/cmd/controller/agentmanagement/agent/manifest_test.go
=> Switch agent from StatefulSet to Deployment (SURE-9419)

internal/cmd/cli/apply.go, internal/cmd/controller/gitops/reconciler/gitjob_controller.go, internal/cmd/controller/gitops/reconciler/gitjob_test.go, pkg/webhook/webhook.go, pkg/webhook/webhook_test.go
Adds a retry mechanism to `fleet apply` after observing several errors due to conflicts under high loads. As the job created is not retrying by itself the `GitRepo` gets hung.
Also changes from 1 Status Update and Patch to one single patch in the webhook handling to mitigate conflicts and possible race conditions.
Refers to: https://github.com/rancher/fleet/issues/3067
=> Retries in fleet apply and single patch in webhook

e2e/single-cluster/helm_verify_test.go, e2e/single-cluster/single_cluster_test.go, integrationtests/cli/apply/apply_online_test.go, integrationtests/cli/apply/apply_test.go, integrationtests/cli/apply/helm_test.go, integrationtests/cli/assets/labels_update/cm.yaml, integrationtests/cli/assets/nested_mixed_two_levels/nested/deploymentC/cm.yaml, integrationtests/cli/assets/targets/override/cm.yaml, integrationtests/cli/assets/targets/simple/cm.yaml, internal/bundlereader/helm.go, internal/bundlereader/loaddirectory.go, internal/bundlereader/loaddirectory_test.go, internal/bundlereader/resources.go, internal/cmd/controller/agentmanagement/agent/agent.go, internal/cmd/controller/agentmanagement/controllers/cluster/import.go, internal/cmd/controller/agentmanagement/controllers/manageagent/manageagent.go, internal/cmd/controller/reconciler/bundle_controller.go, internal/ociwrapper/ociwrapper_test.go
Fleet apply has several "config" files inside of a bundle, like "fleet.yaml". After running "fleet apply" these files are not needed anymore and there is no reason to add them to the `Bundle.Spec.Resources` list.
=> Remove "fleet apply" config files from bundle resources

integrationtests/agent/bundle_deployment_drift_test.go, integrationtests/agent/bundle_deployment_status_test.go
This ensures that bundle deployments are only created as often as necessary. It replaces `It` blocks, which would call the whole setup logic again, creating a new bundle deployment, with `By` statements illustrating mere steps of a testing context.
Logic under test is not affected; this is merely an optimisation of test drivers.
Example result on my machine:
* Before:
```                                                                                
Running Suite: Fleet Suite - /home/tan/Dev/fleet3/integrationtests/agent
========================================================================                                                                
Random Seed: 1741096567 …
```
=> Refactor bundle deployment status integration tests

integrationtests/gitjob/controller/gitrepo_test.go
The test already checks for meaningful status fields and `ResourceVersion` is part of the kubernetes engine. The test is flaky because the value of the original `ResourceVersion` could be already updated when it reads it.
=> Don't check for ResourceVersion on Status tests

charts/fleet/templates/rbac.yaml
Fixes
```
│ fleet-agentmanagement E0304 16:38:51.311219       1 reflector.go:166] "Unhandled Error" err="pkg/mod/k8s.io/client-go@v0.32.1/tools/cache/reflector.go:251: Failed to watch *v1.Deployment: deployments.apps is forbidden: User \"system:serviceaccount:catt │
│ le-fleet-system:fleet-controller\" cannot watch resource \"deployments\" in API group \"apps\" at the cluster scope" logger="UnhandledError"                                                                                                                 │
```
Fix-up for #3313
=> Add missing verb to RBAC

charts/fleet-agent/templates/deployment.yaml, e2e/multi-cluster/installation/agent_test.go, internal/cmd/agent/operator.go, internal/cmd/agent/register.go, internal/cmd/agent/root.go, internal/cmd/controller/agentmanagement/agent/manifest.go
Since we have changed the agent from using a StatefulSet to a Deployment, we also needed and have implemented leader election for every container of the agent pod. This ensures that
- only  one cluster registration is created at a time from one downstream cluster,
- one agent is running on a downstream cluster at a time and
- one container is updating the status at at time,
even if the replicas are temporarily (as in a rollout) or permanently (as in replica size) above one.
Now, if replicas are to be set to anything above one, this will currently lead to the agent of the second pod to perform the cluster registration, even though the agent cannot run after it completed the registration. The cluster registration will complete, but the controller will wait for the lease. This state …
=> [SURE-9419] Move agent registration into controller container

e2e/require-secrets/gitrepo_test.go, internal/cmd/cli/gitcloner/cloner.go, internal/cmd/cli/gitcloner/cloner_test.go, pkg/git-urls/urls_test.go, pkg/git/remote.go
Improve error messages when handling "scp-style" Git URLs: https://github.com/rancher/fleet/issues/2495 
*  ssh/scp style URLs only work when clientSecretName is used
* cloner (job) works with scp-style URLs
* fetcher (controller) works with scp-style URLs*
* made error messages in cloner more distinct
Note: The new require-secrets e2e tests needs `GIT_REPO_URL` to contain a scp-style URL, like `git@gitrepo.host:path`. Other e2e tests cannot be used, since our server runs on a non-standard port and "scp" syntax doesn't support ports...
(Updated description after comments)
=> Update gitcloner/fetcher error messages for SCP/SSH GitRepo URLs

.github/scripts/create-secrets.sh, .github/scripts/create-zot-certs.sh, .github/workflows/e2e-ci.yml, .github/workflows/e2e-nightly-ci.yml, dev/README.md, dev/create-secrets, dev/create-zot-certs, dev/setup-cluster-config, dev/setup-multi-cluster, dev/setup-single-cluster, e2e/assets/helm/repo/http-with-auth-chart-path/fleet.yaml, e2e/assets/helm/repo/http-with-auth-repo-path/fleet.yaml, e2e/assets/helm/repo/oci-with-auth/fleet.yaml, e2e/single-cluster/gitrepo_polling_disabled_test.go, e2e/single-cluster/gitrepo_test.go, e2e/single-cluster/helm_auth_test.go, e2e/single-cluster/helm_dependencies_test.go, e2e/single-cluster/imagescan_test.go, e2e/single-cluster/oci_registry_test.go, e2e/single-cluster/release_cleanup_test.go, e2e/single-cluster/status_test.go, e2e/single-cluster/suite_test.go, e2e/testenv/githelper/git.go, e2e/testenv/infra/cmd/setup.go, e2e/testenv/infra/cmd/teardown.go, e2e/testenv/zothelper/zothelper.go
The new namespace is default, so services are no longer started in the workspaces used for the tests.
This also makes sure, single-cluster tests run in "fleet-local", as their gitrepo resources use the default target.
=> Change namespace for dev infrastructure

dev/setup-single-cluster, e2e/single-cluster/helm_options_test.go, e2e/single-cluster/release_cleanup_test.go, e2e/single-cluster/status_test.go
This improves a couple of points to speed up running end-to-end tests:
* `dev/setup-single-cluster` supports a `--reuse` flag to reuse an existing cluster and uninstall Fleet from it, instead of deleting and re-creating the cluster
* redundant `It` blocks test cases are replaced with `By` statements to enable common setup logic to be run only as many times as necessary
=> Slightly speed up end-to-end test runs 

charts/fleet-crd/templates/crds.yaml, internal/cmd/controller/agentmanagement/controllers/cluster/import.go, pkg/apis/fleet.cattle.io/v1alpha1/cluster_types.go
even though the agent is not a statefulset anymore, but the user could be upgrading from an older fleet version.
Refers to https://github.com/rancher/rancher/issues/49428
=> Delete both, statefulset and deployment on agent update

.github/pull_request_template.md
As discussed in the retrospective, this pull request updates the pull request template to remind contributor to add documentation
=> docs:  remind to add documentation

e2e/single-cluster/helm_auth_test.go, internal/cmd/controller/gitops/reconciler/gitjob_controller.go
This fixes a bug whereby, once a `GitRepo` had been created, subsequent reconciles would not detect a Rancher secret as the source of CA bundle data.
Relevant information for the controller is whether a secret created in the `GitRepo`'s namespace, duplicating a Rancher CA bundle secret, _exists_, not whether it was created or updated.
Refers to #2750.
Follow-up to #3233.
=> Fix Rancher CA bundle mount after GitRepo update

e2e/multi-cluster/installation/suite_test.go
as it appears to be unnecessary.
Unfortunately, those changes seem to cause many issues in the `AfterSuite` code path when the tests have actually succeeded. This will fix test issues we have in `e2e-fleet-mc-test`.
IIRC, those adaptations were necessary for having leader election in every of the three containers of the pod, but now we have a single container in the pod. I was not able to verify that this produces less issues in general, but it will remove the issues we have repeatedly seen recently, since the error occurs in the code removed, which was added by me and just in for a few weeks. When I adapted that test, it fixed the original, but now the original works without this addition.
Refers to #XXX
=> Remove fix for agent redeployment

.github/pull_request_template.md
Follow-up to #3448.
The sources for the Fleet documentation website [2] live in `rancher/fleet-docs` [1].
[1]: https://github.com/rancher/fleet-docs
[2]: https://fleet.rancher.io/
=> Fix docs link in PR template

internal/cmd/controller/gitops/reconciler/status_controller.go
Refers to #3484
Adding a sort by UID for the bundle list, so the same bundle is selected to update the non ready state. 
This only makes sure that the same bundle is always selected. But it still picks one (as long as it is the first and in non ready state). 
A follow-up could aggregate all the non-ready bundles on the message.
And also avoid overiding the status condition previously set at: https://github.com/rancher/fleet/blob/main/internal/cmd/controller/gitops/reconciler/status_controller.go#L159
=> Ensure same bundle is selected for non-ready status

internal/cmd/controller/gitops/reconciler/status_controller.go
Backport of https://github.com/rancher/fleet/pull/3485
Refers to https://github.com/rancher/fleet/issues/3488
=> [v0.12] Ensure same bundle is selected for non-ready status 

charts/fleet-crd/templates/crds.yaml, pkg/apis/fleet.cattle.io/v1alpha1/gitrepo_types.go, pkg/webhook/parser.go, pkg/webhook/parser_test.go, pkg/webhook/webhook.go, pkg/webhook/webhook_test.go
This PR changes the secret handling for webhooks in order to add the possibility to define a secret per `GitRepo`. The actual `main` code has a single global secret shared by all the possible `GitRepos` in the system, which forces the users to share the same secret for all their webhooks in the cluster.
The secret is also cached, which means that it listens to the informer cache for all secrets in the cluster and, if any secret is updated it checks if it's the global secret for webhooks. In that case it reinstantiates all the webhook parsers for all the supported providers with the new secret value (or none if the secret was deleted).
It also needs to instantiate the webhook parsers for all supported providers at the beginning.
Also... a bug was found in that secret caching. If all the …
=> New webhook secret handling

integrationtests/controller/bundle/bundle_targets_test.go, integrationtests/gitjob/controller/suite_test.go, integrationtests/helmops/controller/suite_test.go, internal/cmd/controller/finalize/finalize.go, internal/cmd/controller/reconciler/bundle_controller.go, internal/cmd/controller/reconciler/bundledeployment_controller.go
Also changes/improves how the finalizers are handled, both for Bundles and BundleDeployments.
Refers to #3437
`BundleDeployments` are only being deleted on the `Cluster` reconciler, which can take considerable time to run and cause confusion in the status of resources.
Note: this PR was superseded by #3509 while still on review. However, I believe this implementation is cleaner, so some of the changes there are being replaced.
=> Prune BundleDeployments when GitRepo/Bundle targets change

.github/workflows/e2e-test-fleet-in-rancher.yml
This prevents CI failures such as [this one](https://github.com/rancher/fleet/actions/runs/14310039929/job/40102823796).
=> Wait for webhook deployment before testing Fleet in Rancher

pkg/git/fetch.go, pkg/git/fetch_test.go
This fixes a panic happening when the following conditions are met:
* strict host key checks are disabled
* `known_hosts` entries are found
* no secret exists, neither referenced through a `GitRepo`'s nor a `gitcredential` secret
In that case, emptying a secret's `data` field does not make sense, and would indeed lead to a panic. This commit ensures that said field is only emptied if doing so is needed and safe.
Forward-port of #3539 to `main`.
Follow-up to #3523.
=> Prevent panic when fetching latest commit

pkg/git/fetch.go, pkg/git/fetch_test.go
This fixes a panic happening when the following conditions are met:
* strict host key checks are disabled
* `known_hosts` entries are found
* no secret exists, neither referenced through a `GitRepo`'s nor a `gitcredential` secret
In that case, emptying a secret's `data` field does not make sense, and would indeed lead to a panic. This commit ensures that said field is only emptied if doing so is needed and safe.
Refers to #3537
Follow-up to #3524.
=> [v0.12] Prevent panic when fetching latest commit

pkg/git/fetch.go, pkg/git/fetch_test.go
This fixes a panic happening when the following conditions are met:
* strict host key checks are disabled
* `known_hosts` entries are found
* no secret exists, neither referenced through a `GitRepo`'s nor a `gitcredential` secret
In that case, emptying a secret's `data` field does not make sense, and would indeed lead to a panic. This commit ensures that said field is only emptied if doing so is needed and safe.
Backport of #3539 to v0.11.
Follow-up to #3525.
=> [v0.11] Prevent panic when fetching latest commit

pkg/git/fetch.go, pkg/git/fetch_test.go
This fixes a panic happening when the following conditions are met:
* strict host key checks are disabled
* `known_hosts` entries are found
* no secret exists, neither referenced through a `GitRepo`'s nor a `gitcredential` secret
In that case, emptying a secret's `data` field does not make sense, and would indeed lead to a panic. This commit ensures that said field is only emptied if doing so is needed and safe.
Backport of #3539 to v0.10
Follow-up to #3526.
=> [v0.10] Prevent panic when fetching latest commit

.github/workflows/ci.yml, charts/fleet/templates/deployment.yaml, charts/fleet/templates/deployment_gitjob.yaml, charts/fleet/templates/deployment_helmops.yaml, charts/fleet/tests/extraAnnotations_test.yaml, charts/fleet/tests/extraLabels_test.yaml, charts/fleet/values.yaml
Adds the `extraLabels` and `extraAnnotations` values to the helm charts. Those values are propagated to the `fleet-controller`, `gitjob` and `helmops` deployments.
It also introduces helm charts unittests testing those 2 new values.
Refers to https://github.com/rancher/fleet/issues/3295
=> Adds extra labels and annotations in charts

.github/workflows/ci.yml
Apart from being unnecessary, it would [fail](https://github.com/rancher/fleet/actions/runs/14443816068/job/40499715676?pr=3551) when trying to install an already installed Helm plugin.
=> Remove duplicated Helm unit tests step

internal/cmd/controller/agentmanagement/controllers/cluster/import.go, internal/cmd/controller/agentmanagement/controllers/cluster/import_test.go
Fleet's agent management logic re-imports clusters based on configuration updates, which includes API server URL and CA.
However, those config fields are only used by clusters which do not source API server URL or CA from secrets.
Clusters which do use secrets instead must not be affected by changes to API server URL and CA in config.
This patch provides unit tests validating this new behaviour.
Refers to #3061
=> Trigger cluster imports only from relevant config updates

internal/helmdeployer/install.go
Refers to: https://github.com/rancher/fleet/issues/3564
=> Avoids returning nil map when options.Helm is used

internal/cmd/agent/controller/drift_controller.go
Similar to #3245, while keeping the additional debugging added in #3334
=> Prevent empty Patch updates from Drift reconciler

.github/workflows/e2e-test-fleet-in-rancher.yml
This updates the CI workflow testing Fleet in Rancher, which would previously not check that the `rancher-webhook` deployment actually existed before checking its status. Adding that existence check prevents unwanted failures, such as [this one](https://github.com/rancher/fleet/actions/runs/14549416066/job/40818887299).
=> Wait for `rancher-webhook` deployment to exist

charts/fleet-crd/templates/crds.yaml, pkg/apis/fleet.cattle.io/v1alpha1/gitrepo_types.go
This adds validation on the `repo` field of `GitRepo` resources to check that:
* that field is provided
* its length is at least 1 character. Even if a one-char URL is provided, it will be validated by the gitOps controller which will then output an error, made visible on the `GitRepo` status, if applicable.
Refers to #3392
Written in collaboration with @khushalchandak17.
=> Prevent GitRepo creation with empty repo URL

go.mod, integrationtests/controller/bundle/bundle_targets_test.go, internal/cmd/agent/deployer/internal/resource/ignore.go
[gopkg.in](http://gopkg.in/) is a URL rewriter. 
`gopkg.in/yaml` is actually [`go-yaml/yaml`](https://github.com/go-yaml/yaml). Both are archived by the author and no longer maintained.
```
% curl -SsLfi 'gopkg.in/yaml.v3?go-get=1' | grep go-
<meta name="go-import" content="gopkg.in/yaml.v3 git https://gopkg.in/yaml.v3">
<meta name="go-source" content="gopkg.in/yaml.v3 _ https://github.com/go-yaml/yaml/tree/v3.0.1{/dir} https://github.com/go-yaml/yaml/blob/v3.0.1{/dir}/{file}#L{line}">
```
We switch to `sigs.k8s.io/yaml`, which we use in other places already:
> kubernetes-sigs/yaml is a permanent fork of [ghodss/yaml](https://github.com/ghodss/yaml).
=> Replace gopkg.in/yaml with sigs.k8s.io/yaml

internal/bundlereader/resources.go
Calls semaphone Acquire inside the go route instead to before the go routine.
Placing the Acquire call before the creation of the goroutine means that if any previously launched goroutine fails, it will cancel the shared context used by Acquire.
As a result, since Acquire is called outside the goroutine, it may return an error due to the canceled context—causing us to propagate a generic "context canceled" error instead of the original error that caused the goroutine to fail.
For example, suppose we're trying to download 10 charts, using a semaphore with a limit of 4. If the first call to `downloadDirectory` fails, the errgroup will cancel the context. Then, when the next goroutine attempts to call Acquire, it will receive an error due to the canceled context. This causes the function to …
=> Calls semaphore Acquire inside go routine

internal/bundlereader/resources.go
* Calls semaphore Acquire inside go routine
Calls semaphone Acquire inside the go route instead to before the go routine.
Placing the Acquire call before the creation of the goroutine means that if any previously launched goroutine fails, it will cancel the shared context used by Acquire.
As a result, since Acquire is called outside the goroutine, it may return an error due to the canceled context—causing us to propagate a generic "context canceled" error instead of the original error that caused the goroutine to fail.
For example, suppose we're trying to download 10 charts, using a semaphore with a limit of 4. If the first call to `downloadDirectory` fails, the errgroup will cancel the context. Then, when the next goroutine attempts to call Acquire, it will receive an error due to the …
=> [v0.11] - Calls semaphore Acquire inside go routine

cmd/fleetcli/main.go, integrationtests/gitjob/controller/controller_test.go, internal/cmd/cli/root.go, internal/cmd/controller/gitops/reconciler/gitjob.go, internal/cmd/controller/gitops/reconciler/gitjob_controller.go, internal/cmd/controller/gitops/reconciler/gitjob_test.go
Uses a JSONFormatter in fleet cli.
It also filters out the output received from fleet cli so the error set in the conditions is only the one sent by the fleet cli code and not from any used libraries.
In order to use the json formatter we need to set the `FLEET_JSON_OUTPUT` env var to `true`. This way the command line user won't get the json output unless it's explicitly specified.
Difference in the UI
Before the change:
After the change:
Refers to: https://github.com/rancher/fleet/issues/3234
=> fleet cli json output

internal/cmd/controller/gitops/reconciler/status_controller.go
Similar to #3021
The status_controller reconcile is using update, even though at a times it might not have anything to update 
we can call patch for a case of a status change, or a status from bundle is set, we also check if there is data to patch
=> Using patch instead of update to 

integrationtests/controller/bundle/bundle_helm_test.go, integrationtests/helmops/controller/suite_test.go, internal/cmd/controller/helmops/reconciler/helmop_controller.go, internal/cmd/controller/helmops/reconciler/helmop_status.go, internal/cmd/controller/reconciler/bundle_controller.go, pkg/apis/fleet.cattle.io/v1alpha1/bundle_types.go, pkg/apis/fleet.cattle.io/v1alpha1/helmop_types.go
When creating HelmOps resources, users will create and reference access secrets in the upstream cluster.
While we may not want to enforce typing of such secrets, cloning them to downstream clusters provides an opportunity to type them, thereby helping users identify secrets created by Fleet in downstream clusters, along with uses of those secrets.
This introduces 2 new secret types, applying them to previously `Opaque` secrets:
* `fleet.cattle.io/bundle-helmops-access/v1alpha1` for Helm access for deploying HelmOps bundles
* `fleet.cattle.io/bundle-oci-storage/v1alpha1` for OCI storage access when storing bundles in OCI instead of etcd.
Refers to #3435
=> Use specific secret types for access secrets cloned to downstream clusters

.github/scripts/label-downstream-cluster.sh, dev/setup-fleet-multi-cluster, dev/setup-rancher-clusters
No need to change the CI scripts. The change was not aware of the cluster's namespace and incompatible with dev/setup-rancher-clusters.
Reverts CI script change from https://github.com/rancher/fleet/pull/3139
=> Revert dev-scripts: Spawn arbitrary amount of downstream clusters

e2e/single-cluster/gitrepo_test.go, e2e/single-cluster/suite_test.go
This reduces the risk of flakiness in single-cluster end-to-end tests for `GitRepo`, by:
* refactoring test cases to use separate `When` blocks from Ginkgo, instead of a loop with `Skip` statements, to ease tracking of which test cases run and which do not
* removing the check on logs from `AfterEach`, which could cause failures. That check was added back when our reconcilers were not as mature as they are now. Such a check would anyway not belong there, but rather in integration tests covering bundle deployment cleanup.
=> Simplify GitRepo end-to-end tests

.github/scripts/update_known_hosts_configmap.sh, .github/workflows/updatecli.yml, updatecli/updatecli.d/installation.yaml, updatecli/updatecli.d/known-hosts.yaml, updatecli/values.d/scm.yaml
This provides a new updatecli pipeline to:
1. Compute up-to-date `known_hosts` entries for providers featured in the Fleet chart's `known-hosts` config map
2. Update that config map if entries have changed
3. Submit a pull request with the changes.
Example test run: [here](https://github.com/weyfonk/fleet/actions/runs/14994905550/job/42126707571), leading to [this PR](https://github.com/weyfonk/fleet/pull/5) which basically reorders entries alphabetically to ensure that future pipeline runs will not generate false positives. Once this new pipeline is merged, we should expect a similar PR against `rancher/fleet`.
Open points:
* do we need a separate pipeline for each release branch under maintenance?
=> Monitor known_hosts entries through updatecli

dev/setup-fleet, dev/update-agent-k3d, internal/cmd/agent/clusterstatus.go, internal/cmd/agent/clusterstatus/ticker.go, internal/cmd/agent/operator.go, internal/cmd/agent/root.go
Refers to https://github.com/rancher/fleet/issues/3466
Fixes a bug in main (https://github.com/rancher/fleet/pull/3436), where downstream agents could not report their status, because they used the wrong kubeconfig.
This also avoids a caching client, as we the agent is only allowed to patch cluster status in the cluster registration namespace.
=> Switch agent clusterstatus reporting to the upstream client

integrationtests/cli/apply/apply_online_test.go, internal/cmd/cli/apply/apply.go, internal/cmd/controller/helmops/reconciler/helmop_controller.go, internal/cmd/controller/helmops/reconciler/helmop_controller_test.go
When creating a bundle, Fleet checks if a different bundle already exists with the same name, and errors if so.
By "different", we mean:
* detecting existence of a non-HelmOps bundle when creating a bundle from the HelmOps reconciler
* detecting existence of a HelmOps bundle when creating a bundle from `fleet apply`.
Refers to #3435.
=> Detect bundle naming collision

integrationtests/helmops/controller/controller_test.go, internal/cmd/controller/helmops/reconciler/helmop_controller.go
This enables HelmOp resources to support semantic versioning constraints, such as `0.x.x`, `> 0.1`, etc.
Fleet will fetch the latest available chart version matching such a constraint, or return an error if the constraint is invalid or does not match any available version.
Refers to #3435 and #3763.
[fleet-docs](https://github.com/rancher/fleet-docs) repository. See https://github.com/rancher/fleet-docs/pull/257.
=> Support semantic versioning constraints in HelmOps

internal/cmd/agent/deployer/internal/diff/diff.go, internal/cmd/agent/deployer/internal/diff/kubernetes_vendor/pkg/api/v1/endpoints/util.go, internal/cmd/controller/gitops/reconciler/gitjob_controller.go, internal/cmd/controller/gitops/reconciler/gitjob_test.go, internal/cmd/controller/helmops/reconciler/helmop_controller.go
The following deprecation [warnings](https://github.com/rancher/fleet/actions/runs/15408910368/job/43356842842) will be addressed in future releases:
* `controller-runtime`'s `Result.Requeue` field, to be replaced with `Result.RequeueAfter`; see #3746
* Kubernetes' `v1.Endpoint` and `v1.EndpointSubset` resources; see #3760
=> Ignore warnings about deprecated APIs

internal/cmd/controller/helmops/reconciler/helmop_controller_test.go
Migrating away from using `Requeue` will impact the tests as well; no need for separate warnings there.
This should fix errors such as [this one](https://github.com/rancher/fleet/actions/runs/15550984255/attempts/1).
=> Ignore remaining Requeue occurrences

charts/fleet-crd/templates/crds.yaml, internal/cmd/agent/deployer/monitor/conditions_test.go, internal/cmd/agent/deployer/monitor/updatestatus.go, pkg/apis/fleet.cattle.io/v1alpha1/bundledeployment_types.go, pkg/apis/fleet.cattle.io/v1alpha1/zz_generated.deepcopy.go
Using a pointer field instead of embedding a value prevents empty ignore options from appearing in a HelmOp's specs.
Refers to #3834
=> Allow ignore options to be omitted when empty

internal/cmd/controller/helmops/reconciler/helmop_controller.go, internal/cmd/controller/helmops/reconciler/helmop_controller_test.go
OCI and direct referencing through tarballs does not involve an `index.yaml` file which Helm can search for new versions over time. Therefore, Fleet now skips Helm polling in such cases.
Refers to #3764
Follow-up to #3784.
[fleet-docs](https://github.com/rancher/fleet-docs) repository: see https://github.com/rancher/fleet-docs/pull/272
=> Skip polling for OCI and tarball charts

e2e/multi-cluster/installation/agent_test.go
Merging that test case should have been preceded by a rebase, to take validation logic into account, which uncovered a test failure. This patch fixes that failure, caused by the version field not being empty when installing a tarball chart.
Refers to #3589
Follow-up to #3806
=> Fix end-to-end test for HelmOp install with strict TLS mode

charts/fleet-crd/templates/crds.yaml, e2e/metrics/cluster_test.go, e2e/metrics/suite_test.go, integrationtests/controller/cluster/status_test.go, internal/cmd/controller/reconciler/cluster_controller.go, internal/metrics/cluster_metrics.go, pkg/apis/fleet.cattle.io/v1alpha1/cluster_types.go
HelmOp resources were previously missing from cluster statuses and metrics.
They are now reflected there next to GitRepos, with 2 new status fields:
* `DesiredReadyHelmOps`
* `ReadyHelmOps`
Refers to #3435
Related to https://github.com/rancher/dashboard/issues/14713
=> Add HelmOps to cluster status and metrics

integrationtests/helmops/controller/controller_test.go, internal/cmd/controller/helmops/reconciler/helmop_controller.go, internal/cmd/controller/helmops/reconciler/helmop_controller_test.go, internal/cmd/controller/helmops/reconciler/helmop_status.go, internal/cmd/controller/helmops/reconciler/polling_job.go
When a HelmOp resource references a static chart version, the HelmOps controller checks Helm for existence of that version.
This prevents errors about the version not existing in the Helm index from going undetected until a bundle deployment is created and an agent attempts to deploy it.
Consequently, this also ensures that errors about the version not existing are produced even if no target cluster is found for the HelmOp.
Refers to #3763
Follow-up to #3747.
=> Check Helm for static version

internal/cmd/controller/reconciler/bundledeployment_controller.go, pkg/durations/durations.go
Do not requeue immediately if status update fails, but after a short delay.
Refers to #3881
=> Use patch to update bundledeployment status

charts/fleet/templates/rbac_helmops.yaml, integrationtests/helmops/controller/controller_test.go, internal/cmd/controller/helmops/reconciler/polling_job.go
It also enables patching events for the HelmOp controller as both issues were found in the same test.
Refers to: https://github.com/rancher/fleet/issues/3896
Refers to: https://github.com/rancher/fleet/issues/3898
=> Helmops controller resets conditions after recovering from error

.github/scripts/check-for-known-hosts-changes.sh, .github/workflows/check-changes.yml, .github/workflows/updatecli.yml, updatecli/updatecli.d/known-hosts.yaml
This makes auto-generated changes to the `known-hosts` config map a bit more robust, by:
* Running the update script against each PR updating that config map, to detect any discrepancies ([example run](https://github.com/weyfonk/fleet/pull/14))
* Advising reviewers of any PR generated by updatecli and updating that config map to manually check that the generated updates to the config map are sound ([example PR description](https://github.com/weyfonk/fleet/pull/17))
It also fixes logic to call the update script itself, to fix runtime errors such as [this one](https://github.com/rancher/fleet/actions/runs/16584258322/job/46906435770#step:4:328).
Follow-up to #3709.
[fleet-docs](https://github.com/rancher/fleet-docs) …
=> Request known hosts update validation

integrationtests/cli/apply/helm_test.go, internal/cmd/cli/apply/apply.go
Secrets referenced by a GitRepo's `spec.helmSecretNameForPaths` field now support globbing.
Invalid patterns will lead to `fleet apply` returning an error.
If more than one pattern matches a given bundle path, then the first pattern, in lexical order, will be used.
Refers to #3398
=> Support globbing in HelmSecretForPaths

integrationtests/cli/apply/apply_test.go, integrationtests/cli/assets/simple-fleet-yaml/deployment.yaml, integrationtests/cli/assets/simple-fleet-yaml/fleet.yaml, integrationtests/cli/assets/simple-fleet-yaml/svc.yaml
A bundle's name can be computed from a GitRepo's name and the path leading to the bundle. However, overriding that name is also possible, by populating the `name` field in a `fleet.yaml` file.
A new integration test case covers and demonstrates this.
[fleet-docs](https://github.com/rancher/fleet-docs) repository: see https://github.com/rancher/fleet-docs/pull/303
=> Test bundle name override

internal/bundlereader/loaddirectory.go
This changes how we instantiate the `registryClient` used when downloading helm charts stored in OCI registries. It fixes race conditions that could lead to `Not Logged In` or even authentication problems.
Refers to: https://github.com/rancher/fleet/issues/3915
=> Avoid using a global registry client when downloading OCI helm charts

integrationtests/controller/bundle/bundle_helm_test.go, internal/cmd/controller/reconciler/bundle_controller.go
As decribed in the related issue, some helm repositories identify versions using the "v" prefix (like v1.5.6). Although that's not recommended by Helm, those repositories are still valid.
This PR trims the "v" prefix (if exists) before checking if the version stored in the Bundle spec is semver compliant.
Refers to: https://github.com/rancher/fleet/issues/3953
=> Trims the v prefix in versions before checking if it's a valid semver

integrationtests/cli/deploy/deploy_test.go, internal/helmdeployer/install.go
Also allows atomic flag for install, not just update.
Get a chart into pending install:
```
fleet apply -o timeout-frab-bundle.yaml test ../../frab/helm/frab
fleet target -b timeout-frab-bundle.yaml > timeout-frab-bundledeployment.yaml
fleet deploy -i timeout-frab-bundledeployment.yaml
```
If the timing is right, this results in a helm chart that is in `pending-install`:
```
apiVersion: v1
data:
release: [...blob...]
kind: Secret
metadata:
labels:
name: frab-helm-frab-02710957
owner: helm
status: pending-install
version: "1"
name: sh.helm.release.v1.frab-helm-frab-02710957.v1
namespace: default
type: helm.sh/release.v1
```
Another deploy results in:
```
% fleet deploy  -i timeout-frab-bundledeployment.yaml …
```
=> Stuck helm release in pending-install are replaced (SURE-10627)

internal/cmd/controller/agentmanagement/scheduling/scheduling.go, internal/cmd/controller/agentmanagement/scheduling/scheduling_test.go
=> Disable `0` (string) values in PDB

internal/cmd/controller/reconciler/bundle_controller.go
When using a rollout strategy to maximize the partition size:
```
rolloutStrategy:
maxUnavailable: 100%
autoPartitionSize: 100%
```
logger would log this for 50 bundles to 2000 clusters:
```
fleet-controller-5588b654fc-g2sxw fleet-controller {"level":"info","ts":"2025-09-22T16:10:58Z","logger":"bundle","msg":"Unchanged bundledeployment","controller":"bundle","controllerGroup":"fleet.cattle.io","controllerKind":"Bundle","Bundle":{"name":"scale-50-single-scale-50-bundles-fourty-thirty-five","namespace":"fleet-default"},"namespace":"fleet-default","name":"scale-50-single-scale-50-bundles-fourty-thirty-five","reconcileID":"100752e9-1f32-49ed-b371-07227a91e68b","gitrepo":"scale-50-single","commit":"c61c1ecb79473a24745fa84c4bf10cca56e9c8c2","manifestID":"s-21d4568ce16f9b2b635e976f918b33eca5e2a73 …
```
=> Don't add same field multiple times to logger

internal/cmd/cli/apply/apply.go, internal/cmd/controller/reconciler/bundle_controller.go
Refers to https://github.com/rancher/fleet/issues/4143
This is a quick fix, to remove the secrets faster and not rely entirely on garbage collection.
=> Explicitly delete bundle secrets on bundle deletion

internal/cmd/controller/finalize/finalize.go, internal/cmd/controller/reconciler/bundledeployment_controller.go
This happens occasionally as the bundledeployment controller is triggered a lot.
I believe the bundledeployment controller can exhaust all its workers, until they maybe time out. This happens as it requeues not-found errors for resources which will not reappear. For example, Grafana shows 5000 workers in use, but there is no CPU load and no log messages.
Restarting the fleet-controller is a workaround.
=> Don't requeue for missing resources

integrationtests/controller/bundle/status_test.go, internal/cmd/controller/gitops/reconciler/gitjob_controller.go, internal/cmd/controller/gitops/reconciler/predicate.go, internal/cmd/controller/reconciler/bundle_controller.go, internal/cmd/controller/reconciler/predicate.go
A bundle must only be reconciled upon changes impacting its spec, or a related cluster or bundle deployment. Changes to the bundle's status must not lead to new reconciles, which may cause endless loops.
Relates to #4167.
=> Prevent bundle reconciles triggered by bundle status updates

.github/workflows/e2e-ci.yml, e2e/require-secrets/gitrepo_test.go, internal/cmd/cli/gitcloner/cloner.go, pkg/git/netutils.go
Fleet is now able to authenticate to git using an access token, beside HTTP basic auth and SSH.
This applies to fetching a repository's latest commit and to cloning.
While Github supports personal access tokens on their own, Bitbucket requires a username to be set as `x-token-auth` beside the token.
This patch includes an end-to-end test case for Github.
Refers to #4038
[fleet-docs](https://github.com/rancher/fleet-docs) repository: https://github.com/rancher/fleet-docs/pull/334
=> Support git auth with access token

.github/scripts/deploy-fleet.sh, cmd/codegen/hack/generate_and_sort_crds.sh, pkg/git/remote.go, pkg/git/remote_test.go
This backports fixes brought to `main` by #4177.
It also fixes [typos](https://github.com/rancher/fleet/actions/runs/18223727485/job/51889447456?pr=4190) preventing CI from succeeding. 
=> [v0.13] Fix CI blockers
